# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/{petId}/uploadImage_post for http method type POST 
# RoostTestHash=8dac89cb33
# 
# 

# ********RoostGPT********
import pytest
import json
import os


@pytest.fixture
def test_data():
    """Load test data from JSON file."""
    file_path = os.path.join(os.path.dirname(__file__), "pet_petId_uploadImage.json")
    with open(file_path, 'r') as json_file:
        return json.load(json_file)


@pytest.mark.parametrize("test_case", ["successful operation", "Invalid pet ID", "Invalid file format", "Pet not found"])
def test_upload_image(test_data, test_case, api_helper, valid_api_key, invalid_api_key, oauth2_token):
    """
    Test cases for the /v2/pet/{petId}/uploadImage endpoint.
    Covers response validation, schema validation, and edge cases.
    """

    # Initialize test case data from JSON
    case_data = next((item for item in test_data if item["scenario"] == test_case), None)
    assert case_data, f"No test data found for scenario: {test_case}"

    # Extract test case parameters
    pet_id = case_data["petId"]
    additional_metadata = case_data["additionalMetadata"]
    file_name = case_data["file"]
    expected_status_code = case_data["statusCode"]

    # Set up request parameters
    endpoint = f"v2/pet/{pet_id}/uploadImage"
    headers = {
        "Authorization": f"Bearer {oauth2_token}"
    }
    files = {"file": (file_name, open(os.path.join(os.path.dirname(__file__), file_name), "rb"))} if file_name else None
    data = {
        "additionalMetadata": additional_metadata
    }

    # Make API call
    try:
        response = api_helper.make_request(endpoint=endpoint, method='POST', headers=headers, params=data, files=files)
    except FileNotFoundError as e:
        assert expected_status_code == 415, f"Expected 415 but file was missing, error: {str(e)}"
        return

    # Assert status code
    assert response.status_code == expected_status_code, (
        f"Unexpected status code for scenario '{test_case}':"
        f" Expected {expected_status_code} but got {response.status_code}."
    )

    # Validate the 200 response schema
    if response.status_code == 200:
        assert response.headers["Content-Type"] == "application/json", (
            f"Expected 'application/json', but got {response.headers['Content-Type']}."
        )
        response_json = response.json()
        assert "code" in response_json and isinstance(response_json["code"], int), "Response code is invalid."
        assert "type" in response_json and isinstance(response_json["type"], str), "Response type is invalid."
        assert "message" in response_json and isinstance(response_json["message"], str), "Response message is invalid."


@pytest.mark.parametrize("auth_scenario", ["valid_key", "invalid_key", "missing_key"])
def test_security_scenario_upload_image(auth_scenario, api_helper, test_data, valid_api_key, invalid_api_key):
    """
    Test security scenarios for the /v2/pet/{petId}/uploadImage endpoint.
    Tests valid, invalid, and missing authentication key cases.
    """
    # Load test case data (using successful operation scenario)
    case_data = next((item for item in test_data if item["scenario"] == "successful operation"), None)
    assert case_data, "Test data not found for default scenario 'successful operation'."

    # Extract parameters
    pet_id = case_data["petId"]
    additional_metadata = case_data["additionalMetadata"]
    file_name = case_data["file"]

    # Set up request parameters
    endpoint = f"v2/pet/{pet_id}/uploadImage"
    headers = {}
    files = {"file": (file_name, open(os.path.join(os.path.dirname(__file__), file_name), "rb"))} if file_name else None
    data = {
        "additionalMetadata": additional_metadata
    }

    if auth_scenario == "valid_key":
        headers["Authorization"] = f"Bearer {valid_api_key}"
        expected_status_code = case_data["statusCode"]
    elif auth_scenario == "invalid_key":
        headers["Authorization"] = f"Bearer {invalid_api_key}"
        expected_status_code = 401
    elif auth_scenario == "missing_key":
        expected_status_code = 403
    else:
        pytest.fail(f"Invalid auth_scenario provided: {auth_scenario}")

    # Make API request
    response = api_helper.make_request(endpoint=endpoint, method='POST', headers=headers, params=data, files=files)

    # Assert security-based status codes
    assert response.status_code == expected_status_code, (
        f"Unexpected status code for auth scenario '{auth_scenario}':"
        f" Expected {expected_status_code} but got {response.status_code}."
    )


def test_invalid_http_method(api_helper, valid_api_key):
    """
    Test invalid HTTP method for the /v2/pet/{petId}/uploadImage endpoint.
    """
    endpoint = "v2/pet/12345/uploadImage"
    headers = {
        "Authorization": f"Bearer {valid_api_key}"
    }

    # Attempt to call POST endpoint using GET method
    response = api_helper.make_request(endpoint=endpoint, method='GET', headers=headers)

    # Assert 405 Method Not Allowed response
    assert response.status_code == 405, (
        f"Expected 405 with GET method for 'uploadImage', but got {response.status_code}."
    )


def test_invalid_url(api_helper, valid_api_key):
    """
    Test invalid endpoint URL for the /v2/pet/{petId}/uploadImage API.
    """
    endpoint = "v2/pet/9999/uploadFile"  # Intentionally incorrect
    headers = {
        "Authorization": f"Bearer {valid_api_key}"
    }

    response = api_helper.make_request(endpoint=endpoint, method='POST', headers=headers)

    # Assert 404 Not Found in case of missing endpoint
    assert response.status_code == 404, (
        f"Expected 404 with incorrect URL, but got {response.status_code}."
    )
