# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/{petId}/uploadImage_post for http method type POST 
# RoostTestHash=8dac89cb33
# 
# 

# ********RoostGPT********
import pytest
import os
import requests
from conftest import get_base_url, get_auth_headers  # Import functions from conftest
import json


@pytest.fixture
def test_data():
    """
    Fixture to load test data from the JSON file.
    """
    current_dir = os.path.dirname(__file__)
    json_path = os.path.join(current_dir, "pet_petId_uploadImage.json")
    with open(json_path, "r") as test_file:
        return json.load(test_file)


@pytest.fixture
def api_config():
    """
    Fixture to load configuration from the config.yml file.
    """
    current_dir = os.path.dirname(__file__)
    config_path = os.path.join(current_dir, "config.yml")
    with open(config_path, "r") as config_file:
        return config_file.read()  # Assume YAML parsing handled inside conftest or other utility


@pytest.mark.parametrize("test_case", [{"scenario": obj["scenario"], **obj} for obj in test_data()])
def test_upload_pet_image(test_case, api_config):
    """
    Test cases for the /v2/pet/{petId}/uploadImage API endpoint.

    This function iterates through all test cases defined in the JSON file.
    """
    # Fetch base URL from configuration
    base_url = get_base_url(api_config)

    # Setup endpoint
    endpoint = f"/v2/pet/{test_case['petId']}/uploadImage"

    # Prepare request payload
    data = {
        "additionalMetadata": test_case["additionalMetadata"]
    }
    files = {
        "file": open(os.path.join(os.path.dirname(__file__), test_case["file"]), "rb")
    } if test_case["file"] else None

    # Prepare full API URL
    url = base_url + endpoint

    # Call API with authentication handled using get_auth_headers function
    response = requests.post(
        url,
        headers=get_auth_headers(api_config),
        data=data,
        files=files
    )

    # Assert response status code matches expected
    assert response.status_code == test_case["statusCode"], (
        f"Expected {test_case['statusCode']} for scenario '{test_case['scenario']}', "
        f"but got {response.status_code}. Response: {response.text}"
    )

    # Verify response body for successful operations
    if response.status_code == 200:
        response_json = response.json()
        assert "code" in response_json, "Response body is missing 'code'."
        assert "type" in response_json, "Response body is missing 'type'."
        assert "message" in response_json, "Response body is missing 'message'."
    elif response.status_code == 422 or response.status_code == 400:
        # Optionally assert specific error messages/body formats for error codes.
        pass  # Placeholder for future validation.


def test_missing_authentication(api_config):
    """
    Test the API endpoint without authentication headers.
    """
    # Fetch base URL from configuration
    base_url = get_base_url(api_config)

    # Use a valid petId example
    endpoint = "/v2/pet/12345/uploadImage"

    # Prepare request payload
    data = {
        "additionalMetadata": "Sample metadata"
    }
    files = {
        "file": open(os.path.join(os.path.dirname(__file__), "sample_pet_image.jpg"), "rb")
    }

    # Prepare full API URL
    url = base_url + endpoint

    # Call API without authentication headers
    response = requests.post(
        url,
        data=data,
        files=files
    )

    # Assert response returns appropriate unauthorized error
    assert response.status_code == 401, "Expected 401 Unauthorized but did not get it."
    assert "error" in response.text.lower(), "Expected error message in response."


def test_invalid_authentication(api_config):
    """
    Test the API endpoint with invalid authentication headers.
    """
    # Fetch base URL from configuration
    base_url = get_base_url(api_config)

    # Use a valid petId example
    endpoint = "/v2/pet/54321/uploadImage"

    # Prepare request payload
    data = {
        "additionalMetadata": "Additional comments"
    }
    files = {
        "file": open(os.path.join(os.path.dirname(__file__), "pet_display_image.jpeg"), "rb")
    }

    # Prepare full API URL
    url = base_url + endpoint

    # Call API with invalid authentication headers
    response = requests.post(
        url,
        headers={"Authorization": "InvalidBearerToken"},
        data=data,
        files=files
    )

    # Assert response returns appropriate unauthorized error
    assert response.status_code == 403, "Expected 403 Forbidden but did not get it."
    assert "error" in response.text.lower(), "Expected error message in response."
