# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /me_get for http method type GET 
# RoostTestHash=4f4e94f0a0
# 
# 

# ********RoostGPT********
import pytest
import os
import json
from validator import SwaggerSchemaValidator

# Load the API schema for validation
BASE_PATH = os.path.dirname(__file__)
SPEC_PATH = os.path.join(BASE_PATH, "api.json")
swagger_validator = SwaggerSchemaValidator(SPEC_PATH)

# Test Data File
TEST_DATA_FILE = os.path.join(BASE_PATH, "me.json")


@pytest.mark.parametrize("test_case", json.load(open(TEST_DATA_FILE)))
def test_me_endpoint(api_client, valid_api_key, oauth2_token, test_case):
    """
    Test the /me endpoint using data-driven tests from the JSON file.
    Validates the request and response against the OpenAPI schema.
    """
    # Extract test case details from the JSON file
    scenario = test_case["scenario"]
    status_code = test_case["statusCode"]
    expected_response_body = test_case["responseBody"]
    swagger_data_info = test_case.get("swaggerDataInfo", {})
    
    # Headers for the request
    headers = {
        "Authorization": f"Basic {oauth2_token}"
    }

    # Execute the HTTP GET request
    response = api_client.get("/me", headers=headers)

    assert response.status_code == status_code, (
        f"Test failed for scenario '{scenario}', expected status {status_code} "
        f"but got {response.status_code}. Response body: {response.text}"
    )

    # Validate response JSON with the Swagger schema for 200 status
    if status_code == 200:
        response_data = response.json()

        # Ensure the response schema matches the expected schema
        swagger_validator.validate_with_schema(
            response_data,
            schema={
                "type": "object",
                "properties": {
                    "id": {"type": "string", "format": "uuid"},
                    "login": {"type": "string"},
                    "name": {"type": "string"},
                },
                "required": ["id", "login", "name"],
            }
        )
        assert response_data is not None, "Expected a valid response body for status code 200."
    
        # Additional optional cross-checking with test case 'responseBody' if exists.
        if expected_response_body:
            assert response.json() == expected_response_body, (
                f"Expected body does not match for scenario '{scenario}'. "
                f"Expected {expected_response_body}, got {response.json()}"
            )

    # Validate error response for other status codes
    elif status_code != 200:
        response_data = response.json()
        swagger_validator.validate_with_schema(
            response_data,
            schema={
                "type": "object",
                "properties": {
                    "message": {"type": "string"}
                }
            }
        )

    print(f"Test passed for scenario: {scenario}")


def test_me_endpoint_with_invalid_auth(api_client, invalid_api_key):
    """
    Test /me endpoint with invalid authentication to verify proper error handling.
    """
    headers = {
        "Authorization": f"Basic {invalid_api_key}"
    }

    response = api_client.get("/me", headers=headers)

    assert response.status_code == 401, "Expected status 401 for invalid authentication."
    response_data = response.json()
    swagger_validator.validate_with_schema(
        response_data,
        schema={
            "type": "object",
            "properties": {
                "message": {"type": "string"}
            }
        }
    )
    print("Test passed for invalid authentication scenario.")


def test_me_endpoint_missing_auth(api_client):
    """
    Test /me endpoint with missing authentication header to verify proper error handling.
    """
    response = api_client.get("/me", headers=None)

    assert response.status_code == 401, "Expected status 401 for missing authentication."
    response_data = response.json()
    swagger_validator.validate_with_schema(
        response_data,
        schema={
            "type": "object",
            "properties": {
                "message": {"type": "string"}
            }
        }
    )
    print("Test passed for missing authentication scenario.")

# Instructions for Running Tests
"""
1. Ensure pytest is installed in your environment by running `pip install pytest`.
2. Set the required environment variables in your OS:
   - CIRCLECI_API_API_HOST: Base URL for the API.
   - Circle-Token: Your API key for header-based authentication.
   - CIRCLECI_API_AUTH_USERNAME: Your token for Basic Auth.
3. Place api.json, validator.py, conftest.py, and me.json in the same directory as this test file.
4. Run the tests using the command: `pytest -s test_me.py`.
"""
