# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /context_get for http method type GET 
# RoostTestHash=2f15b78843
# 
# 

# ********RoostGPT********
import pytest
import requests
from jsonschema import validate

# Base URL Configuration
BASE_URL = "https://circleci.com/api/v2"
CIRCLE_TOKEN = "your_circleci_token"  # Replace with your actual token

# Fixtures
@pytest.fixture(scope="module")
def headers():
    """Returns authorization headers."""
    return {"Circle-Token": CIRCLE_TOKEN}

@pytest.fixture(scope="module")
def base_url():
    """Base URL for the API."""
    return BASE_URL


# Schema for the 200 Response
SUCCESS_RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "items": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {"type": "string", "format": "uuid"},
                    "name": {"type": "string"},
                    "created_at": {"type": "string", "format": "date-time"},
                },
                "required": ["id", "name", "created_at"],
            },
        },
        "next_page_token": {"type": "string", "x-nullable": True},
    },
    "required": ["items", "next_page_token"],
}

# Schema for the Default Error Response
ERROR_RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "message": {"type": "string"},
    },
}

# Test Suite
class TestContextAPI:
    """Tests for the /context endpoint."""

    @pytest.mark.parametrize(
        "query_params",
        [
            {"owner-id": "c65b68ef-e73b-4bf2-be9a-7a322a9df150"},  # Valid Owner ID
            {"owner-slug": "sample-org-slug"},  # Valid Owner Slug
            {"owner-type": "organization"},  # Valid Owner Type
            {},  # No query parameters
        ],
    )
    def test_list_contexts_success(self, base_url, headers, query_params):
        """
        Test the /context endpoint with valid tokens and parameters.
        """
        response = requests.get(f"{base_url}/context", headers=headers, params=query_params)

        # Assert the HTTP status code
        assert response.status_code == 200, f"Unexpected status code: {response.status_code}"

        # Validate the response schema
        response_json = response.json()
        validate(instance=response_json, schema=SUCCESS_RESPONSE_SCHEMA)

    @pytest.mark.parametrize(
        "headers_override",
        [
            {},  # Missing Token
            {"Circle-Token": "invalid_token"},  # Invalid Token
        ],
    )
    def test_list_contexts_auth_errors(self, base_url, headers_override):
        """
        Test the /context endpoint with invalid or missing tokens.
        """
        response = requests.get(f"{base_url}/context", headers=headers_override)

        # Assert the HTTP status code
        assert response.status_code != 200, "Expected an authentication error response."

        # Validate the error response schema if applicable
        if response.status_code in [401, 403]:  # Unauthorized or Forbidden
            response_json = response.json()
            validate(instance=response_json, schema=ERROR_RESPONSE_SCHEMA)

    def test_list_contexts_server_error(self, base_url, headers, requests_mock):
        """
        Simulate a server error for the /context endpoint.
        """
        requests_mock.get(f"{base_url}/context", status_code=500)

        response = requests.get(f"{base_url}/context", headers=headers)

        # Assert the HTTP status code
        assert response.status_code == 500, "Expected a 500 Internal Server Error."

    @pytest.mark.parametrize(
        "invalid_params",
        [
            {"owner-id": "invalid-uuid"},  # Invalid Owner ID
            {"owner-slug": ""},  # Empty Owner Slug
            {"owner-type": "invalid_type"},  # Unsupported Owner Type
        ],
    )
    def test_list_contexts_bad_request(self, base_url, headers, invalid_params):
        """
        Test the /context endpoint with invalid query parameters.
        """
        response = requests.get(f"{base_url}/context", headers=headers, params=invalid_params)

        # Assert the HTTP status code
        assert response.status_code == 400, "Expected a 400 Bad Request."

        # Validate the error response schema
        response_json = response.json()
        validate(instance=response_json, schema=ERROR_RESPONSE_SCHEMA)
