# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /insights/{org-slug}/summary_get for http method type GET 
# RoostTestHash=fca8c865dc
# 
# 

# ********RoostGPT********
import pytest
import requests
import json


@pytest.fixture(scope="module")
def base_url():
    return "https://circleci.com/api/v2"


@pytest.fixture(scope="module")
def auth_header():
    return {
        "Authorization": "Basic REPLACE_BASIC_AUTH"
    }


@pytest.fixture
def valid_org_slug():
    return "gh/CircleCI-Public"


@pytest.fixture
def valid_query_params():
    return {
        "reporting-window": "last-90-days",
        "project-names": ["api-preview-docs", "another-project"]
    }


@pytest.fixture
def invalid_auth_header():
    return {
        "Authorization": "Basic INVALID_AUTH"
    }


@pytest.fixture
def invalid_org_slug():
    return "invalid/org"


@pytest.mark.parametrize("status_code, org_slug, auth", [
    (200, "gh/CircleCI-Public", "auth_header"),
    (401, "gh/CircleCI-Public", "invalid_auth_header"),
    (404, "invalid/org", "auth_header"),
])
def test_get_summary_metrics(base_url, status_code, org_slug, auth, request):
    """
    Test the GET /insights/{org-slug}/summary endpoint.
    Covers various status codes: 200 (Success), 401 (Unauthorized), 404 (Not Found).
    """
    # Fetch dynamic auth header using fixture name
    auth_header = request.getfixturevalue(auth)
    endpoint = f"/insights/{org_slug}/summary"
    response = requests.get(base_url + endpoint, headers=auth_header)

    assert response.status_code == status_code, f"Expected {status_code}, got {response.status_code}"
    
    if status_code == 200:
        response_json = response.json()

        # Validate top-level schema
        assert "org_data" in response_json, "'org_data' field missing in response."
        assert "org_project_data" in response_json, "'org_project_data' field missing in response."
        assert "all_projects" in response_json, "'all_projects' field missing in response."

        # Validate 'org_data' schema structure
        org_data = response_json["org_data"]
        assert "metrics" in org_data, "'metrics' field missing in 'org_data'."
        assert "trends" in org_data, "'trends' field missing in 'org_data'."

        # Validate 'metrics' in org_data
        metrics = org_data["metrics"]
        assert "total_runs" in metrics, "'total_runs' field missing in 'metrics'."
        assert isinstance(metrics["total_runs"], int), "Expected 'total_runs' to be integer."
        assert metrics["total_runs"] >= 0, "'total_runs' must be non-negative."

        assert "total_duration_secs" in metrics, "'total_duration_secs' field missing in 'metrics'."
        assert isinstance(metrics["total_duration_secs"], int), "Expected 'total_duration_secs' to be integer."
        assert metrics["total_duration_secs"] >= 0, "'total_duration_secs' must be non-negative."

        assert "total_credits_used" in metrics, "'total_credits_used' field missing in 'metrics'."
        assert isinstance(metrics["total_credits_used"], int), "Expected 'total_credits_used' to be integer."
        assert metrics["total_credits_used"] >= 0, "'total_credits_used' must be non-negative."

        assert "success_rate" in metrics, "'success_rate' field missing in 'metrics'."
        assert isinstance(metrics["success_rate"], float), "Expected 'success_rate' to be float."

        assert "throughput" in metrics, "'throughput' field missing in 'metrics'."
        assert isinstance(metrics["throughput"], float), "Expected 'throughput' to be float."

        # Further validation omitted for brevity


def test_invalid_auth(base_url, valid_org_slug, invalid_auth_header):
    """
    Test the API Authentication with invalid credentials.
    Expected status code: 401 Unauthorized.
    """
    endpoint = f"/insights/{valid_org_slug}/summary"
    response = requests.get(base_url + endpoint, headers=invalid_auth_header)

    assert response.status_code == 401, "Authentication check failed."


def test_missing_auth(base_url, valid_org_slug):
    """
    Test the API endpoint with missing credentials.
    Expected status code: 401 Unauthorized.
    """
    endpoint = f"/insights/{valid_org_slug}/summary"
    response = requests.get(base_url + endpoint)

    assert response.status_code == 401, "Missing authentication check failed."


def test_invalid_org_slug(base_url, invalid_org_slug, auth_header):
    """
    Test the API with an invalid organization slug.
    Expected status code: 404 Not Found.
    """
    endpoint = f"/insights/{invalid_org_slug}/summary"
    response = requests.get(base_url + endpoint, headers=auth_header)

    assert response.status_code == 404, "Invalid organization slug check failed."


@pytest.mark.parametrize("query_params", [
    {"reporting-window": "last-90-days"},
    {"project-names": ["project1", "project2"]},
    {},
])
def test_query_params(base_url, valid_org_slug, query_params, auth_header):
    """
    Test the API with different combinations of query parameters.
    """
    endpoint = f"/insights/{valid_org_slug}/summary"
    response = requests.get(base_url + endpoint, headers=auth_header, params=query_params)

    assert response.status_code == 200, f"Unexpected status code: {response.status_code}"


@pytest.fixture(scope="module")
def config_file():
    with open("config.json", "r") as f:
        return json.load(f)


@pytest.mark.parametrize("param_name, param_value", [
    ("reporting-window", "last-30-days"),
    ("project-names", ["project-1", "project-2"]),
])
def test_dynamic_query_params(base_url, valid_org_slug, param_name, param_value, auth_header):
    """
    Test the API using dynamic parameters from configuration file.
    """
    endpoint = f"/insights/{valid_org_slug}/summary"
    response = requests.get(base_url + endpoint, headers=auth_header, params={param_name: param_value})

    assert response.status_code == 200, f"Unexpected status code for {param_name}: {response.status_code}"
