# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /insights/{project-slug}/workflows/{workflow-name}/summary_get for http method type GET 
# RoostTestHash=2e0178896c
# 
# 

# ********RoostGPT********
import pytest
import requests
from requests.auth import HTTPBasicAuth

# Test configuration
BASE_URL = "https://circleci.com/api/v2"
API_ENDPOINT = "/insights/{project_slug}/workflows/{workflow_name}/summary"
VALID_PROJECT_SLUG = "gh/CircleCI-Public/api-preview-docs"
VALID_WORKFLOW_NAME = "build-and-test"
VALID_CREDENTIALS = ("username", "password")  # Replace with valid username and password
INVALID_CREDENTIALS = ("invalid_user", "invalid_pass")


@pytest.fixture(scope="module")
def api_url():
    """Fixture to return the API URL."""
    return BASE_URL + API_ENDPOINT.format(
        project_slug=VALID_PROJECT_SLUG, workflow_name=VALID_WORKFLOW_NAME
    )


@pytest.fixture(scope="module")
def auth_headers():
    """Fixture to return the valid authentication header."""
    return HTTPBasicAuth(*VALID_CREDENTIALS)


@pytest.fixture(scope="module")
def invalid_auth_headers():
    """Fixture to return invalid authentication header."""
    return HTTPBasicAuth(*INVALID_CREDENTIALS)


@pytest.mark.parametrize("query_params,expected_status", [
    ({"all-branches": True}, 200),
    ({"branch": "main"}, 200),
    ({}, 200),  # Default branch
])
def test_valid_requests(api_url, auth_headers, query_params, expected_status):
    """
    Test valid API requests with different query parameters.
    """
    response = requests.get(api_url, auth=auth_headers, params=query_params)
    assert response.status_code == expected_status
    
    # Validate JSON schema
    response_json = response.json()
    assert "metrics" in response_json
    assert "trends" in response_json
    assert "workflow_names" in response_json


def test_missing_auth(api_url):
    """
    Test API request with missing authentication headers.
    """
    response = requests.get(api_url)
    assert response.status_code == 401 or response.status_code == 403  # Unauthorized or Forbidden


def test_invalid_auth(api_url, invalid_auth_headers):
    """
    Test API request with invalid authentication credentials.
    """
    response = requests.get(api_url, auth=invalid_auth_headers)
    assert response.status_code == 401 or response.status_code == 403  # Unauthorized or Forbidden


@pytest.mark.parametrize("query_params", [
    ({"all-branches": "INVALID_VALUE"}),  # Invalid boolean value
    ({"branch": 12345}),  # Invalid branch type (integer instead of string)
])
def test_invalid_query_params(api_url, auth_headers, query_params):
    """
    Test API request with invalid query parameters.
    """
    response = requests.get(api_url, auth=auth_headers, params=query_params)
    assert response.status_code == 400 or response.status_code == 422  # Bad Request or Unprocessable Entity


@pytest.mark.parametrize("query_params", [
    ({"all-branches": True}),  # Valid query param
    ({})
])
def test_response_schema(api_url, auth_headers, query_params):
    """
    Validate response schema for successful requests.
    """
    response = requests.get(api_url, auth=auth_headers, params=query_params)
    assert response.status_code == 200

    json_data = response.json()
    assert "metrics" in json_data
    assert "trends" in json_data
    assert "workflow_names" in json_data

    # Validate metrics structure
    metrics = json_data["metrics"]
    assert "total_runs" in metrics
    assert "successful_runs" in metrics
    assert "failed_runs" in metrics
    
    # Validate trends structure
    trends = json_data["trends"]
    assert "total_runs" in trends
    assert "failed_runs" in trends

    # Validate workflow_names
    assert isinstance(json_data["workflow_names"], list)


def test_server_error(api_url, auth_headers):
    """
    Simulate server error response by providing invalid slug/workflow in path.
    """
    invalid_api_url = BASE_URL + API_ENDPOINT.format(
        project_slug="invalid-slug", workflow_name="invalid-workflow"
    )
    response = requests.get(invalid_api_url, auth=auth_headers)
    assert response.status_code == 500 or response.status_code == 404  # Internal Server Error or Not Found
