# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /insights/{project-slug}/workflows/{workflow-name}/test-metrics_get for http method type GET 
# RoostTestHash=1e497c49fd
# 
# 

# ********RoostGPT********
import pytest
import requests
from requests.auth import HTTPBasicAuth

BASE_URL = "https://circleci.com/api/v2"
ENDPOINT = "insights/{project_slug}/workflows/{workflow_name}/test-metrics"

# Test data and configuration
@pytest.fixture(scope="module")
def config():
    return {
        "base_url": BASE_URL,
        "endpoint": ENDPOINT,
        "auth": {
            "username": "test_username",
            "password": "test_password"
        },
        "project_slug": "gh/CircleCI-Public/api-preview-docs",
        "workflow_name": "build-and-test"
    }

@pytest.fixture
def headers(config):
    return {
        "Authorization": f"Basic {requests.auth._basic_auth_str(config['auth']['username'], config['auth']['password'])}"
    }

@pytest.fixture
def query_params():
    return [
        {},
        {"branch": "main"},
        {"all-branches": True},
    ]

@pytest.fixture
def invalid_auth_header():
    return {"Authorization": "Basic INVALID_CREDENTIALS"}

def build_url(config, query):
    query_string = "&".join(f"{k}={v}" for k, v in query.items() if v is not None)
    endpoint = config["endpoint"].format(project_slug=config["project_slug"], workflow_name=config["workflow_name"])
    return f"{config['base_url']}/{endpoint}?{query_string}"

# Test cases
@pytest.mark.parametrize("query", query_params())
def test_successful_response(headers, config, query):
    """
    Test GET operation with valid authentication and valid parameters.
    """
    url = build_url(config, query)
    response = requests.get(url, headers=headers)
    
    assert response.status_code == 200
    assert isinstance(response.json(), dict)

    # Validate response schema
    response_data = response.json()
    assert "average_test_count" in response_data
    assert isinstance(response_data["average_test_count"], int)

    assert "most_failed_tests" in response_data
    assert isinstance(response_data["most_failed_tests"], list)

@pytest.mark.parametrize("query", query_params())
def test_missing_authentication(config, query):
    """
    Test GET operation without authentication header.
    """
    url = build_url(config, query)
    response = requests.get(url)
    
    assert response.status_code == 401 or response.status_code == 403
    assert "message" in response.json()

@pytest.mark.parametrize("query", query_params())
def test_invalid_authentication(config, query, invalid_auth_header):
    """
    Test GET operation with invalid authentication.
    """
    url = build_url(config, query)
    response = requests.get(url, headers=invalid_auth_header)
    
    assert response.status_code == 401 or response.status_code == 403
    assert "message" in response.json()

@pytest.mark.parametrize("query", query_params())
def test_missing_required_parameters(headers, query):
    """
    Test GET operation with missing required parameters.
    """
    modified_query = query.copy()
    modified_query.pop("branch", None)
    modified_query.pop("all-branches", None)

    url = f"{BASE_URL}/insights//workflows/test-metrics"
    response = requests.get(url, headers=headers)

    assert response.status_code == 404

def test_default_error(config, headers):
    """
    Test GET operation expecting default error response.
    """
    url = build_url(config, {"branch": "invalid_branch"})
    response = requests.get(url, headers=headers)
    
    assert response.status_code != 200
    assert "message" in response.json()

@pytest.mark.parametrize("query", query_params())
def test_boundary_cases(headers, config, query):
    """
    Test GET operation for boundary cases for parameters.
    """
    query.update({"branch": "!" * 255})
    url = build_url(config, query)
    response = requests.get(url, headers=headers)
    
    assert response.status_code == 400 or response.status_code == 422
    assert "message" in response.json()

