# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /insights/{project-slug}/workflows/{workflow-name}_get for http method type GET 
# RoostTestHash=4918eb1733
# 
# 

# ********RoostGPT********
# test_api.py

import pytest
import requests
from datetime import datetime, timedelta


BASE_URL = "https://circleci.com/api/v2"
ENDPOINT = "/insights/{project-slug}/workflows/{workflow-name}"


@pytest.fixture
def auth_headers():
    """Fixture for authentication headers."""
    return {"Authorization": "Basic REPLACE_BASIC_AUTH"}


@pytest.fixture
def url():
    """Fixture for generating dynamic URLs."""
    project_slug = "gh/CircleCI-Public/api-preview-docs"
    workflow_name = "build-and-test"
    return BASE_URL + ENDPOINT.format(project_slug=project_slug, workflow_name=workflow_name)


@pytest.fixture
def query_params():
    """Fixture for query parameters."""
    start_date = datetime.utcnow() - timedelta(days=90)
    end_date = datetime.utcnow()
    return {
        "all-branches": "true",
        "branch": "main",
        "page-token": None,
        "start-date": start_date.isoformat() + "Z",
        "end-date": end_date.isoformat() + "Z",
    }


@pytest.mark.parametrize("branch, expected_status", [
    ("main", 200),
    ("non-existing-branch", 200),  # Handles if no data available
])
def test_get_workflow_runs_success(url, auth_headers, branch, expected_status):
    """Test retrieving recent workflow runs with valid parameters."""
    params = {"branch": branch}
    response = requests.get(url, headers=auth_headers, params=params)
    assert response.status_code == expected_status
    if response.status_code == 200:
        assert "items" in response.json()
        assert isinstance(response.json()["items"], list)
        assert "next_page_token" in response.json()


def test_get_workflow_runs_missing_auth(url):
    """Test endpoint without authentication."""
    response = requests.get(url)
    assert response.status_code == 401
    assert "message" in response.json()


@pytest.mark.parametrize("missing_param", ["start-date", "end-date"])
def test_get_workflow_runs_missing_required_params(url, auth_headers, query_params, missing_param):
    """Test endpoint with omitted required query parameters."""
    query_params.pop(missing_param)
    response = requests.get(url, headers=auth_headers, params=query_params)
    assert response.status_code == 400


def test_get_workflow_runs_invalid_pagination(url, auth_headers, query_params):
    """Test invalid pagination token."""
    query_params["page-token"] = "INVALID_TOKEN"
    response = requests.get(url, headers=auth_headers, params=query_params)
    assert response.status_code in [400, 404]
    assert "message" in response.json()


def test_get_workflow_runs_schema_validation(url, auth_headers, query_params, jsonschema):
    """Test response schema validation."""
    response = requests.get(url, headers=auth_headers, params=query_params)
    assert response.status_code == 200

    # Response Schema as per OpenAPI Spec
    response_schema = {
        "type": "object",
        "properties": {
            "items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {"type": "string", "format": "uuid"},
                        "branch": {"type": "string"},
                        "duration": {"type": "integer", "minimum": 0},
                        "created_at": {"type": "string", "format": "date-time"},
                        "stopped_at": {"type": "string", "format": "date-time"},
                        "credits_used": {"type": "integer", "minimum": 0},
                        "status": {"type": "string"},
                        "is_approval": {"type": "boolean"},
                    },
                    "required": [
                        "id",
                        "branch",
                        "duration",
                        "created_at",
                        "stopped_at",
                        "credits_used",
                        "status",
                        "is_approval",
                    ],
                },
            },
            "next_page_token": {"type": "string"},
        },
        "required": ["items", "next_page_token"],
    }

    # Validate response payload
    jsonschema.validate(instance=response.json(), schema=response_schema)


def test_get_workflow_runs_internal_server_error(url, auth_headers):
    """Simulate internal server error."""
    # Assuming we can inject/mock server payload for 500. Alternatively, test against a real scenario.
    response = requests.get(url, headers=auth_headers, params={"branch": "main"})
    assert response.status_code in [500, 502, 503]


# Instructions for running the tests:
# 1. Install dependencies: pip install pytest requests jsonschema
# 2. Add a valid Authorization header where indicated above.
# 3. Save the test file as `test_api.py`.
# 4. Run tests using: pytest test_api.py
