# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /jobs/{job-id}/cancel_post for http method type POST 
# RoostTestHash=647b98788e
# 
# 

# ********RoostGPT********
import pytest
import requests
from uuid import uuid4

# Configuration Constants
BASE_URL = "https://circleci.com/api/v2"
AUTH_HEADER = {"Authorization": "Basic REPLACE_BASIC_AUTH"}

# Pytest Fixtures
@pytest.fixture
def valid_job_id():
    return str(uuid4())  # Generate a mock UUID for the test

@pytest.fixture
def invalid_job_id():
    return "invalid-uuid"  # Invalid UUID

@pytest.fixture
def base_url():
    return BASE_URL

@pytest.fixture
def headers():
    return AUTH_HEADER

# Test Suite: Cancel Job Endpoint
@pytest.mark.parametrize(
    "job_id, expected_status, expected_message",
    [
        ("valid-job-id-placeholder", 200, "Job cancelled successfully."),
        ("invalid-job-id-placeholder", 400, "Bad request error."),
    ],
)
def test_cancel_job_status_codes(job_id, expected_status, expected_message, base_url, headers):
    """
    Test the /jobs/{job-id}/cancel endpoint for various response codes.
    """
    url = f"{base_url}/jobs/{job_id}/cancel"
    response = requests.post(url, headers=headers)
    assert response.status_code == expected_status
    if response.status_code == 200:
        assert response.json()["message"] == expected_message


def test_cancel_job_valid_uuid(valid_job_id, base_url, headers):
    """
    Test cancel job endpoint with valid job ID.
    """
    url = f"{base_url}/jobs/{valid_job_id}/cancel"
    response = requests.post(url, headers=headers)
    assert response.status_code == 200
    assert "message" in response.json()
    assert response.json()["message"] == "Job cancelled successfully."


def test_cancel_job_invalid_uuid(invalid_job_id, base_url, headers):
    """
    Test cancel job endpoint with invalid UUID.
    """
    url = f"{base_url}/jobs/{invalid_job_id}/cancel"
    response = requests.post(url, headers=headers)
    assert response.status_code == 400
    assert "message" in response.json()
    assert response.json()["message"] == "Bad request error."


def test_auth_missing(base_url, valid_job_id):
    """
    Test cancel job endpoint with missing authentication header.
    """
    url = f"{base_url}/jobs/{valid_job_id}/cancel"
    response = requests.post(url)  # No authorization header
    assert response.status_code == 401
    assert "message" in response.json()
    assert response.json()["message"] == "Unauthorized error."


def test_auth_invalid(base_url, valid_job_id):
    """
    Test cancel job endpoint with invalid authentication.
    """
    invalid_headers = {"Authorization": "Basic INVALID_AUTH"}
    url = f"{base_url}/jobs/{valid_job_id}/cancel"
    response = requests.post(url, headers=invalid_headers)
    assert response.status_code == 403
    assert "message" in response.json()
    assert response.json()["message"] == "Forbidden error."


def test_job_not_found(base_url):
    """
    Test cancel job endpoint with non-existent job ID.
    """
    non_existent_job_id = str(uuid4())  # Random UUID that represents a non-existent job
    url = f"{base_url}/jobs/{non_existent_job_id}/cancel"
    response = requests.post(url, headers=AUTH_HEADER)
    assert response.status_code == 404
    assert "message" in response.json()
    assert response.json()["message"] == "Job not found error."

# Instructions for Running Tests
# - Install dependencies: pip install pytest requests
# - Run tests using: pytest <filename>.py
