# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /me/collaborations_get for http method type GET 
# RoostTestHash=ff854080c5
# 
# 

# ********RoostGPT********
import pytest
import requests
from requests.auth import HTTPBasicAuth

# Base URL for the API
BASE_URL = "https://circleci.com/api/v2"

# Fixtures for configuration
@pytest.fixture
def api_url():
    return f"{BASE_URL}/me/collaborations"

@pytest.fixture
def valid_auth():
    # Replace with valid credentials
    return HTTPBasicAuth("username", "password")

@pytest.fixture
def invalid_auth():
    # Replace with invalid credentials
    return HTTPBasicAuth("invalid_username", "invalid_password")

@pytest.fixture
def headers():
    return {"Content-Type": "application/json"}

# Test for successful response (200 OK)
def test_get_collaborations_success(api_url, valid_auth, headers):
    """Test GET /me/collaborations with valid credentials."""
    response = requests.get(api_url, auth=valid_auth, headers=headers)

    assert response.status_code == 200
    assert response.headers["Content-Type"] == "application/json"

    data = response.json()
    assert isinstance(data, list)

    for item in data:
        assert "id" in item and isinstance(item["id"], str)
        assert "vcs-type" in item and isinstance(item["vcs-type"], str)
        assert "name" in item and isinstance(item["name"], str)
        assert "avatar_url" in item and isinstance(item["avatar_url"], str)
        assert "slug" in item and isinstance(item["slug"], str)

# Test for unauthorized response (401)
def test_get_collaborations_unauthorized(api_url, invalid_auth, headers):
    """Test GET /me/collaborations with invalid credentials."""
    response = requests.get(api_url, auth=invalid_auth, headers=headers)

    assert response.status_code == 401
    assert response.headers["Content-Type"] == "application/json"

    data = response.json()
    assert "message" in data
    assert isinstance(data["message"], str)

# Test for missing authentication (401)
def test_get_collaborations_no_auth(api_url, headers):
    """Test GET /me/collaborations without authentication."""
    response = requests.get(api_url, headers=headers)

    assert response.status_code == 401
    assert response.headers["Content-Type"] == "application/json"

    data = response.json()
    assert "message" in data
    assert isinstance(data["message"], str)

# Test for unexpected server errors (5xx)
@pytest.mark.parametrize("http_error_status", [500, 502, 503, 504])
def test_get_collaborations_server_error(api_url, valid_auth, headers, http_error_status, monkeypatch):
    """Simulate server error responses (5xx) from the API."""

    def mock_get(*args, **kwargs):
        class MockResponse:
            def __init__(self):
                self.status_code = http_error_status
                self.headers = {"Content-Type": "application/json"}
                self._json = {"message": "Server error"}

            def json(self):
                return self._json

        return MockResponse()

    monkeypatch.setattr(requests, "get", mock_get)

    response = requests.get(api_url, auth=valid_auth, headers=headers)

    assert response.status_code == http_error_status
    assert response.headers["Content-Type"] == "application/json"

    data = response.json()
    assert "message" in data
    assert data["message"] == "Server error"
