# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /organization/{org-slug-or-id}/url-orb-allow-list/{allow-list-entry-id}_delete for http method type DELETE 
# RoostTestHash=c8868eae41
# 
# 

# ********RoostGPT********
import pytest
import requests
import json

# Configuration for the test suite
BASE_URL = "https://circleci.com/api/v2"
ENDPOINT = "/organization/{org_slug_or_id}/url-orb-allow-list/{allow_list_entry_id}"
AUTH_HEADER = {"Authorization": "Basic REPLACE_BASIC_AUTH"}

# Test data
TEST_ORG_SLUG_OR_ID = "gh/CircleCI-Public"
TEST_ALLOW_LIST_ENTRY_ID = "ba98990a-5a00-4cad-b55e-b44117b92e0c"

# Fixtures
@pytest.fixture
def base_url():
    return BASE_URL

@pytest.fixture
def headers():
    return AUTH_HEADER

@pytest.fixture
def valid_path_params():
    return {
        "org_slug_or_id": TEST_ORG_SLUG_OR_ID,
        "allow_list_entry_id": TEST_ALLOW_LIST_ENTRY_ID
    }

@pytest.fixture
def invalid_path_params():
    return {
        "org_slug_or_id": "invalid-org",
        "allow_list_entry_id": "invalid-id"
    }

# Test functions
class TestRemoveURLOrbAllowListEntry:
    """Test Suite for Remove URL Orb Allow List Entry API"""

    def test_remove_entry_success(self, base_url, headers, valid_path_params):
        """
        Test: Successful removal of a URL orb allow list entry
        Expected: 200 OK with correct response schema
        """
        url = f"{base_url}{ENDPOINT}".format(**valid_path_params)
        response = requests.delete(url, headers=headers)

        assert response.status_code == 200, f"Unexpected status code: {response.status_code}"
        response_data = response.json()
        assert "id" in response_data, "Response is missing 'id'"
        assert "message" in response_data, "Response is missing 'message'"
        assert response_data["id"] == valid_path_params["allow_list_entry_id"], "ID mismatch"
        assert response_data["message"], "Message is empty"

    def test_invalid_entry_404(self, base_url, headers, invalid_path_params):
        """
        Test: Invalid entry ID or organization
        Expected: 404 Not Found
        """
        url = f"{base_url}{ENDPOINT}".format(**invalid_path_params)
        response = requests.delete(url, headers=headers)

        assert response.status_code == 404, f"Unexpected status code: {response.status_code}"
        response_data = response.json()
        assert "message" in response_data, "Response is missing 'message'"

    def test_missing_auth(self, base_url, valid_path_params):
        """
        Test: Missing authentication
        Expected: 401 Unauthorized
        """
        url = f"{base_url}{ENDPOINT}".format(**valid_path_params)
        response = requests.delete(url)

        assert response.status_code == 401, f"Unexpected status code: {response.status_code}"
        response_data = response.json()
        assert "message" in response_data, "Response is missing 'message'"

    def test_invalid_auth(self, base_url, valid_path_params):
        """
        Test: Invalid authentication token
        Expected: 403 Forbidden
        """
        invalid_header = {"Authorization": "Basic INVALID_TOKEN"}
        url = f"{base_url}{ENDPOINT}".format(**valid_path_params)
        response = requests.delete(url, headers=invalid_header)

        assert response.status_code == 403, f"Unexpected status code: {response.status_code}"
        response_data = response.json()
        assert "message" in response_data, "Response is missing 'message'"


# Configuration file example
config_example = """
{
    "base_url": "https://circleci.com/api/v2",
    "auth_header": {
        "Authorization": "Basic REPLACE_BASIC_AUTH"
    },
    "test_data": {
        "valid_org_slug_or_id": "gh/CircleCI-Public",
        "valid_allow_list_entry_id": "ba98990a-5a00-4cad-b55e-b44117b92e0c",
        "invalid_org_slug_or_id": "invalid-org",
        "invalid_allow_list_entry_id": "invalid-id"
    }
}
"""

# Save config_example to config.json file
with open("config.json", "w") as config_file:
    config_file.write(config_example)

# Instructions for running the tests
"""
1. Install pytest and requests using pip.
   $ pip install pytest requests

2. Update the `config.json` file with valid credentials, base URL, and test data as needed.

3. Run the pytest test suite using the following command:
   $ pytest -v test_api.py
"""
