# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /organization_post for http method type POST 
# RoostTestHash=e5301c8a97
# 
# 

# ********RoostGPT********
import pytest
import requests
from requests.auth import HTTPBasicAuth


# pytest configuration fixtures
@pytest.fixture(scope='module')
def base_url():
    return "https://circleci.com/api/v2"


@pytest.fixture(scope='module')
def auth_credentials():
    return {"username": "your_username", "password": "your_password"}


@pytest.fixture(scope='module')
def headers():
    return {"Content-Type": "application/json"}


# Test payloads
@pytest.fixture(scope='function')
def valid_payload():
    return {"name": "NewOrganization", "vcs_type": "github"}


@pytest.fixture(scope='function')
def invalid_payload_missing_required_field():
    return {"vcs_type": "github"}  # Missing 'name'


@pytest.fixture(scope='function')
def invalid_payload_invalid_field_type():
    return {"name": 12345, "vcs_type": "github"}  # Invalid type for 'name'


# Test for the "POST /organization" endpoint
class TestCreateOrganization:
    """Tests for the Create Organization API endpoint."""

    @pytest.mark.parametrize(
        "payload, expected_status_code",
        [
            (pytest.lazy_fixture("valid_payload"), 201),
            (pytest.lazy_fixture("invalid_payload_missing_required_field"), 400),
            (pytest.lazy_fixture("invalid_payload_invalid_field_type"), 400),
        ],
    )
    def test_create_organization(self, base_url, auth_credentials, headers, payload, expected_status_code):
        """
        Test POST /organization with different payloads and expected status codes.
        """
        response = requests.post(
            url=f"{base_url}/organization",
            headers=headers,
            json=payload,
            auth=HTTPBasicAuth(auth_credentials["username"], auth_credentials["password"]),
        )
        assert response.status_code == expected_status_code

    def test_create_organization_missing_auth(self, base_url, headers, valid_payload):
        """
        Test POST /organization with missing authentication.
        """
        response = requests.post(
            url=f"{base_url}/organization",
            headers=headers,
            json=valid_payload,
        )
        assert response.status_code == 401  # Unauthorized

    def test_create_organization_invalid_auth(self, base_url, headers, valid_payload):
        """
        Test POST /organization with invalid authentication.
        """
        response = requests.post(
            url=f"{base_url}/organization",
            headers=headers,
            json=valid_payload,
            auth=HTTPBasicAuth("invalid_user", "invalid_password"),
        )
        assert response.status_code == 403  # Forbidden or 401 Unauthorized

    def test_create_organization_successful_response_schema(self, base_url, auth_credentials, headers, valid_payload):
        """
        Test the response schema of a successful organization creation.
        """
        response = requests.post(
            url=f"{base_url}/organization",
            headers=headers,
            json=valid_payload,
            auth=HTTPBasicAuth(auth_credentials["username"], auth_credentials["password"]),
        )
        assert response.status_code == 201
        response_json = response.json()
        assert "id" in response_json
        assert "name" in response_json
        assert "slug" in response_json
        assert "vcs_type" in response_json
        assert isinstance(response_json["id"], str)
        assert isinstance(response_json["name"], str)
        assert isinstance(response_json["slug"], str)
        assert isinstance(response_json["vcs_type"], str)


# Instructions for running the test suite
"""
1. Replace `your_username` and `your_password` in the `auth_credentials` fixture with actual basic auth credentials.
2. Save this file with a name like `test_create_organization.py`.
3. Install pytest and requests libraries if not already installed.
   - Run `pip install pytest requests` in your terminal.
4. Execute the test suite:
   - Run `pytest test_create_organization.py -v` in your terminal.
5. Check the test results to ensure correct functionality of the `/organization` endpoint.
"""
