# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /pipeline/{pipeline-id}/values_get for http method type GET 
# RoostTestHash=c2031e2ab2
# 
# 

# ********RoostGPT********
import pytest
import requests

# Fixtures for Base URL and Authentication
@pytest.fixture(scope="session")
def base_url():
    return "https://circleci.com/api/v2"


@pytest.fixture(scope="session")
def auth_headers():
    return {"Authorization": "Basic REPLACE_BASIC_AUTH"}


# Test Suite for /pipeline/{pipeline-id}/values endpoint
class TestPipelineValuesEndpoint:
    """Test suite for the /pipeline/{pipeline-id}/values endpoint"""

    @pytest.fixture
    def valid_pipeline_id(self):
        """Returns a valid pipeline ID for testing"""
        return "5034460f-c7c4-4c43-9457-de07e2029e7b"

    @pytest.fixture
    def invalid_pipeline_id(self):
        """Returns an invalid pipeline ID for testing"""
        return "invalid-id"

    def test_get_pipeline_values_valid_id(self, base_url, auth_headers, valid_pipeline_id):
        """Test retrieving pipeline values using a valid pipeline ID"""
        url = f"{base_url}/pipeline/{valid_pipeline_id}/values"
        response = requests.get(url, headers=auth_headers)

        assert response.status_code == 200, f"Unexpected status code: {response.status_code}"
        assert isinstance(response.json(), dict), "Response should be a JSON object"
        for value in response.json().values():
            assert isinstance(value, (str, int, bool)), "Unexpected value type in pipeline values"

    def test_get_pipeline_values_invalid_id(self, base_url, auth_headers, invalid_pipeline_id):
        """Test retrieving pipeline values using an invalid pipeline ID"""
        url = f"{base_url}/pipeline/{invalid_pipeline_id}/values"
        response = requests.get(url, headers=auth_headers)

        assert response.status_code != 200, f"Expected non-200 status code but got {response.status_code}"
        assert "message" in response.json(), "Error response should contain a 'message'"
        assert isinstance(response.json()["message"], str), "'message' should be a string"

    def test_get_pipeline_values_missing_auth(self, base_url, valid_pipeline_id):
        """Test retrieving pipeline values without authentication headers"""
        url = f"{base_url}/pipeline/{valid_pipeline_id}/values"
        response = requests.get(url)

        assert response.status_code in [401, 403], f"Unexpected status code: {response.status_code}"
        assert "message" in response.json(), "Error response should contain a 'message'"
        assert isinstance(response.json()["message"], str), "'message' should be a string"

    def test_get_pipeline_values_expired_token(self, base_url, valid_pipeline_id):
        """Test pipeline values endpoint with expired token"""
        expired_auth_headers = {"Authorization": "Basic EXPIRED_TOKEN"}
        url = f"{base_url}/pipeline/{valid_pipeline_id}/values"
        response = requests.get(url, headers=expired_auth_headers)

        assert response.status_code in [401, 403], f"Unexpected status code: {response.status_code}"
        assert "message" in response.json(), "Error response should contain a 'message'"
        assert isinstance(response.json()["message"], str), "'message' should be a string"

    @pytest.mark.parametrize(
        "pipeline_id, expected_status_code",
        [
            ("5034460f-c7c4-4c43-9457-de07e2029e7b", 200),
            ("invalid-id", 404),
        ],
    )
    def test_get_pipeline_values_parameterized(self, base_url, auth_headers, pipeline_id, expected_status_code):
        """Parameterized test for pipeline values endpoint"""
        url = f"{base_url}/pipeline/{pipeline_id}/values"
        response = requests.get(url, headers=auth_headers)

        assert response.status_code == expected_status_code, f"Unexpected status code: {response.status_code}"

