# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /pipeline_get for http method type GET 
# RoostTestHash=15b970cbc8
# 
# 

# ********RoostGPT********
import pytest
import requests

# Base URL and Authorization Token for the API
BASE_URL = "https://circleci.com/api/v2"
AUTH_HEADER = {"Authorization": "Basic REPLACE_BASIC_AUTH"}

@pytest.fixture
def headers():
    """Fixture for request headers."""
    return AUTH_HEADER

@pytest.fixture
def base_url():
    """Fixture for base API URL."""
    return BASE_URL

@pytest.fixture
def sample_query_params():
    """Sample query parameters for testing."""
    return {
        "org-slug": "gh/CircleCI-Public",
        "page-token": "SOME_STRING_VALUE",
        "mine": False
    }

@pytest.mark.parametrize("query_params, expected_status", [
    ({"org-slug": "gh/CircleCI-Public"}, 200),  # Valid org-slug
    ({"page-token": "SOME_STRING_VALUE"}, 200),  # Valid page-token
    ({"mine": True}, 200),  # Valid 'mine' boolean value
    (None, 200),  # No query parameters
])
def test_list_pipelines_success(headers, base_url, query_params, expected_status):
    """
    Test the /pipeline endpoint for successful responses.
    Valid inputs should return a status code of 200.
    """
    url = f"{base_url}/pipeline"
    response = requests.get(url, headers=headers, params=query_params)
    assert response.status_code == expected_status, f"Unexpected status code: {response.status_code}"
    assert "items" in response.json(), "Response does not contain 'items'"
    assert "next_page_token" in response.json(), "Response does not contain 'next_page_token'"


@pytest.mark.parametrize("query_params, expected_status", [
    ({"org-slug": "INVALID_ORG"}, 401),  # Invalid org-slug
    ({"mine": "INVALID_BOOLEAN"}, 400),  # Invalid query parameter type
    ({"page-token": "INVALID_TOKEN"}, 404),  # Invalid page-token
])
def test_list_pipelines_error(headers, base_url, query_params, expected_status):
    """
    Test the /pipeline endpoint for various error responses.
    Invalid inputs should return appropriate 4xx/5xx error codes.
    """
    url = f"{base_url}/pipeline"
    response = requests.get(url, headers=headers, params=query_params)
    assert response.status_code == expected_status, f"Unexpected status code: {response.status_code}"


def test_list_pipelines_unauthenticated(base_url):
    """
    Test the /pipeline endpoint with missing authentication.
    Should return a 401 Unauthorized error.
    """
    url = f"{base_url}/pipeline"
    response = requests.get(url)
    assert response.status_code == 401, f"Unexpected status code: {response.status_code}"
    assert "message" in response.json(), "Response does not contain 'message'"


def test_response_schema(headers, base_url, sample_query_params):
    """
    Validate the response schema of /pipeline endpoint.
    Checks if the structure matches what is defined in the API spec.
    """
    url = f"{base_url}/pipeline"
    response = requests.get(url, headers=headers, params=sample_query_params)
    assert response.status_code == 200, "Unexpected status code"
    data = response.json()

    # Validate keys in response object
    assert "items" in data
    assert "next_page_token" in data

    # Validate schema of items array
    for item in data["items"]:
        assert "id" in item
        assert "number" in item
        assert "project_slug" in item
        assert "created_at" in item
        assert "errors" in item
        assert isinstance(item["errors"], list)


def test_invalid_method(headers, base_url):
    """
    Test the /pipeline endpoint with an unsupported HTTP method.
    Should return a 405 Method Not Allowed error.
    """
    url = f"{base_url}/pipeline"
    response = requests.post(url, headers=headers)
    assert response.status_code == 405, f"Unexpected status code: {response.status_code}"
    assert "message" in response.json(), "Response does not contain 'message'"
