# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /project/{project-slug}/checkout-key_get for http method type GET 
# RoostTestHash=e48840e700
# 
# 

# ********RoostGPT********
import pytest
import requests

# Configuration
BASE_URL = "https://circleci.com/api/v2"
API_AUTH_HEADER = {"Authorization": "Basic REPLACE_BASIC_AUTH"}

# Fixtures
@pytest.fixture
def project_slug():
    return "gh/CircleCI-Public/api-preview-docs"

@pytest.fixture
def valid_digest():
    return "md5"

@pytest.fixture
def invalid_digest():
    return "invalid-digest-type"

@pytest.fixture
def headers():
    return API_AUTH_HEADER

# Utility function: Generate endpoint URLs
def generate_url(project_slug, digest=None):
    url = f"{BASE_URL}/project/{project_slug}/checkout-key"
    if digest:
        url += f"?digest={digest}"
    return url

# Test cases
class TestCheckoutKeyAPI:
    """Test suite for /project/{project-slug}/checkout-key API endpoint."""

    @pytest.mark.parametrize("digest", [None, "md5", "sha256"])
    def test_get_checkout_keys_valid_request(self, project_slug, headers, digest):
        """Test fetching checkout keys with valid inputs."""
        url = generate_url(project_slug, digest)
        response = requests.get(url, headers=headers)
        
        # Validate response
        assert response.status_code == 200
        response_data = response.json()
        assert "items" in response_data
        assert isinstance(response_data["items"], list)
        assert "next_page_token" in response_data

        # Validate schema of first item if exists
        if response_data["items"]:
            first_key = response_data["items"][0]
            assert "public-key" in first_key
            assert "type" in first_key
            assert "fingerprint" in first_key
            assert "preferred" in first_key
            assert "created-at" in first_key

    def test_get_checkout_keys_invalid_auth(self, project_slug):
        """Test fetching with invalid authorization header."""
        headers = {"Authorization": "Basic INVALID_AUTH"}
        url = generate_url(project_slug)
        response = requests.get(url, headers=headers)
        
        # Validate response
        assert response.status_code == 401

    def test_get_checkout_keys_missing_auth(self, project_slug):
        """Test fetching checkout keys without authorization."""
        url = generate_url(project_slug)
        response = requests.get(url)
        
        # Validate response
        assert response.status_code == 401

    def test_get_checkout_keys_invalid_digest(self, project_slug, headers, invalid_digest):
        """Test fetching checkout keys with invalid digest type."""
        url = generate_url(project_slug, invalid_digest)
        response = requests.get(url, headers=headers)
        
        # Validate response
        assert response.status_code == 400

    def test_get_checkout_keys_invalid_project_slug(self, headers):
        """Test fetching checkout keys with invalid project slug."""
        invalid_slug = "invalid-project-slug"
        url = generate_url(invalid_slug)
        response = requests.get(url, headers=headers)
        
        # Validate response
        assert response.status_code == 404

    def test_get_checkout_keys_no_optional_parameters(self, project_slug, headers):
        """Test fetching checkout keys without optional parameters."""
        url = generate_url(project_slug)
        response = requests.get(url, headers=headers)
        
        # Validate response
        assert response.status_code == 200
        response_data = response.json()
        assert "items" in response_data
        assert "next_page_token" in response_data

