# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /project/{project-slug}/pipeline_post for http method type POST 
# RoostTestHash=b6771f42df
# 
# 

# ********RoostGPT********
import pytest
import requests

BASE_URL = "https://circleci.com/api/v2"
AUTH_TOKEN = "REPLACE_BASIC_AUTH"  # Replace with your actual token


@pytest.fixture
def headers():
    """
    Fixture to provide default headers for authorization.
    """
    return {
        "Authorization": f"Basic {AUTH_TOKEN}",
        "Content-Type": "application/json",
    }


@pytest.mark.parametrize("project_slug", [
    "gh/CircleCI-Public/api-preview-docs",
])
@pytest.mark.parametrize("payload, status_code", [
    ({"branch": "feature/design-new-api"}, 201),
    ({"tag": "v3.1.4159"}, 201),
    ({"branch": "", "tag": ""}, 400),
    ({"parameters": {"deploy_prod": "invalid_value"}}, 400),  # Invalid payload
])
def test_trigger_pipeline_success(headers, project_slug, payload, status_code):
    """
    Test the 'Trigger Pipeline' API with various payloads, including valid and invalid inputs.
    """
    url = f"{BASE_URL}/project/{project_slug}/pipeline"
    response = requests.post(url, headers=headers, json=payload)

    assert response.status_code == status_code

    if status_code == 201:
        # Validate the success response schema
        response_json = response.json()
        assert "id" in response_json and isinstance(response_json["id"], str)
        assert "state" in response_json and isinstance(response_json["state"], str)
        assert "number" in response_json and isinstance(response_json["number"], int)
        assert "created_at" in response_json and isinstance(response_json["created_at"], str)
    else:
        # Validate error response schema
        response_json = response.json()
        assert "message" in response_json and isinstance(response_json["message"], str)


@pytest.mark.parametrize("project_slug", [
    "gh/CircleCI-Public/api-preview-docs",
])
@pytest.mark.parametrize("headers, status_code", [
    (None, 401),  # Missing authorization
    ({"Authorization": "InvalidToken", "Content-Type": "application/json"}, 401),  # Invalid authorization
])
def test_trigger_pipeline_auth_failure(headers, project_slug, headers, status_code):
    """
    Test authorization scenarios, including missing and invalid credentials.
    """
    url = f"{BASE_URL}/project/{project_slug}/pipeline"
    response = requests.post(url, headers=headers, json={"branch": "feature/design-new-api"})

    assert response.status_code == status_code


@pytest.mark.parametrize("project_slug", [
    "invalid/project/slug",
    "gh/invalid-org-name/invalid-repo-name",
])
def test_trigger_pipeline_invalid_slug(headers, project_slug):
    """
    Test pipeline API with invalid project slug.
    """
    url = f"{BASE_URL}/project/{project_slug}/pipeline"
    response = requests.post(url, headers=headers, json={"branch": "feature/design-new-api"})

    assert response.status_code == 404
    response_json = response.json()
    assert "message" in response_json and isinstance(response_json["message"], str)


@pytest.mark.parametrize("timeout", [2, 5, 10])
def test_trigger_pipeline_timeout(headers, timeout):
    """
    Test timeout settings for the pipeline API.
    """
    url = f"{BASE_URL}/project/gh/CircleCI-Public/api-preview-docs/pipeline"
    try:
        response = requests.post(url, headers=headers, json={"branch": "feature/design-new-api"}, timeout=timeout)
        assert response.status_code == 201 or response.status_code == 500
    except requests.exceptions.Timeout:
        pytest.fail(f"Request timed out with timeout value {timeout}s")


@pytest.mark.parametrize("payload", [
    {"branch": "feature/design-new-api", "parameters": {}},  # Empty parameters
    {"branch": "feature/design-new-api", "parameters": {"key1": "value1", "key2": "value2"}},  # Multiple valid parameters
    {"parameters": {"key_with_long_length_that_exceeds_128": "value"}},  # Exceeding key limit
])
def test_trigger_pipeline_edge_cases(headers, payload):
    """
    Test edge cases for pipeline request body parameters.
    """
    url = f"{BASE_URL}/project/gh/CircleCI-Public/api-preview-docs/pipeline"
    response = requests.post(url, headers=headers, json=payload)

    assert response.status_code in [201, 400, 422]
