# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /project/{project-slug}_get for http method type GET 
# RoostTestHash=0ed7ae20fe
# 
# 

# ********RoostGPT********
# tests/test_project_api.py

import pytest
import requests
from jsonschema import validate

BASE_URL = "https://circleci.com/api/v2"
AUTH_HEADER = {"Authorization": "Basic REPLACE_BASIC_AUTH"}


@pytest.fixture
def valid_project_slug():
    """Fixture for a valid project slug."""
    return "gh/CircleCI-Public/api-preview-docs"


@pytest.fixture
def invalid_project_slug():
    """Fixture for an invalid project slug."""
    return "invalid/slug/does-not-exist"


@pytest.fixture
def valid_request_headers():
    """Fixture for valid authentication headers."""
    return AUTH_HEADER


@pytest.fixture
def invalid_request_headers():
    """Fixture for invalid authentication headers."""
    return {"Authorization": "Basic INVALID_AUTH"}


@pytest.fixture
def base_url():
    """Fixture for the base URL."""
    return BASE_URL


@pytest.fixture
def project_response_schema():
    """Fixture for expected response schema for 200 (success)."""
    return {
        "type": "object",
        "properties": {
            "slug": {"type": "string"},
            "name": {"type": "string"},
            "id": {"type": "string", "format": "uuid"},
            "organization_name": {"type": "string"},
            "organization_slug": {"type": "string"},
            "organization_id": {"type": "string", "format": "uuid"},
            "vcs_info": {
                "type": "object",
                "properties": {
                    "vcs_url": {"type": "string"},
                    "provider": {"type": "string"},
                    "default_branch": {"type": "string"},
                },
                "required": ["vcs_url", "provider", "default_branch"],
            },
        },
        "required": [
            "slug",
            "name",
            "id",
            "organization_name",
            "organization_slug",
            "organization_id",
            "vcs_info",
        ],
    }


@pytest.mark.parametrize(
    "project_slug, headers, expected_status_code",
    [
        ("gh/CircleCI-Public/api-preview-docs", AUTH_HEADER, 200),  # Valid case
        ("invalid/slug/does-not-exist", AUTH_HEADER, 404),  # Invalid project slug
        ("gh/CircleCI-Public/api-preview-docs", None, 401),  # Missing auth header
        ("gh/CircleCI-Public/api-preview-docs", {"Authorization": "Basic INVALID_AUTH"}, 403),  # Invalid auth
    ],
)
def test_project_api(base_url, project_slug, headers, expected_status_code):
    """
    Test the /project/{project-slug} endpoint.

    Ensures handling of valid and invalid slugs, authentication, and required headers.
    """
    url = f"{base_url}/project/{project_slug}"

    response = requests.get(url, headers=headers if headers else {})
    assert response.status_code == expected_status_code

    if expected_status_code == 200:
        # Success case: Validate the response schema
        validate(instance=response.json(), schema=project_response_schema)
    elif expected_status_code in [401, 403, 404]:
        # Error cases: Generic error response schema
        error_schema = {"type": "object", "properties": {"message": {"type": "string"}}}
        validate(instance=response.json(), schema=error_schema)


def test_project_api_success_schema(
    base_url, valid_project_slug, valid_request_headers, project_response_schema
):
    """
    Test successful response schema validation for a valid project slug.
    """
    url = f"{base_url}/project/{valid_project_slug}"
    response = requests.get(url, headers=valid_request_headers)

    assert response.status_code == 200
    validate(instance=response.json(), schema=project_response_schema)


def test_project_api_auth_missing(base_url, valid_project_slug):
    """
    Test /project/{project-slug} without an authorization header.

    Verifies it returns a 401 Unauthorized status.
    """
    url = f"{base_url}/project/{valid_project_slug}"
    response = requests.get(url)

    assert response.status_code == 401
    error_schema = {"type": "object", "properties": {"message": {"type": "string"}}}
    validate(instance=response.json(), schema=error_schema)


def test_project_api_auth_invalid(base_url, valid_project_slug, invalid_request_headers):
    """
    Test /project/{project-slug} with invalid authentication headers.

    Verifies it returns a 403 Forbidden status.
    """
    url = f"{base_url}/project/{valid_project_slug}"
    response = requests.get(url, headers=invalid_request_headers)

    assert response.status_code == 403
    error_schema = {"type": "object", "properties": {"message": {"type": "string"}}}
    validate(instance=response.json(), schema=error_schema)


def test_project_api_not_found(base_url, invalid_project_slug, valid_request_headers):
    """
    Test /project/{project-slug} with a slug that does not exist.

    Verifies it returns a 404 Not Found status.
    """
    url = f"{base_url}/project/{invalid_project_slug}"
    response = requests.get(url, headers=valid_request_headers)

    assert response.status_code == 404
    error_schema = {"type": "object", "properties": {"message": {"type": "string"}}}
    validate(instance=response.json(), schema=error_schema)
