# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /project/{project-slug}/pipeline/{pipeline-number}_get for http method type GET 
# RoostTestHash=4ad1614d82
# 
# 

# ********RoostGPT********
import pytest
import requests
from jsonschema import validate

# Base URL Configuration
BASE_URL = "https://circleci.com/api/v2"

# Fixtures for Configuration
@pytest.fixture
def auth_header():
    return {"Authorization": "Basic REPLACE_BASIC_AUTH"}

@pytest.fixture
def pipeline_example():
    return {
        "project_slug": "gh/CircleCI-Public/api-preview-docs",
        "pipeline_number": 123
    }

# Schema for Response Validation
PIPELINE_SCHEMA = {
    "type": "object",
    "properties": {
        "id": {"type": "string", "format": "uuid"},
        "errors": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": {"type": "string"},
                    "message": {"type": "string"}
                },
                "required": ["type", "message"]
            }
        },
        "project_slug": {"type": "string"},
        "updated_at": {"type": "string", "format": "date-time"},
        "number": {"type": "integer", "format": "int64"},
        "trigger_parameters": {
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {"type": "string"},
                    {"type": "integer", "format": "int64"},
                    {"type": "boolean"},
                    {"type": "object"}
                ]
            }
        },
        "state": {"type": "string"},
        "created_at": {"type": "string", "format": "date-time"},
        "trigger": {
            "type": "object",
            "properties": {
                "type": {"type": "string"},
                "received_at": {"type": "string", "format": "date-time"},
                "actor": {
                    "type": "object",
                    "properties": {
                        "login": {"type": "string"},
                        "avatar_url": {"type": "string"}
                    },
                    "required": ["login", "avatar_url"]
                }
            },
            "required": ["type", "received_at", "actor"]
        },
        "vcs": {
            "type": "object",
            "properties": {
                "provider_name": {"type": "string"},
                "origin_repository_url": {"type": "string"},
                "target_repository_url": {"type": "string"},
                "revision": {"type": "string"}
            },
            "required": [
                "provider_name",
                "origin_repository_url",
                "target_repository_url",
                "revision"
            ]
        }
    },
    "required": ["id", "number", "project_slug", "created_at", "state", "trigger"]
}

# Test Cases for Endpoint /project/{project_slug}/pipeline/{pipeline_number}
@pytest.mark.parametrize(
    "pipeline_number,status_code",
    [
        (123, 200),  # Valid Pipeline Number (Success Scenario)
        (999999, 404),  # Non-existent Pipeline Number (Not Found)
        ("invalid", 400),  # Invalid Format Pipeline Number (Bad Request)
    ],
)
def test_get_pipeline(auth_header, pipeline_example, pipeline_number, status_code):
    """
    Test the GET /project/{project_slug}/pipeline/{pipeline_number} endpoint
    """
    url = f"{BASE_URL}/project/{pipeline_example['project_slug']}/pipeline/{pipeline_number}"
    response = requests.get(url, headers=auth_header)

    # Assert Status Code
    assert response.status_code == status_code

    # Schema Validation for Success Response
    if response.status_code == 200:
        validate(instance=response.json(), schema=PIPELINE_SCHEMA)

    # Assert Error Response Schema for 4xx/5xx
    if response.status_code != 200:
        error_schema = {
            "type": "object",
            "properties": {"message": {"type": "string"}},
            "required": ["message"]
        }
        validate(instance=response.json(), schema=error_schema)

# Security Tests
@pytest.mark.parametrize(
    "auth_header,status_code",
    [
        ({"Authorization": "Basic REPLACE_BASIC_AUTH"}, 200),  # Valid Credentials
        ({"Authorization": "Basic INVALID_CREDENTIALS"}, 401),  # Invalid Credentials
        ({}, 401)  # Missing Credentials
    ],
)
def test_get_pipeline_auth(auth_header, pipeline_example, status_code):
    """
    Test authentication for GET /project/{project_slug}/pipeline/{pipeline_number}
    """
    url = f"{BASE_URL}/project/{pipeline_example['project_slug']}/pipeline/{pipeline_example['pipeline_number']}"
    response = requests.get(url, headers=auth_header)
    assert response.status_code == status_code

# Instructions for Running Tests
def print_instructions():
    """
    Instructions for running pytest tests
    """
    print("To run these tests:")
    print("1. Install pytest: `pip install pytest`")
    print("2. Run tests with command: `pytest <filename>.py`")
    print("3. Ensure valid authentication credentials are set.")
    print("4. Update BASE_URL and test fixtures for your environment.")

# Print instructions as part of module execution
if __name__ == "__main__":
    print_instructions()
