# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /project/{project-slug}_delete for http method type DELETE 
# RoostTestHash=e62474b2de
# 
# 

# ********RoostGPT********
import pytest
import requests

# Configuration Fixture
@pytest.fixture(scope="module")
def config():
    return {
        "base_url": "https://circleci.com/api/v2",
        "auth_token": "REPLACE_BASIC_AUTH",  # Replace with your valid auth token
        "project_slug": "gh/CircleCI-Public/api-preview-docs"  # Replace with a test project slug
    }

# Authorization Fixture
@pytest.fixture(scope="module")
def headers(config):
    return {"Authorization": f"Basic {config['auth_token']}"}

# Test Function: DELETE Project Endpoint
@pytest.mark.parametrize(
    "project_slug, expected_status_code, expected_message",
    [
        ("gh/CircleCI-Public/api-preview-docs", 200, "Project deleted successfully"),  # Valid Request
        ("invalid/project-slug", 404, "Project not found"),  # Invalid slug
        ("", 400, "Bad Request"),  # Missing slug
    ],
)
def test_delete_project(config, headers, project_slug, expected_status_code, expected_message):
    """
    Test DELETE /project/{project-slug}
    Covers success, client error, and server error scenarios.
    """
    # Construct URL
    url = f"{config['base_url']}/project/{project_slug}"
    
    # Perform DELETE request
    response = requests.delete(url, headers=headers)
    
    # Assert status code
    assert response.status_code == expected_status_code
    
    # Assert response message
    response_json = response.json()
    assert "message" in response_json
    assert response_json["message"] == expected_message

# Test Invalid Authentication
def test_delete_project_invalid_auth(config):
    """
    Test DELETE /project/{project-slug} with invalid authentication
    """
    # Construct URL
    url = f"{config['base_url']}/project/{config['project_slug']}"
    
    # Perform DELETE request with invalid token
    invalid_headers = {"Authorization": "Basic INVALID_TOKEN"}
    response = requests.delete(url, headers=invalid_headers)
    
    # Assert 401 Unauthorized
    assert response.status_code == 401
    
    # Assert error message
    response_json = response.json()
    assert "message" in response_json
    assert response_json["message"] == "Unauthorized"

# Test Missing Authentication
def test_delete_project_missing_auth(config):
    """
    Test DELETE /project/{project-slug} without authentication
    """
    # Construct URL
    url = f"{config['base_url']}/project/{config['project_slug']}"
    
    # Perform DELETE request without headers
    response = requests.delete(url)
    
    # Assert 401 Unauthorized
    assert response.status_code == 401
    
    # Assert error message
    response_json = response.json()
    assert "message" in response_json
    assert response_json["message"] == "Unauthorized"

