# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /project/{project-slug}/schedule_get for http method type GET 
# RoostTestHash=38cfe1d56e
# 
# 

# ********RoostGPT********
import pytest
import requests
from pytest import fixture


# Configuration for test data
@fixture(scope="module")
def base_url():
    return "https://circleci.com/api/v2"


@fixture(scope="module")
def valid_auth_headers():
    return {
        "Authorization": "Basic REPLACE_BASIC_AUTH"
    }


@fixture(scope="module")
def invalid_auth_headers():
    return {
        "Authorization": "Basic INVALID_BASIC_AUTH"
    }


@fixture
def valid_project_slug():
    return "gh/CircleCI-Public/api-preview-docs"


@fixture
def invalid_project_slug():
    return "invalid/project/slug"


@pytest.mark.parametrize("auth_headers,status_code", [
    (pytest.lazy_fixture("valid_auth_headers"), 200),
    (pytest.lazy_fixture("invalid_auth_headers"), 401),
    (None, 401),
])
def test_get_schedule_with_auth(base_url, valid_project_slug, auth_headers, status_code):
    """
    Test the `/project/{project-slug}/schedule` endpoint with various authorization credentials.
    """
    url = f"{base_url}/project/{valid_project_slug}/schedule"
    headers = auth_headers if auth_headers else {}
    response = requests.get(url, headers=headers)
    assert response.status_code == status_code, f"Unexpected status code: {response.status_code}"
    if status_code == 200:
        assert "items" in response.json(), "Expected 'items' in response"


@pytest.mark.parametrize("project_slug,status_code", [
    (pytest.lazy_fixture("valid_project_slug"), 200),
    (pytest.lazy_fixture("invalid_project_slug"), 404),
])
def test_get_schedule_with_valid_and_invalid_project_slug(base_url, valid_auth_headers, project_slug, status_code):
    """
    Test the `/project/{project-slug}/schedule` endpoint with valid and invalid project slugs.
    """
    url = f"{base_url}/project/{project_slug}/schedule"
    headers = valid_auth_headers
    response = requests.get(url, headers=headers)
    assert response.status_code == status_code, f"Unexpected status code: {response.status_code}"


@pytest.mark.parametrize("query_params,status_code", [
    ({"page-token": "SOME_STRING_VALUE"}, 200),
    ({}, 200),
])
def test_get_schedule_with_query_params(base_url, valid_auth_headers, valid_project_slug, query_params, status_code):
    """
    Test the `/project/{project-slug}/schedule` endpoint with query parameters like page-token.
    """
    url = f"{base_url}/project/{valid_project_slug}/schedule"
    headers = valid_auth_headers
    response = requests.get(url, headers=headers, params=query_params)
    assert response.status_code == status_code, f"Unexpected status code: {response.status_code}"


def test_get_schedule_schema_validation(base_url, valid_auth_headers, valid_project_slug):
    """
    Test the `/project/{project-slug}/schedule` endpoint response schema validation.
    """
    url = f"{base_url}/project/{valid_project_slug}/schedule"
    headers = valid_auth_headers
    response = requests.get(url, headers=headers)
    assert response.status_code == 200, f"Unexpected status code: {response.status_code}"
    data = response.json()

    # Verify keys in response
    assert "items" in data, "'items' key not found in response"
    assert isinstance(data["items"], list), "'items' should be a list"
    assert "next_page_token" in data, "'next_page_token' key not found in response"

    # Validate nested schema for `items`
    for item in data["items"]:
        assert "id" in item, "'id' key not found in schedule item"
        assert "name" in item, "'name' key not found in schedule item"
        assert "timetable" in item, "'timetable' key not found in schedule item"
        assert "project-slug" in item, "'project-slug' key not found in schedule item"
        assert "actor" in item, "'actor' key not found in schedule item"


def test_get_schedule_without_auth(base_url, valid_project_slug):
    """
    Test the `/project/{project-slug}/schedule` endpoint without authentication.
    """
    url = f"{base_url}/project/{valid_project_slug}/schedule"
    response = requests.get(url)
    assert response.status_code == 401, f"Unexpected status code: {response.status_code}"


@pytest.mark.parametrize("edge_query_param", [
    {"page-token": ""},
    {"page-token": "invalid_token_value"}
])
def test_get_schedule_edge_query_params(base_url, valid_auth_headers, valid_project_slug, edge_query_param):
    """
    Test the `/project/{project-slug}/schedule` endpoint with edge cases in query parameters.
    """
    url = f"{base_url}/project/{valid_project_slug}/schedule"
    headers = valid_auth_headers
    response = requests.get(url, headers=headers, params=edge_query_param)
    assert response.status_code in [200, 400], f"Unexpected status code: {response.status_code}"
