# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /project/{project-slug}/envvar_get for http method type GET 
# RoostTestHash=2246026986
# 
# 

# ********RoostGPT********
import pytest
import requests
from jsonschema import validate

BASE_URL = "https://circleci.com/api/v2"
AUTH_HEADER = {"Authorization": "Basic REPLACE_BASIC_AUTH"}

# Sample valid project slug for testing
VALID_PROJECT_SLUG = "gh/CircleCI-Public/api-preview-docs"

# Response schemas
SUCCESS_RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "items": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "value": {"type": "string"},
                    "created-at": {"type": ["string", "null"]},  # Can be null
                },
                "required": ["name", "value"],
            },
        },
        "next_page_token": {"type": ["string", "null"]},  # Can be null
    },
    "required": ["items", "next_page_token"],
}

ERROR_RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "message": {"type": "string"},
    },
    "required": ["message"],
}


@pytest.fixture
def base_url():
    """Fixture for test base URL."""
    return BASE_URL


@pytest.fixture
def auth_headers():
    """Fixture for authenticated headers."""
    return AUTH_HEADER


def test_authentication_missing(base_url):
    """Test missing authentication header."""
    url = f"{base_url}/project/{VALID_PROJECT_SLUG}/envvar"
    response = requests.get(url)
    assert response.status_code == 401
    assert "message" in response.json()


def test_authentication_invalid(base_url):
    """Test invalid authentication credentials."""
    url = f"{base_url}/project/{VALID_PROJECT_SLUG}/envvar"
    invalid_auth_header = {"Authorization": "Basic INVALID"}
    response = requests.get(url, headers=invalid_auth_header)
    assert response.status_code == 401
    assert "message" in response.json()


@pytest.mark.parametrize("project_slug", [
    VALID_PROJECT_SLUG,  # Valid slug
    "invalid/project/slug",  # Invalid slug
    "gh//repo-name",  # Missing organization in slug
    "",  # Empty slug
])
def test_various_project_slugs(base_url, auth_headers, project_slug):
    """Test behavior with various project slugs."""
    url = f"{base_url}/project/{project_slug}/envvar"
    response = requests.get(url, headers=auth_headers)

    if project_slug == VALID_PROJECT_SLUG:
        assert response.status_code == 200
        validate(instance=response.json(), schema=SUCCESS_RESPONSE_SCHEMA)
    else:
        assert response.status_code in [400, 404]  # Bad request or not found
        validate(instance=response.json(), schema=ERROR_RESPONSE_SCHEMA)


def test_response_schema(base_url, auth_headers):
    """Test success response schema for valid project slug."""
    url = f"{base_url}/project/{VALID_PROJECT_SLUG}/envvar"
    response = requests.get(url, headers=auth_headers)
    assert response.status_code == 200
    validate(instance=response.json(), schema=SUCCESS_RESPONSE_SCHEMA)


def test_pagination(base_url, auth_headers):
    """Test pagination using the next_page_token."""
    url = f"{base_url}/project/{VALID_PROJECT_SLUG}/envvar"
    response = requests.get(url, headers=auth_headers)
    assert response.status_code == 200

    response_data = response.json()
    if response_data.get("next_page_token"):
        next_page_url = f"{url}?page-token={response_data['next_page_token']}"
        next_page_response = requests.get(next_page_url, headers=auth_headers)
        assert next_page_response.status_code == 200
        validate(instance=next_page_response.json(), schema=SUCCESS_RESPONSE_SCHEMA)


@pytest.mark.parametrize("headers", [
    None,  # Missing authorization
    {"Authorization": "Bearer INVALID"},  # Invalid format
])
def test_no_or_invalid_auth(base_url, headers):
    """Test endpoint with no or invalid authorization."""
    url = f"{base_url}/project/{VALID_PROJECT_SLUG}/envvar"
    response = requests.get(url, headers=headers)
    assert response.status_code == 401
    validate(instance=response.json(), schema=ERROR_RESPONSE_SCHEMA)
