# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /project/{project-slug}/schedule_post for http method type POST 
# RoostTestHash=c09a49d354
# 
# 

# ********RoostGPT********
import pytest
import requests
from jsonschema import validate

# Constants
BASE_URL = "https://circleci.com/api/v2"
ENDPOINT = "/project/{project-slug}/schedule"
HEADERS = {"Authorization": "Basic REPLACE_BASIC_AUTH", "Content-Type": "application/json"}
REQUEST_SCHEMA = {
    "type": "object",
    "properties": {
        "name": {"type": "string"},
        "timetable": {
            "anyOf": [
                {
                    "type": "object",
                    "properties": {
                        "per-hour": {"type": "integer"},
                        "hours-of-day": {"type": "array", "items": {"type": "integer"}},
                        "days-of-week": {"type": "array", "items": {"type": "string"}},
                    },
                    "required": ["per-hour", "hours-of-day", "days-of-week"]
                },
                {
                    "type": "object",
                    "properties": {
                        "per-hour": {"type": "integer"},
                        "hours-of-day": {"type": "array", "items": {"type": "integer"}},
                        "days-of-month": {"type": "array", "items": {"type": "integer"}},
                    },
                    "required": ["per-hour", "hours-of-day", "days-of-month"]
                }
            ]
        },
        "attribution-actor": {"type": "string"},
        "parameters": {"type": "object"},
        "description": {"type": ["string", "null"]},
    },
    "required": ["name", "timetable", "attribution-actor", "parameters"]
}

RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "id": {"type": "string"},
        "name": {"type": "string"},
        "timetable": {"type": "object"},
        "project-slug": {"type": "string"},
        "parameters": {"type": "object"},
        "actor": {"type": "object"},
        "description": {"type": ["string", "null"]},
        "created-at": {"type": "string"},
        "updated-at": {"type": "string"},
    },
    "required": ["id", "name", "timetable", "project-slug", "parameters", "actor", "created-at", "updated-at"]
}

# Sample data
VALID_PROJECT_SLUG = "gh/CircleCI-Public/api-preview-docs"
INVALID_PROJECT_SLUG = "gh/invalid/slug"
VALID_PAYLOAD = {
    "name": "Test Schedule",
    "timetable": {
        "per-hour": 1,
        "hours-of-day": [0],
        "days-of-week": ["MON"]
    },
    "attribution-actor": "current",
    "parameters": {"branch": "main"},
    "description": "Test Description"
}
INVALID_PAYLOAD = {
    "name": "",
    "timetable": {},
    "attribution-actor": "",
    "parameters": {},
    "description": ""
}


@pytest.fixture
def base_url():
    return BASE_URL


@pytest.fixture
def headers():
    return HEADERS


# Test cases
@pytest.mark.parametrize("project_slug, payload, status_code", [
    (VALID_PROJECT_SLUG, VALID_PAYLOAD, 201),  # Valid request
    (INVALID_PROJECT_SLUG, VALID_PAYLOAD, 404),  # Invalid project slug
    (VALID_PROJECT_SLUG, INVALID_PAYLOAD, 400),  # Invalid payload
])
def test_create_schedule(project_slug, payload, status_code, base_url, headers):
    """
    Test creating a schedule with multiple scenarios:
    - Valid data
    - Invalid project slug
    - Invalid payload
    """
    url = f"{base_url}{ENDPOINT.format(project_slug=project_slug)}"
    response = requests.post(url, json=payload, headers=headers)
    assert response.status_code == status_code

    if status_code == 201:
        validate(instance=response.json(), schema=RESPONSE_SCHEMA)
    elif status_code in [400, 404]:
        assert "message" in response.json()


def test_missing_authentication(base_url):
    """
    Test the endpoint without authentication headers.
    """
    url = f"{base_url}{ENDPOINT.format(project_slug=VALID_PROJECT_SLUG)}"
    response = requests.post(url, json=VALID_PAYLOAD)
    assert response.status_code == 401


def test_invalid_authentication(base_url):
    """
    Test the endpoint with invalid authentication credentials.
    """
    invalid_headers = {"Authorization": "Basic INVALID_AUTH", "Content-Type": "application/json"}
    url = f"{base_url}{ENDPOINT.format(project_slug=VALID_PROJECT_SLUG)}"
    response = requests.post(url, json=VALID_PAYLOAD, headers=invalid_headers)
    assert response.status_code == 401


# Setup instructions:
# 1. Replace `REPLACE_BASIC_AUTH` with the correct authorization token.
# 2. Execute the tests using: pytest <file_name>.py
