# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /project/{project-slug}/checkout-key/{fingerprint}_get for http method type GET 
# RoostTestHash=f8a50ff886
# 
# 

# ********RoostGPT********
import pytest
import requests
from requests.auth import HTTPBasicAuth

BASE_URL = "https://circleci.com/api/v2"
VALID_PROJECT_SLUG = "gh/CircleCI-Public/api-preview-docs"
VALID_FINGERPRINT = "c9:0b:1c:4f:d5:65:56:b9:ad:88:f9:81:2b:37:74:2f"
VALID_AUTH = HTTPBasicAuth("username", "password")  # Replace with valid credentials
INVALID_AUTH = HTTPBasicAuth("invalid_user", "invalid_pass")


@pytest.fixture
def base_url():
    """Fixture for base API URL."""
    return BASE_URL


@pytest.fixture
def auth():
    """Fixture for valid authentication credentials."""
    return VALID_AUTH


@pytest.fixture
def invalid_auth():
    """Fixture for invalid authentication credentials."""
    return INVALID_AUTH


@pytest.mark.parametrize(
    "project_slug,fingerprint,expected_status",
    [
        (VALID_PROJECT_SLUG, VALID_FINGERPRINT, 200),  # Valid request
        ("invalid/project-slug", VALID_FINGERPRINT, 400),  # Invalid project slug
        (VALID_PROJECT_SLUG, "invalid-fingerprint", 400),  # Invalid fingerprint
    ],
)
def test_get_checkout_key_valid_and_invalid_requests(
    base_url, auth, project_slug, fingerprint, expected_status
):
    """
    Test the GET endpoint for both valid and invalid inputs.
    """
    url = f"{base_url}/project/{project_slug}/checkout-key/{fingerprint}"
    response = requests.get(url, auth=auth)
    assert response.status_code == expected_status

    if expected_status == 200:
        response_data = response.json()
        assert "public-key" in response_data
        assert "type" in response_data
        assert "fingerprint" in response_data
        assert "preferred" in response_data
        assert "created-at" in response_data
    else:
        assert "message" in response.json()


def test_get_checkout_key_missing_auth(base_url):
    """
    Test the GET endpoint without authentication (should fail).
    """
    url = f"{base_url}/project/{VALID_PROJECT_SLUG}/checkout-key/{VALID_FINGERPRINT}"
    response = requests.get(url)
    assert response.status_code == 401
    assert "message" in response.json()


def test_get_checkout_key_invalid_auth(base_url, invalid_auth):
    """
    Test the GET endpoint with invalid authentication.
    """
    url = f"{base_url}/project/{VALID_PROJECT_SLUG}/checkout-key/{VALID_FINGERPRINT}"
    response = requests.get(url, auth=invalid_auth)
    assert response.status_code == 401
    assert "message" in response.json()


def test_get_checkout_key_edge_cases(base_url, auth):
    """
    Test the GET endpoint with edge case inputs.
    """
    url = f"{base_url}/project/{VALID_PROJECT_SLUG}/checkout-key/" \
          f"00000000000000000000000000000000000000000000"
    response = requests.get(url, auth=auth)
    assert response.status_code == 400
    assert "message" in response.json()


@pytest.mark.parametrize(
    "auth_fixture,expected_status",
    [
        (pytest.lazy_fixture("auth"), 200),  # Valid credentials
        (pytest.lazy_fixture("invalid_auth"), 401),  # Invalid credentials
    ],
)
def test_get_checkout_key_authentication_scenarios(
    base_url, auth_fixture, expected_status
):
    """
    Test the GET endpoint with different authentication scenarios.
    """
    url = f"{base_url}/project/{VALID_PROJECT_SLUG}/checkout-key/{VALID_FINGERPRINT}"
    response = requests.get(url, auth=auth_fixture)
    assert response.status_code == expected_status


def test_response_schema_validation(base_url, auth):
    """
    Validate the response schema against the OpenAPI spec.
    """
    url = f"{base_url}/project/{VALID_PROJECT_SLUG}/checkout-key/{VALID_FINGERPRINT}"
    response = requests.get(url, auth=auth)
    assert response.status_code == 200

    response_data = response.json()
    assert isinstance(response_data, dict)
    assert isinstance(response_data["public-key"], str)
    assert response_data["type"] in ["deploy-key", "github-user-key"]
    assert isinstance(response_data["fingerprint"], str)
    assert isinstance(response_data["preferred"], bool)
    assert isinstance(response_data["created-at"], str)
