# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /current.json_get for http method type GET 
# RoostTestHash=4bfd44e81d
# 
# 

# ********RoostGPT********
# test_weather_api.py

import pytest
import requests
from jsonschema import validate

# -------------------
# Pytest Config/Fixtures
# -------------------

@pytest.fixture(scope="session")
def base_url():
    return "https://api.weatherapi.com/v1"

@pytest.fixture(scope="session")
def api_key():
    return "your_api_key_here"

@pytest.fixture(scope="module")
def headers(api_key):
    return {"Authorization": api_key}

# -------------------
# Positive Test Cases
# -------------------

@pytest.mark.parametrize("query", [
    "New York", 
    "10001", 
    "NY", 
    "40.71,-74.01", 
    "192.168.1.1"
])
def test_get_realtime_weather_success(base_url, headers, query):
    """Test the /current.json endpoint with valid query"""
    params = {"q": query, "lang": "en"}
    response = requests.get(f"{base_url}/current.json", headers=headers, params=params)
    
    # Validate status code
    assert response.status_code == 200, f"Expected 200, got {response.status_code}"
    
    # JSON schema validation
    schema = {
        "type": "object",
        "properties": {
            "location": {"type": "object"},
            "current": {"type": "object"}
        },
        "required": ["location", "current"]
    }
    validate(instance=response.json(), schema=schema)
    assert "location" in response.json()
    assert "current" in response.json()

# -------------------
# Negative Test Cases
# -------------------

@pytest.mark.parametrize("query", [None, "", 12345])  # Invalid or missing queries
def test_get_realtime_weather_invalid_query(base_url, headers, query):
    """Test the /current.json endpoint with invalid or missing query"""
    params = {"q": query, "lang": "en"}
    response = requests.get(f"{base_url}/current.json", headers=headers, params=params)

    # Validate status code and error message
    assert response.status_code == 400, f"Expected 400, got {response.status_code}"
    assert response.json().get("code") in [1003, 1006], "Unexpected error code returned"
    
def test_get_realtime_weather_missing_api_key(base_url):
    """Test the /current.json endpoint without API key"""
    params = {"q": "New York", "lang": "en"}
    response = requests.get(f"{base_url}/current.json", params=params)
    
    # Validate status code
    assert response.status_code == 401, f"Expected 401, got {response.status_code}"
    assert response.json().get("code") == 1002, "Unexpected error code returned"

@pytest.mark.parametrize("invalid_key", ["invalid_key", "12345"])
def test_get_realtime_weather_invalid_api_key(base_url, invalid_key):
    """Test the /current.json endpoint with invalid API key"""
    headers = {"Authorization": invalid_key}
    params = {"q": "New York", "lang": "en"}
    response = requests.get(f"{base_url}/current.json", headers=headers, params=params)

    # Validate status code
    assert response.status_code == 401, f"Expected 401, got {response.status_code}"
    assert response.json().get("code") == 2006, "Unexpected error code returned"

def test_get_realtime_weather_exceed_quota(base_url, api_key):
    """Test the /current.json endpoint with API key that exceeds quota"""
    headers = {"Authorization": api_key}
    params = {"q": "New York", "lang": "en"}
    for _ in range(101):  # Assuming quota is 100 requests
        response = requests.get(f"{base_url}/current.json", headers=headers, params=params)
    
    # Validate status code when quota is exceeded
    assert response.status_code == 403, "Expected quota exceeding error"
    assert response.json().get("code") == 2007, "Expected error code 2007 for quota exceeded"

# -------------------
# Instructions for Setup and Running
# -------------------

"""
1. Update 'base_url' and 'api_key' in the test config fixtures.
2. Install dependencies:
   pip install pytest requests jsonschema
3. Run tests using pytest:
   pytest -v test_weather_api.py
"""
