# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /search.json_get for http method type GET 
# RoostTestHash=72ffe69306
# 
# 

# ********RoostGPT********
import pytest
import requests

BASE_URL = "https://api.weatherapi.com/v1/search.json"
API_KEY = "<your_api_key>"


@pytest.fixture
def base_headers():
    """Fixture to define default headers with API key."""
    return {
        "Content-Type": "application/json",
        "Authorization": f"ApiKey {API_KEY}"
    }


@pytest.fixture
def valid_query():
    """Sample valid query for testing."""
    return {"q": "London"}


@pytest.fixture
def invalid_query():
    """Sample invalid query for testing."""
    return {"q": ""}


@pytest.mark.parametrize("query_param, expected_status", [
    ({"q": "London"}, 200),
    ({"q": ""}, 400),
    (None, 400)
])
def test_search_endpoint_responses(base_headers, query_param, expected_status):
    """
    Test the /v1/search.json endpoint for different query parameters.

    1. Valid query (e.g., city name) should return 200.
    2. Empty query should return 400.
    3. Missing query parameter should return 400.
    """
    params = query_param if query_param else {}
    response = requests.get(BASE_URL, headers=base_headers, params=params)
    assert response.status_code == expected_status
    if response.status_code == 200:
        assert isinstance(response.json(), list)
        for item in response.json():
            assert "id" in item
            assert "name" in item
            assert "region" in item
            assert "country" in item
            assert "lat" in item
            assert "lon" in item
            assert "url" in item
    elif response.status_code == 400:
        assert "code" in response.json()
        assert "message" in response.json()


def test_missing_api_key(valid_query):
    """
    Test the /v1/search.json endpoint without an API key.
    It should return a 401 error.
    """
    response = requests.get(BASE_URL, params=valid_query)
    assert response.status_code == 401
    assert "code" in response.json()
    assert response.json()["code"] == 1002
    assert "message" in response.json()


def test_invalid_api_key(valid_query):
    """
    Test the /v1/search.json endpoint with an invalid API key.
    It should return a 401 error.
    """
    headers = {"Content-Type": "application/json", "Authorization": "ApiKey invalid_key"}
    response = requests.get(BASE_URL, headers=headers, params=valid_query)
    assert response.status_code == 401
    assert "code" in response.json()
    assert response.json()["code"] == 2006
    assert "message" in response.json()


def test_quota_exceeded(valid_query, base_headers):
    """
    Simulate exceeding the API call quota by providing a sample response.
    It should return a 403 error.
    """
    mock_response = {
        "code": 2007,
        "message": "API key has exceeded calls per month quota."
    }
    
    # Assuming we simulate the response here
    response = requests.get(BASE_URL, headers=base_headers, params=valid_query)
    if response.status_code == 403:
        assert response.json() == mock_response


@pytest.mark.parametrize("invalid_query_param, error_code, error_message", [
    ({"q": ""}, 1003, "Parameter 'q' not provided."),
    ({"q": "!@#$"}, 1006, "No location found matching parameter 'q'")
])
def test_invalid_query_scenarios(base_headers, invalid_query_param, error_code, error_message):
    """
    Test error scenarios with invalid query parameters.
    """
    response = requests.get(BASE_URL, headers=base_headers, params=invalid_query_param)
    assert response.status_code == 400
    assert response.json()["code"] == error_code
    assert response.json()["message"] == error_message
