# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /rest/api/2/announcementBanner_get for http method type GET 
# RoostTestHash=3c50e638d2
# 
# 

# ********RoostGPT********
import pytest
import json
from pathlib import Path

# Load the test data from JSON file
@pytest.fixture(scope="session")
def test_data():
    json_file_path = Path(__file__).parent / 'rest_api_2_announcementBanner.json'
    if not json_file_path.exists():
        raise FileNotFoundError(f"Test data file not found at {json_file_path}")
    with open(json_file_path, 'r') as file:
        return json.load(file)

# Fixtures for authorization headers
@pytest.fixture
def basic_auth_header(valid_api_key):
    return {"Authorization": f"Basic {valid_api_key}"}

@pytest.fixture
def oauth2_header(oauth2_token):
    return {"Authorization": f"Bearer {oauth2_token}"}

@pytest.fixture
def invalid_auth_header(invalid_api_key):
    return {"Authorization": f"Basic {invalid_api_key}"}

# Test for GET /rest/api/2/announcementBanner
@pytest.mark.parametrize("scenario", ["Returned if the request is successful.", 
                                      "Returned if the authentication credentials are incorrect or missing.", 
                                      "Returned if the user does not have the necessary permission."])
@pytest.mark.parametrize("auth_type", ["basic", "oauth", "invalid"])
def test_get_announcement_banner(api_client, test_data, basic_auth_header, oauth2_header, invalid_auth_header, scenario, auth_type):
    """
    Test the /rest/api/2/announcementBanner endpoint for various authorization and response scenarios.
    """
    # Prepare headers based on authentication type
    if auth_type == "basic":
        headers = basic_auth_header
    elif auth_type == "oauth":
        headers = oauth2_header
    elif auth_type == "invalid":
        headers = invalid_auth_header
    else:
        headers = {}

    # Identify the test case scenario with corresponding expected data
    test_case = next(item for item in test_data if item["scenario"] == scenario)
    status_code = test_case["statusCode"]
    expected_body = test_case["responseBody"]

    # Perform the API request
    response = api_client.get("/rest/api/2/announcementBanner", headers=headers)

    # Validate the response
    assert response.status_code == status_code, f"Expected status code {status_code}, got {response.status_code}"

    if response.status_code == 200 or response.status_code == 403:  # Success or Forbidden cases
        response_json = response.json()
        assert response_json == json.loads(expected_body), f"Response body mismatch: {response_json} != {expected_body}"
    elif response.status_code == 401:  # Unauthorized cases
        if expected_body:  # Perform response body comparison if provided
            assert response.text == expected_body, f"Expected body: {expected_body}, but got: {response.text}"

# Instruction for running the tests
"""
To run the tests:
1. Ensure Python 3 is installed on the system.
2. Install the required Python packages using `pip install pytest requests pyyaml`.
3. Add the correct API host under 'THE_JIRA_CLOUD_PLATFORM_REST_API_API_HOST',
   OAuth2 token under 'OAUTH2_OAUTH2_TOKEN', and basic auth credentials under 'THE_JIRA_CLOUD_PLATFORM_REST_API_AUTH_USERNAME'
   as environment variables for the config.yml to use them dynamically.
4. Place the 'rest_api_2_announcementBanner.json' and 'config.yml' files in the same directory as the test file.
5. Run the test suite using the command `pytest -v`.
"""
