# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /current.json_get for http method type GET 
# RoostTestHash=4bfd44e81d
# 
# 

# ********RoostGPT********
import pytest
import requests

# Configuration fixture
@pytest.fixture(scope="module")
def base_url():
    return "https://api.weatherapi.com/v1"  # Replace with the actual base URL of API

@pytest.fixture(scope="module")
def api_key():
    return "your_api_key"  # Replace with valid API key

@pytest.fixture
def headers(api_key):
    return {"key": api_key}

@pytest.fixture
def default_params():
    return {
        "q": "New York",  # Example query parameter. Replace with valid test parameter
        "lang": "en"      # Example language parameter
    }

# 1. Happy Path Test: Successful call to the API
def test_get_current_weather_success(base_url, headers, default_params):
    response = requests.get(f"{base_url}/current.json", params=default_params, headers=headers)
    assert response.status_code == 200
    body = response.json()
    # Validate the response schema
    assert "location" in body
    assert "current" in body
    assert isinstance(body["location"], dict)
    assert isinstance(body["current"], dict)

# 2. Parameter 'q' Not Provided (Error 400)
def test_get_current_weather_missing_q(base_url, headers):
    params_without_q = {"lang": "en"}
    response = requests.get(f"{base_url}/current.json", params=params_without_q, headers=headers)
    assert response.status_code == 400
    body = response.json()
    assert body["code"] == 1003
    assert body["message"] == "Parameter 'q' not provided."

# 3. Invalid Location in Query Parameter (Error 400)
def test_get_current_weather_invalid_location(base_url, headers):
    invalid_params = {"q": "InvalidCityName", "lang": "en"}
    response = requests.get(f"{base_url}/current.json", params=invalid_params, headers=headers)
    assert response.status_code == 400
    body = response.json()
    assert body["code"] == 1006  # No location found matching parameter 'q'

# 4. Unauthorized Request: API Key Not Provided (Error 401)
def test_get_current_weather_unauthorized_no_key(base_url, default_params):
    response = requests.get(f"{base_url}/current.json", params=default_params)
    assert response.status_code == 401
    body = response.json()
    assert body["code"] == 1002
    assert body["message"] == "API key not provided"

# 5. Unauthorized Request: Invalid API Key (Error 401)
def test_get_current_weather_invalid_api_key(base_url, default_params):
    invalid_headers = {"key": "invalid_api_key"}
    response = requests.get(f"{base_url}/current.json", params=default_params, headers=invalid_headers)
    assert response.status_code == 401
    body = response.json()
    assert body["code"] == 2006
    assert body["message"] == "API key provided is invalid"

# 6. Quota Exceeded (Error 403)
def test_get_current_weather_quota_exceeded(base_url, default_params):
    # Simulate quota exceeded error
    quota_exceeded_headers = {"key": "quota_exceeded_api_key"}
    response = requests.get(f"{base_url}/current.json", params=default_params, headers=quota_exceeded_headers)
    assert response.status_code == 403
    body = response.json()
    assert body["code"] == 2007
    assert body["message"] == "API key has exceeded calls per month quota."

# 7. Test with Missing Optional Parameter ('lang')
def test_get_current_weather_no_lang(base_url, headers):
    params_without_lang = {"q": "New York"}
    response = requests.get(f"{base_url}/current.json", params=params_without_lang, headers=headers)
    assert response.status_code == 200
    body = response.json()
    assert "location" in body
    assert "current" in body

# 8. Test Response Schema Matches Specification (Happy Path)
def test_get_current_weather_response_schema(base_url, headers, default_params):
    response = requests.get(f"{base_url}/current.json", params=default_params, headers=headers)
    assert response.status_code == 200
    body = response.json()
    required_keys_location = ["name", "region", "country", "lat", "lon", "tz_id", "localtime"]
    required_keys_current = ["last_updated", "temp_c", "temp_f", "condition", "wind_mph", "humidity"]
    for key in required_keys_location:
        assert key in body["location"]
    for key in required_keys_current:
        assert key in body["current"]

# Parameterized Test Examples (Testing Different Query Parameters)
@pytest.mark.parametrize("query_param", [
    ("New York"),
    ("Los Angeles"),
    ("London"),
    ("Toronto"),
    ("40.712776,-74.005974")  # Provide Latitude and Longitude
])
def test_get_current_weather_various_locations(base_url, headers, query_param):
    response = requests.get(f"{base_url}/current.json", params={"q": query_param}, headers=headers)
    assert response.status_code == 200
    body = response.json()
    assert "location" in body
    assert "current" in body

# Teardown Fixture to Ensure Clean State
@pytest.fixture(autouse=True)
def teardown():
    yield
    # Perform any cleanup tasks, if required
