# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /forecast.json_get for http method type GET 
# RoostTestHash=2d002b4f8c
# 
# 

# ********RoostGPT********
import pytest
import requests
from jsonschema import validate

# Configuration: Base URL and API Key
BASE_URL = "https://api.weatherapi.com/v1/forecast.json"
API_KEY = "your_api_key_here"

# Fixtures for testing configuration
@pytest.fixture
def base_url():
    return BASE_URL

@pytest.fixture
def api_key():
    return API_KEY

# Fixtures for sample request and expected data
@pytest.fixture
def valid_request_params():
    return {
        "q": "New York",
        "days": 3
    }

@pytest.fixture
def invalid_request_params():
    return {
        "q": "",
        "days": ""
    }

@pytest.fixture
def extended_request_params():
    return {
        "q": "London",
        "days": 7,
        "dt": "2023-10-01",
        "alerts": "yes",
        "aqi": "yes"
    }

# Sample response schema
@pytest.fixture
def success_response_schema():
    return {
        "type": "object",
        "properties": {
            "location": {"type": "object"},
            "current": {"type": "object"},
            "forecast": {"type": "object"},
        },
        "required": ["location", "current", "forecast"],
    }

@pytest.fixture
def error_response_schema():
    return {
        "type": "object",
        "properties": {
            "code": {"type": "integer"},
            "message": {"type": "string"}
        },
        "required": ["code", "message"]
    }

# Helper function for API call
def call_api(base_url, api_key, params):
    headers = {"key": api_key}
    response = requests.get(base_url, params=params, headers=headers)
    return response

# Test for valid request with a successful response
def test_valid_request(base_url, api_key, valid_request_params, success_response_schema):
    response = call_api(base_url, api_key, valid_request_params)
    assert response.status_code == 200
    assert response.headers["Content-Type"] == "application/json"
    response_json = response.json()
    validate(instance=response_json, schema=success_response_schema)

# Test for invalid request parameters
def test_invalid_request(base_url, api_key, invalid_request_params, error_response_schema):
    response = call_api(base_url, api_key, invalid_request_params)
    assert response.status_code == 400
    assert response.headers["Content-Type"] == "application/json"
    response_json = response.json()
    validate(instance=response_json, schema=error_response_schema)

# Test for invalid API Key
def test_invalid_api_key(base_url, invalid_request_params, error_response_schema):
    response = call_api(base_url, "invalid_api_key", invalid_request_params)
    assert response.status_code == 401
    assert response.headers["Content-Type"] == "application/json"
    response_json = response.json()
    validate(instance=response_json, schema=error_response_schema)

# Test for security scenarios (missing API Key)
def test_missing_api_key(base_url, valid_request_params, error_response_schema):
    headers = {}  # No authentication header
    response = requests.get(base_url, params=valid_request_params, headers=headers)
    assert response.status_code == 401
    assert response.headers["Content-Type"] == "application/json"
    response_json = response.json()
    validate(instance=response_json, schema=error_response_schema)

# Test for forbidden scenarios (over-quota or disabled API Key)
def test_forbidden_scenario(base_url, valid_request_params, error_response_schema):
    headers = {"key": "forbidden_api_key"}
    response = requests.get(base_url, params=valid_request_params, headers=headers)
    assert response.status_code == 403
    response_json = response.json()
    validate(instance=response_json, schema=error_response_schema)

# Test with extended request (additional query parameters)
def test_extended_request(base_url, api_key, extended_request_params, success_response_schema):
    response = call_api(base_url, api_key, extended_request_params)
    assert response.status_code == 200
    response_json = response.json()
    validate(instance=response_json, schema=success_response_schema)

# Test for boundary conditions (minimum and maximum days)
@pytest.mark.parametrize("days", [1, 14, 15])  # 15 is out-of-bound
def test_boundary_days(base_url, api_key, days, error_response_schema, success_response_schema):
    params = {"q": "New York", "days": days}
    response = call_api(base_url, api_key, params)
    if days == 15:  # Expecting error for out-of-bound value
        assert response.status_code == 400
        response_json = response.json()
        validate(instance=response_json, schema=error_response_schema)
    else:
        assert response.status_code == 200
        response_json = response.json()
        validate(instance=response_json, schema=success_response_schema)

# Instructions for setup and execution
"""
1. Update the BASE_URL and API_KEY variables with your respective values.
2. Install pytest: pip install pytest
3. Install jsonschema: pip install jsonschema
4. Run tests: pytest <filename>.py
"""
