# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /forecast.json_get for http method type GET 
# RoostTestHash=2d002b4f8c
# 
# 

# ********RoostGPT********
import pytest
import requests

# Configuration fixture
@pytest.fixture(scope="session")
def api_config():
    return {
        "base_url": "https://api.weatherapi.com/v1/forecast.json",
        "api_key": "your_api_key_here",
    }


# Fixture for API headers
@pytest.fixture
def api_headers(api_config):
    return {
        "Content-Type": "application/json",
        "key": api_config["api_key"],
    }


# Fixture for valid query parameters
@pytest.fixture
def valid_query_params():
    return {
        "q": "New York",
        "days": 7,
    }


# Fixture for invalid query parameters
@pytest.fixture
def invalid_query_params():
    return {
        "q": "",  # Missing location
        "days": 0,  # Invalid days value
    }


# Helper function for making API requests
def make_api_request(url, headers, params, method="GET"):
    if method == "GET":
        response = requests.get(url, headers=headers, params=params)
    else:
        raise ValueError(f"Unsupported method: {method}")
    return response


# Test for valid forecast API request
def test_forecast_valid_request(api_config, api_headers, valid_query_params):
    """Test the forecast API with valid query parameters."""
    response = make_api_request(api_config["base_url"], api_headers, valid_query_params)
    assert response.status_code == 200

    json_response = response.json()
    assert "location" in json_response
    assert "current" in json_response
    assert "forecast" in json_response


# Test for invalid forecast API request (missing 'q')
def test_forecast_missing_q(api_config, api_headers, invalid_query_params):
    """Test the forecast API with missing or empty 'q' parameter."""
    invalid_query_params["days"] = 7  # Ensure 'days' is valid
    response = make_api_request(api_config["base_url"], api_headers, invalid_query_params)
    assert response.status_code == 400

    json_response = response.json()
    assert "code" in json_response
    assert json_response["code"] == 1003
    assert "message" in json_response
    assert json_response["message"] == "Parameter 'q' not provided."


# Test for invalid API key
@pytest.fixture
def invalid_api_headers(api_config):
    return {
        "Content-Type": "application/json",
        "key": "invalid_api_key",
    }


def test_invalid_api_key(api_config, invalid_api_headers, valid_query_params):
    """Test the forecast API with an invalid API key."""
    response = make_api_request(api_config["base_url"], invalid_api_headers, valid_query_params)
    assert response.status_code == 401

    json_response = response.json()
    assert "code" in json_response
    assert json_response["code"] in [1002, 2006]
    assert "message" in json_response
    assert "API key" in json_response["message"]


# Test for exceeding API quota
def test_exceeding_api_quota(api_config, api_headers, valid_query_params):
    """Test case for API quota exceeded."""
    response = make_api_request(api_config["base_url"], api_headers, valid_query_params)
    if response.status_code == 403:
        json_response = response.json()
        assert "code" in json_response
        assert json_response["code"] == 2007
        assert "message" in json_response
        assert json_response["message"] == "API key has exceeded calls per month quota."


# Parameterized test for edge case of 'days' parameter
@pytest.mark.parametrize("days, expected_status", [
    (0, 400),  # Invalid value
    (15, 400),  # Exceeding maximum value
    (14, 200),  # Valid maximum value
])
def test_days_edge_case(api_config, api_headers, valid_query_params, days, expected_status):
    """Test edge cases for the 'days' query parameter."""
    valid_query_params["days"] = days
    response = make_api_request(api_config["base_url"], api_headers, valid_query_params)
    assert response.status_code == expected_status


# Test for API output schema validation
def test_schema_validation(api_config, api_headers, valid_query_params):
    """Validate the schema of API response."""
    response = make_api_request(api_config["base_url"], api_headers, valid_query_params)
    assert response.status_code == 200

    json_response = response.json()
    assert "location" in json_response and isinstance(json_response["location"], dict)
    assert "current" in json_response and isinstance(json_response["current"], dict)
    assert "forecast" in json_response and isinstance(json_response["forecast"], dict)
    assert "forecastday" in json_response["forecast"] and isinstance(json_response["forecast"]["forecastday"], list)


# Instructions for running tests
if __name__ == "__main__":
    print("Run the following command to execute the tests:")
    print("pytest -v --tb=short")
