# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /ip.json_get for http method type GET 
# RoostTestHash=5693e62dd1
# 
# 

# ********RoostGPT********
import pytest
import requests
from jsonschema import validate

# Configuration fixture for base URL and API key
@pytest.fixture(scope="module")
def config():
    return {
        "base_url": "http://sampleapi.com/v1/ip.json",
        "api_key": "sample_api_key",
    }

# Expected response schemas
SCHEMA_200 = {
    "type": "object",
    "properties": {
        "ip": {"type": "string"},
        "type": {"type": "string"},
        "continent_code": {"type": "string"},
        "continent_name": {"type": "string"},
        "country_code": {"type": "string"},
        "country_name": {"type": "string"},
        "is_eu": {"type": "boolean"},
        "geoname_id": {"type": "integer"},
        "city": {"type": "string"},
        "region": {"type": ["string", "null"]},
        "lat": {"type": "number"},
        "lon": {"type": "number"},
        "tz_id": {"type": "string"},
        "localtime_epoch": {"type": "integer"},
        "localtime": {"type": "string"},
    },
    "required": ["ip", "type", "continent_code", "country_name"],
}

SCHEMA_ERROR = {
    "type": "object",
    "properties": {
        "code": {"type": "integer"},
        "message": {"type": "string"},
    },
    "required": ["code", "message"],
}

# Helper function to add API key to headers
def add_auth_headers(api_key):
    return {"Authorization": f"Bearer {api_key}"}

# Test for 200 Response
def test_ip_lookup_valid(config):
    """Test valid IP lookup."""
    url = config["base_url"]
    headers = add_auth_headers(config["api_key"])
    params = {"q": "185.249.71.82"}
    
    response = requests.get(url, headers=headers, params=params)
    assert response.status_code == 200
    validate(instance=response.json(), schema=SCHEMA_200)

# Test for 400 Response: Missing Query Parameter
def test_ip_lookup_missing_query(config):
    """Test response when query parameter is missing."""
    url = config["base_url"]
    headers = add_auth_headers(config["api_key"])
    
    response = requests.get(url, headers=headers)
    assert response.status_code == 400
    validate(instance=response.json(), schema=SCHEMA_ERROR)
    assert response.json()["code"] == 1003

# Test for 401 Response: Missing API Key
def test_ip_lookup_missing_api_key(config):
    """Test response when API key is missing."""
    url = config["base_url"]
    params = {"q": "185.249.71.82"}
    
    response = requests.get(url, params=params)  # No headers
    assert response.status_code == 401
    validate(instance=response.json(), schema=SCHEMA_ERROR)
    assert response.json()["code"] == 1002

# Test for 401 Response: Invalid API Key
def test_ip_lookup_invalid_api_key(config):
    """Test response when API key is invalid."""
    url = config["base_url"]
    headers = add_auth_headers("invalid_api_key")
    params = {"q": "185.249.71.82"}
    
    response = requests.get(url, headers=headers, params=params)
    assert response.status_code == 401
    validate(instance=response.json(), schema=SCHEMA_ERROR)
    assert response.json()["code"] == 2006

# Test for 403 Response: Exceeded Quota
def test_ip_lookup_exceeded_quota(config, mocker):
    """Mocked response test for exceeded quota."""
    url = config["base_url"]
    headers = add_auth_headers(config["api_key"])
    params = {"q": "185.249.71.82"}
    
    mocker.patch(
        "requests.get",
        return_value=mocker.Mock(
            status_code=403,
            json=lambda: {"code": 2007, "message": "API key has exceeded calls per month quota."},
        )
    )
    response = requests.get(url, headers=headers, params=params)
    assert response.status_code == 403
    validate(instance=response.json(), schema=SCHEMA_ERROR)
    assert response.json()["code"] == 2007

# Parametrized Edge Cases Test
@pytest.mark.parametrize("ip_address", ["", "12345", "aaa.bbb.ccc.ddd", None])
def test_ip_lookup_invalid_ip(config, ip_address):
    """Test various invalid IP cases."""
    url = config["base_url"]
    headers = add_auth_headers(config["api_key"])
    params = {"q": ip_address}
    
    response = requests.get(url, headers=headers, params=params)
    assert response.status_code == 400
    validate(instance=response.json(), schema=SCHEMA_ERROR)


# Cleanup fixture for teardown (if needed for persistent changes)
@pytest.fixture(autouse=True)
def cleanup():
    yield
    # Any cleanup logic (e.g., deleting mock data) can be added here
