# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /ip.json_get for http method type GET 
# RoostTestHash=5693e62dd1
# 
# 

# ********RoostGPT********
import pytest
import requests

# Configuration data
BASE_URL = "https://api.example.com/v1/ip.json"
API_KEY = "your_api_key_here"

@pytest.fixture
def valid_headers():
    """Return headers with valid API key."""
    return {"Authorization": f"ApiKey {API_KEY}"}

@pytest.fixture
def invalid_headers():
    """Return headers with an invalid API key."""
    return {"Authorization": "ApiKey invalid_key"}

@pytest.fixture
def missing_headers():
    """Return headers with missing API key."""
    return {}

### Test Cases for Endpoint `/v1/ip.json`
@pytest.mark.parametrize(
    "query_param, expected_status, expected_schema",
    [
        ("185.249.71.82", 200, {
            "ip": str,
            "type": str,
            "continent_code": str,
            "continent_name": str,
            "country_code": str,
            "country_name": str,
            "is_eu": bool,
            "geoname_id": int,
            "city": str,
            "region": (str, type(None)),
            "lat": float,
            "lon": float,
            "tz_id": str,
            "localtime_epoch": int,
            "localtime": str,
        }),
    ],
)
def test_get_ip_with_valid_query_param(
    valid_headers, query_param, expected_status, expected_schema
):
    """Happy path: Test GET request for 'q' with valid input."""
    url = f"{BASE_URL}?q={query_param}"
    response = requests.get(url, headers=valid_headers)
    assert response.status_code == expected_status
    response_json = response.json()

    # Validate response schema
    for key, expected_type in expected_schema.items():
        assert key in response_json
        assert isinstance(response_json[key], expected_type)


def test_get_ip_without_query_param(valid_headers):
    """Error scenario: Missing 'q' query parameter."""
    url = f"{BASE_URL}"
    response = requests.get(url, headers=valid_headers)
    assert response.status_code == 400
    response_json = response.json()
    assert "code" in response_json
    assert "message" in response_json
    assert response_json["code"] == 1003  # Specific error code for missing 'q'
    assert response_json["message"] == "Parameter 'q' not provided."


@pytest.mark.parametrize(
    "query_param, expected_code",
    [
        ("invalid_ip", 1006),
        ("", 1003),
    ],
)
def test_get_ip_with_invalid_query_param(valid_headers, query_param, expected_code):
    """Error scenarios: Invalid or empty 'q' query parameter."""
    url = f"{BASE_URL}?q={query_param}"
    response = requests.get(url, headers=valid_headers)
    assert response.status_code == 400
    response_json = response.json()
    assert "code" in response_json
    assert "message" in response_json
    assert response_json["code"] == expected_code


def test_get_ip_with_invalid_api_key(invalid_headers):
    """Error scenario: API key is invalid."""
    url = f"{BASE_URL}?q=185.249.71.82"
    response = requests.get(url, headers=invalid_headers)
    assert response.status_code == 401
    response_json = response.json()
    assert "code" in response_json
    assert "message" in response_json
    assert response_json["code"] == 2006  # Specific error code for invalid API key
    assert response_json["message"] == "API key provided is invalid"


def test_get_ip_without_api_key(missing_headers):
    """Error scenario: API key is missing."""
    url = f"{BASE_URL}?q=185.249.71.82"
    response = requests.get(url, headers=missing_headers)
    assert response.status_code == 401
    response_json = response.json()
    assert "code" in response_json
    assert "message" in response_json
    assert response_json["code"] == 1002  # Specific error code for missing API key
    assert response_json["message"] == "API key not provided"


def test_get_ip_exceeded_quota(valid_headers):
    """Error scenario: API key exceeded monthly quota."""
    url = f"{BASE_URL}?q=185.249.71.82"
    # Simulate exceeding quota, e.g., mocking the server or enforcing the condition
    response = requests.get(url, headers=valid_headers)
    # Assume server returns 403 for quota exceeded
    if response.status_code == 403:
        response_json = response.json()
        assert "code" in response_json
        assert "message" in response_json
        assert response_json["code"] == 2007  # Specific error code for exceeded quota
        assert response_json["message"] == "API key has exceeded calls per month quota."


### Utilities for Running Tests
def run_tests():
    """Utility function to run the test suite directly (optional)."""
    pytest.main()


# Instructions:
# Save this file as `test_ip_api.py` and set up the following configurations:
# 1. Replace `BASE_URL` with the actual base URL of the API.
# 2. Replace `API_KEY` with a valid API key.
# 3. Run the test suite using `pytest test_ip_api.py`.
