# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /laureates_get for http method type GET 
# RoostTestHash=9608ebea00
# 
# 

# ********RoostGPT********
# test_laureates_api.py

import pytest
import requests


@pytest.fixture(scope="module")
def base_url():
    """Base URL for the API endpoint."""
    return "https://api.example.com/2.1/laureates"


@pytest.fixture(scope="module")
def headers():
    """Default headers for API requests (modify if authentication is needed)."""
    return {"Accept": "application/json"}


def test_laureates_api_success(base_url, headers):
    """
    Test the /2.1/laureates endpoint for a successful response (200 HTTP status code).
    """
    params = {"offset": 1, "limit": 10}
    response = requests.get(base_url, headers=headers, params=params)

    assert response.status_code == 200, f"Expected status code 200 but got {response.status_code}"
    response_data = response.json()

    # Validate the response schema
    assert "laureates" in response_data, "Expected 'laureates' field in response body"
    assert isinstance(response_data["laureates"], list), "'laureates' field should be a list"
    assert "meta" in response_data, "Expected 'meta' field in response body"
    assert isinstance(response_data["meta"], dict), "'meta' field should be a dictionary"


@pytest.mark.parametrize(
    "params,expected_status_code",
    [
        ({}, 400),  # Missing required parameters
        ({"offset": -1, "limit": 10}, 422),  # Invalid 'offset' parameter
        ({"offset": 1, "limit": -10}, 422),  # Invalid 'limit' parameter
        ({"offset": 1, "limit": 10, "sort": "invalid_sort"}, 422),  # Invalid 'sort' parameter
        ({"ID": -1}, 422),  # Invalid 'ID' parameter
        ({"gender": "invalid_gender"}, 422),  # Invalid 'gender' parameter
    ],
)
def test_laureates_api_client_errors(base_url, headers, params, expected_status_code):
    """
    Test the /2.1/laureates endpoint for client error response scenarios (4xx codes).
    """
    response = requests.get(base_url, headers=headers, params=params)
    assert response.status_code == expected_status_code, f"Expected status code {expected_status_code} but got {response.status_code}"


def test_laureates_api_not_found(base_url, headers):
    """
    Test the /2.1/laureates endpoint to simulate 404 Not Found.
    """
    invalid_url = f"{base_url}/invalid"
    response = requests.get(invalid_url, headers=headers)
    assert response.status_code == 404, f"Expected status code 404 but got {response.status_code}"
    response_data = response.json()
    assert "code" in response_data, "Expected 'code' field in response body"
    assert "message" in response_data, "Expected 'message' field in response body"


def test_laureates_api_validation_error(base_url, headers):
    """
    Test the /2.1/laureates endpoint for validation errors (422 HTTP status code).
    """
    params = {"offset": "invalid_value"}  # Should trigger validation error
    response = requests.get(base_url, headers=headers, params=params)
    assert response.status_code == 422, f"Expected status code 422 but got {response.status_code}"
    response_data = response.json()

    # Validate the response schema
    assert "code" in response_data, "Expected 'code' field in response body"
    assert "message" in response_data, "Expected 'message' field in response body"


def test_valid_response_schema(base_url, headers):
    """
    Test the /2.1/laureates endpoint against the expected response schema.
    """
    params = {"offset": 1, "limit": 2}
    response = requests.get(base_url, headers=headers, params=params)
    assert response.status_code == 200, f"Expected status 200 but got {response.status_code}"
    response_data = response.json()

    # Validate "meta" field
    assert "meta" in response_data, "Expected 'meta' field in response"
    assert isinstance(response_data["meta"], dict), "Field 'meta' should be a dictionary"
    assert "offset" in response_data["meta"], "Expected 'offset' in 'meta'"
    assert "limit" in response_data["meta"], "Expected 'limit' in 'meta'"

    # Validate "laureates" field
    assert "laureates" in response_data, "Expected 'laureates' field in response"
    assert isinstance(response_data["laureates"], list), "Field 'laureates' should be a list"
    if response_data["laureates"]:
        laureate = response_data["laureates"][0]
        assert "id" in laureate, "Expected 'id' field for laureate"
        assert isinstance(laureate["id"], int), "'id' should be an integer"


# Instructions for Running Tests:
# 1. Install pytest: `pip install pytest`
# 2. Run tests: `pytest test_laureates_api.py`
# 3. To view detailed output, use: `pytest -v` or `pytest -vv`
