# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /marine.json_get for http method type GET 
# RoostTestHash=4a44035781
# 
# 

# ********RoostGPT********
import pytest
import requests

BASE_URL = "https://api.weatherapi.com"  # You can override this in fixtures.
ENDPOINT = "/v1/marine.json"
API_KEY = "your_api_key"  # Replace with the actual API key.

@pytest.fixture
def api_headers():
    """Fixture to provide headers for requests."""
    return {
        "key": API_KEY
    }

@pytest.fixture
def valid_params():
    """Fixture for default valid query params."""
    return {
        "q": "40.7128,-74.0060",  # Example: Latitude/Longitude of New York
        "days": 3
    }


# Test: 200 OK Response
@pytest.mark.parametrize("lang", [None, "en", "fr", "es"])  # Different language codes
@pytest.mark.parametrize("hour", [None, 6, 15, 23])  # Different hour values
def test_marine_weather_success(api_headers, valid_params, lang, hour):
    """Tests the successful 200 OK response with various combinations of optional parameters."""
    params = valid_params.copy()
    if lang:
        params["lang"] = lang
    if hour:
        params["hour"] = hour

    response = requests.get(BASE_URL + ENDPOINT, params=params, headers=api_headers)
    assert response.status_code == 200

    # Validate response schema (partial validation as an example)
    data = response.json()
    assert "location" in data
    assert "forecast" in data
    assert "name" in data["location"]
    assert isinstance(data["location"]["name"], str)
    assert "forecastday" in data["forecast"]
    assert isinstance(data["forecast"]["forecastday"], list)


# Test: 401 Unauthorized
def test_marine_weather_missing_api_key(valid_params):
    """Tests the 401 Unauthorized error when API key is missing."""
    response = requests.get(BASE_URL + ENDPOINT, params=valid_params)
    assert response.status_code == 401
    data = response.json()
    assert data["code"] == 1002
    assert data["message"] == "API key not provided"


def test_marine_weather_invalid_api_key(valid_params):
    """Tests the 401 Unauthorized error when an invalid API key is provided."""
    headers = {"key": "invalid_api_key"}
    response = requests.get(BASE_URL + ENDPOINT, params=valid_params, headers=headers)
    assert response.status_code == 401
    data = response.json()
    assert data["code"] == 2006
    assert data["message"] == "API key provided is invalid"


# Test: 400 Bad Request
@pytest.mark.parametrize("invalid_param", [
    {"q": None},  # Missing q
    {"days": None},  # Missing days
    {"days": 8},  # Out of valid range (1-7)
    {"dt": "invalid-date"},  # Invalid dt format
    {"q": "invalid-location"},  # Invalid q
])
def test_marine_weather_bad_request(api_headers, valid_params, invalid_param):
    """Tests various cases of 400 Bad Request errors."""
    params = valid_params.copy()
    params.update(invalid_param)

    response = requests.get(BASE_URL + ENDPOINT, params=params, headers=api_headers)
    assert response.status_code == 400
    data = response.json()
    assert "code" in data
    assert "message" in data


# Test: 403 Forbidden
def test_marine_weather_exceeded_quota(api_headers, valid_params):
    """Tests the 403 Forbidden response when API call quota is exceeded."""
    # Mock a scenario where the quota is surpassed
    headers = api_headers.copy()
    headers["key"] = "quota_exceeded_key"  # Replace with an actual quota exceeded key for testing

    response = requests.get(BASE_URL + ENDPOINT, params=valid_params, headers=headers)
    assert response.status_code == 403
    data = response.json()
    assert data["code"] == 2007
    assert data["message"] == "API key has exceeded calls per month quota."


# Test: Parameter edge cases
@pytest.mark.parametrize("param_combinations", [
    {"q": "0.0000,0.0000"},  # Valid minimum lat/lon
    {"days": 1},  # Minimum days
    {"days": 7},  # Maximum days
    {"unixdt": 1490227200},  # Valid unix timestamp
])
def test_marine_weather_edge_cases(api_headers, valid_params, param_combinations):
    """Tests edge case combinations for parameters."""
    params = valid_params.copy()
    params.update(param_combinations)

    response = requests.get(BASE_URL + ENDPOINT, params=params, headers=api_headers)
    assert response.status_code == 200
    data = response.json()
    assert "forecast" in data
    assert "forecastday" in data["forecast"]


# Test: 500 Internal Server Error (mocking or environment-specific)
def test_marine_weather_internal_error(mocker, valid_params, api_headers):
    """Tests the case where the API returns a 500 Internal Server Error."""
    mocker.patch("requests.get", side_effect=Exception("Internal Server Error"))

    with pytest.raises(Exception, match="Internal Server Error"):
        requests.get(BASE_URL + ENDPOINT, params=valid_params, headers=api_headers)
