# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /marine.json_get for http method type GET 
# RoostTestHash=4a44035781
# 
# 

# ********RoostGPT********
import pytest
import requests

# Base URL Configuration
BASE_URL = "https://api.weatherapi.com/v1/marine.json"
API_KEY = "your_api_key_here"  # Replace with your API key

# Fixtures for test data setup
@pytest.fixture
def base_params():
    return {
        "q": "40.7128,-74.0060",
        "days": 5
    }

@pytest.fixture
def invalid_params():
    return {
        "q": "",
        "days": 10
    }

@pytest.fixture
def headers():
    return {
        "key": API_KEY
    }

# Test for security schema cases
@pytest.mark.parametrize("header,expected_status", [
    ({"key": "valid_api_key"}, 200),
    ({"key": "invalid_api_key"}, 401),
    ({}, 401),
])
def test_security_schema(header, expected_status, base_params):
    response = requests.get(BASE_URL, headers=header, params=base_params)
    assert response.status_code == expected_status

# Tests for valid cases
def test_valid_request(base_params, headers):
    response = requests.get(BASE_URL, headers=headers, params=base_params)
    assert response.status_code == 200
    response_json = response.json()

    # Validate response schema
    assert "location" in response_json
    assert "forecast" in response_json
    assert "name" in response_json["location"]
    assert "forecastday" in response_json["forecast"]

def test_optional_params(base_params, headers):
    params = {**base_params, "hour": 17, "lang": "es"}
    response = requests.get(BASE_URL, headers=headers, params=params)
    assert response.status_code == 200

# Tests for error scenarios
@pytest.mark.parametrize("params,expected_code", [
    ({"days": None}, 1003),
    ({"q": "invalid_location"}, 1006),
])
def test_client_errors(params, expected_code, headers):
    response = requests.get(BASE_URL, headers=headers, params=params)
    assert response.status_code == 400
    response_json = response.json()
    assert response_json["code"] == expected_code

def test_api_key_error(invalid_params):
    response = requests.get(BASE_URL, params=invalid_params)
    assert response.status_code == 401

def test_access_denied_error(base_params):
    headers = {"key": "disabled_api_key"}
    response = requests.get(BASE_URL, headers=headers, params=base_params)
    assert response.status_code == 403

# Test boundary conditions
@pytest.mark.parametrize("days,expected_status", [
    (1, 200),
    (7, 200),
    (8, 400),  # Beyond limit
    (0, 400),  # Below limit
])
def test_days_param_boundary(days, expected_status, headers):
    params = {"q": "40.7128,-74.0060", "days": days}
    response = requests.get(BASE_URL, headers=headers, params=params)
    assert response.status_code == expected_status

# Schema validation utility function
def validate_schema(response_json):
    assert "location" in response_json
    assert "forecast" in response_json
    assert "name" in response_json["location"]
    assert "forecastday" in response_json["forecast"]

# Instructions for running tests
"""
1. Install the pytest and requests libraries using pip:
   pip install pytest requests

2. Add your valid API key to the `API_KEY` variable.

3. Run the tests using pytest:
   pytest -v test_marine_api.py
"""

# Test configurations in JSON file
"""
{
  "base_url": "https://api.weatherapi.com/v1/marine.json",
  "api_key": "your_api_key_here",
  "valid_params": {
    "q": "40.7128,-74.0060",
    "days": 5
  },
  "invalid_params": {
    "q": "",
    "days": 10
  },
  "headers": {
    "key": "your_api_key_here"
  }
}
"""
