# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=977dd819cb
# 
# 

# ********RoostGPT********
# nobel_prize_api_tests.py

import pytest
import requests

# Base URL for the API
BASE_URL = "https://api.nobelprizes.org/2.1/nobelPrizes"


@pytest.fixture
def base_url():
    """Fixture for base API URL."""
    return BASE_URL


@pytest.fixture
def sample_valid_params():
    """Fixture for sample valid parameters."""
    return {
        "offset": 0,
        "limit": 10,
        "nobelPrizeYear": 2020,
        "nobelPrizeCategory": "phy",
    }


@pytest.mark.parametrize(
    "params, expected_status_code",
    [
        (None, 200),
        ({"offset": 10}, 200),
        ({"limit": 5}, 200),
        ({"offset": -1}, 400),  # Invalid parameter
        ({"limit": 0}, 400),    # Invalid parameter
        ({"nobelPrizeYear": 1899}, 400),  # Below minimum year
        ({"nobelPrizeYear": 2020, "yearTo": 2025}, 400),  # Missing required combination
        ({"nobelPrizeCategory": "unknown"}, 422),  # Invalid category
    ],
)
def test_nobel_prizes_status_code(base_url, params, expected_status_code):
    """Test various scenarios for status codes."""
    response = requests.get(base_url, params=params)
    assert response.status_code == expected_status_code


def test_valid_response_structure(base_url, sample_valid_params):
    """Test response structure with valid parameters."""
    response = requests.get(base_url, params=sample_valid_params)
    assert response.status_code == 200
    
    # Validate response structure
    response_data = response.json()
    assert "nobelPrizes" in response_data
    assert isinstance(response_data["nobelPrizes"], list)
    assert "meta" in response_data
    assert isinstance(response_data["meta"], dict)


@pytest.mark.parametrize("nobel_prize_year, expected_status_code", 
                         [(2020, 200), (1900, 400), ("invalid_year", 400)])
def test_nobel_prizes_year_filter(base_url, nobel_prize_year, expected_status_code):
    """Test filtering by prize year."""
    params = {"nobelPrizeYear": nobel_prize_year}
    response = requests.get(base_url, params=params)
    assert response.status_code == expected_status_code


def test_authentication_required(base_url):
    """Test behavior for missing authentication (if applicable)."""
    headers = {}
    response = requests.get(base_url, headers=headers)
    assert response.status_code in [401, 403]  # Example if authentication required


def test_error_message_for_invalid_year(base_url):
    """Verify error message for an invalid year."""
    params = {"nobelPrizeYear": 1800}
    response = requests.get(base_url, params=params)
    assert response.status_code == 400
    response_data = response.json()
    assert "code" in response_data
    assert "message" in response_data


def test_pagination(base_url):
    """Test the offset and limit for pagination."""
    params = {"offset": 0, "limit": 2}
    response = requests.get(base_url, params=params)
    assert response.status_code == 200

    data = response.json()
    assert "meta" in data
    assert data["meta"].get("limit") == 2


def test_invalid_parameters(base_url):
    """Test handling of invalid parameters."""
    params = {"limit": "string_value"}
    response = requests.get(base_url, params=params)
    assert response.status_code == 400


def test_no_results_found(base_url):
    """Test case where no results are returned."""
    params = {"nobelPrizeYear": 1800, "nobelPrizeCategory": "xyz"}
    response = requests.get(base_url, params=params)
    assert response.status_code in [400, 404]


@pytest.mark.parametrize(
    "query_params, mandatory_fields",
    [
        ({"nobelPrizeYear": 2020}, ["awardYear", "category"]),
        ({"nobelPrizeCategory": "eco"}, ["dateAwarded", "prizeAmount"]),
    ],
)
def test_response_fields(base_url, query_params, mandatory_fields):
    """Ensure required fields exist in the response."""
    response = requests.get(base_url, params=query_params)
    assert response.status_code == 200

    for prize in response.json().get("nobelPrizes", []):
        for field in mandatory_fields:
            assert field in prize


# Instructions for execution
"""
To execute these tests:
1. Install pytest and requests: `pip install pytest requests`
2. Save this script as `test_nobel_prize_api.py`.
3. Run tests: `pytest test_nobel_prize_api.py -v`.
"""
