# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
import pytest
import requests

BASE_URL = "http://example.com/api/2.1/nobelPrize"
VALID_CATEGORY = "physics"
VALID_YEAR = 2021
INVALID_CATEGORY = "invalidCategory"
INVALID_YEAR = 1800

@pytest.fixture
def api_url():
    return BASE_URL

@pytest.fixture
def valid_category():
    return VALID_CATEGORY

@pytest.fixture
def valid_year():
    return VALID_YEAR

@pytest.fixture
def invalid_category():
    return INVALID_CATEGORY

@pytest.fixture
def invalid_year():
    return INVALID_YEAR

# Test Suite for Nobel Prize API
class TestNobelPrizeAPI:

    @pytest.mark.parametrize("category,year,status_code", [
        (VALID_CATEGORY, VALID_YEAR, 200),   # Valid Request
        (VALID_CATEGORY, INVALID_YEAR, 422), # Invalid Year (Boundary Error)
        (INVALID_CATEGORY, VALID_YEAR, 404), # Invalid Category
        (None, VALID_YEAR, 400),             # Missing Category
        (VALID_CATEGORY, None, 400)          # Missing Year
    ])
    def test_request_status_codes(self, api_url, category, year, status_code):
        """Test endpoint response codes for various scenarios."""
        url = f"{api_url}/{category or ''}/{year or ''}"
        response = requests.get(url)
        assert response.status_code == status_code

    def test_successful_response_schema(self, api_url, valid_category, valid_year):
        """Validate API response schema for successful requests."""
        url = f"{api_url}/{valid_category}/{valid_year}"
        response = requests.get(url)
        assert response.status_code == 200
        
        # Verify response schema
        response_json = response.json()
        assert "nobelPrize" in response_json
        assert isinstance(response_json["nobelPrize"], dict)
        assert "awardYear" in response_json["nobelPrize"]
        assert response_json["nobelPrize"]["awardYear"] == valid_year

    def test_bad_request(self, api_url):
        """Test response for malformed requests."""
        url = f"{api_url}/invalidCategory/"
        response = requests.get(url)
        assert response.status_code == 400

        response_json = response.json()
        assert "code" in response_json
        assert "message" in response_json

    def test_resource_not_found(self, api_url, invalid_category, valid_year):
        """Test response for resource not found."""
        url = f"{api_url}/{invalid_category}/{valid_year}"
        response = requests.get(url)
        assert response.status_code == 404

        response_json = response.json()
        assert "code" in response_json
        assert "message" in response_json

    def test_unprocessable_entity(self, api_url, valid_category, invalid_year):
        """Test response for semantic errors like invalid year."""
        url = f"{api_url}/{valid_category}/{invalid_year}"
        response = requests.get(url)
        assert response.status_code == 422

        response_json = response.json()
        assert "code" in response_json
        assert "message" in response_json
