# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=977dd819cb
# 
# 

# ********RoostGPT********
import pytest
import requests

BASE_URL = "http://example.com/2.1/nobelPrizes"

@pytest.fixture(scope="module")
def base_url():
    """Fixture to define the base URL for the API."""
    return BASE_URL

@pytest.fixture
def default_params():
    """Fixture to define default query params."""
    return {
        "nobelPrizeYear": 2022,
        "nobelPrizeCategory": "eco",
        "format": "json"
    }

def is_valid_response(response, status_code):
    """Helper to validate HTTP status and JSON response content."""
    assert response.status_code == status_code
    assert response.headers["Content-Type"] == "application/json"
    return response.json()

@pytest.mark.parametrize(
    "query_params, expected_status",
    [
        (None, 200),  # Default response
        ({"limit": 10}, 200),  # Valid offset and limit
        ({"limit": -10}, 400),  # Invalid limit
        ({"nobelPrizeYear": 1800}, 422),  # Invalid year outside range
    ]
)
def test_fetch_nobel_prizes(base_url, query_params, expected_status):
    """Test fetching Nobel Prizes for various query parameter combinations."""
    response = requests.get(base_url, params=query_params)
    data = is_valid_response(response, expected_status)
    
    if response.status_code == 200:
        assert "nobelPrizes" in data
        assert isinstance(data["nobelPrizes"], list)
    elif response.status_code in (400, 422):
        assert "code" in data
        assert "message" in data

def test_pagination(base_url):
    """Test pagination with offset and limit."""
    params = {"offset": 5, "limit": 10}
    response = requests.get(base_url, params=params)
    data = is_valid_response(response, 200)

    assert "meta" in data
    assert "offset" in data["meta"]
    assert "limit" in data["meta"]

@pytest.mark.parametrize(
    "category, expected_status",
    [
        ("eco", 200),  # Valid category
        ("invalid_category", 422),  # Invalid category
    ]
)
def test_filter_by_category(base_url, category, expected_status):
    """Test filtering by Nobel Prize category."""
    params = {"nobelPrizeCategory": category}
    response = requests.get(base_url, params=params)
    data = is_valid_response(response, expected_status)
    
    if response.status_code == 200:
        for prize in data["nobelPrizes"]:
            assert prize["category"]["en"] == category

def test_response_schema(base_url, default_params):
    """Test to validate the response schema for the endpoint."""
    response = requests.get(base_url, params=default_params)
    data = is_valid_response(response, 200)
    
    for prize in data["nobelPrizes"]:
        assert "awardYear" in prize
        assert "category" in prize
        assert "laureates" in prize

@pytest.mark.parametrize(
    "field, expected_status",
    [
        ("nobelPrizeYear", 422),  # Missing yearTo with year
        ("limit", 400),  # Invalid limit values
    ]
)
def test_invalid_combinations(base_url, field, expected_status):
    """Test API responses for invalid parameter combinations."""
    params = {}
    params[field] = -9999  # Invalid value
    response = requests.get(base_url, params=params)
    is_valid_response(response, expected_status)

@pytest.mark.parametrize(
    "status_code",
    [404, 422]  # Include other error status codes to test
)
def test_error_responses(base_url, status_code):
    """Test handling of errors for invalid requests."""
    invalid_url = f"{base_url}/invalid_endpoint"
    response = requests.get(invalid_url)
    assert response.status_code == status_code
