# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /search.json_get for http method type GET 
# RoostTestHash=72ffe69306
# 
# 

# ********RoostGPT********
import pytest
import requests

BASE_URL = "https://api.weatherapi.com/v1"
API_KEY = "your_api_key_here"

@pytest.fixture
def headers():
    """Fixture to set headers for the API request."""
    return {
        "Content-Type": "application/json",
        "key": API_KEY
    }

@pytest.mark.parametrize(
    "query, expected_status",
    [
        ("London", 200),  # Valid city name
        ("", 400),        # Missing query parameter
        (None, 400)       # Null parameter
    ]
)
def test_search_autocomplete_valid_query(headers, query, expected_status):
    """
    Test the search/autocomplete endpoint with valid, empty, and null 'q' parameters.
    """
    params = {"q": query} if query is not None else {}
    response = requests.get(f"{BASE_URL}/search.json", headers=headers, params=params)
    assert response.status_code == expected_status

    if expected_status == 200:
        data = response.json()
        assert isinstance(data, list)
        for item in data:  # Validate schema of response body
            assert "id" in item
            assert "name" in item
            assert "region" in item
            assert "country" in item
            assert "lat" in item
            assert "lon" in item
            assert "url" in item
    elif expected_status == 400:
        data = response.json()
        assert "code" in data
        assert "message" in data

def test_missing_api_key():
    """Test the API with missing API key."""
    response = requests.get(f"{BASE_URL}/search.json")
    assert response.status_code == 401
    data = response.json()
    assert data["code"] == 1002
    assert data["message"] == "API key not provided"

def test_invalid_api_key():
    """Test the API with an invalid API key."""
    headers = {"Content-Type": "application/json", "key": "invalid_key"}
    response = requests.get(f"{BASE_URL}/search.json", headers=headers, params={"q": "London"})
    assert response.status_code == 401
    data = response.json()
    assert data["code"] == 2006
    assert data["message"] == "API key provided is invalid"

def test_exceeded_api_quota():
    """Simulate exceeding API quota (403 response)."""
    headers = {"Content-Type": "application/json", "key": "quota_exceeded_key"}
    response = requests.get(f"{BASE_URL}/search.json", headers=headers, params={"q": "London"})
    assert response.status_code == 403
    data = response.json()
    assert "code" in data
    assert data["message"] == "API key has exceeded calls per month quota."

def test_invalid_query_parameter(headers):
    """Test the endpoint with an invalid query parameter."""
    response = requests.get(f"{BASE_URL}/search.json", headers=headers, params={"q": "Non-existent-location"})
    assert response.status_code == 400
    data = response.json()
    assert data["code"] == 1006
    assert data["message"] == "No location found matching parameter 'q'"

def test_json_bulk_invalid(headers):
    """
    Test the API response when the request is invalid JSON or contains too many locations.
    """
    params = {"q": "[{'invalid':'json'}"}  # Passing malformed JSON as a string for testing purpose
    response = requests.get(f"{BASE_URL}/search.json", headers=headers, params=params)
    assert response.status_code == 400
    data = response.json()
    assert "code" in data
    assert data["message"] == "Json body passed in bulk request is invalid. Please make sure it is valid json with utf-8 encoding."
