# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /search.json_get for http method type GET 
# RoostTestHash=72ffe69306
# 
# 

# ********RoostGPT********
import pytest
import requests

# ---------------------------
# Configuration
# ---------------------------

BASE_URL = "https://api.weatherapi.com"
API_KEY = "your_api_key_here"

@pytest.fixture
def headers():
    """Fixture for headers including API key."""
    return {"key": API_KEY}

# ---------------------------
# Test Data
# ---------------------------

VALID_QUERY = {"q": "London"}
INVALID_QUERY = {"q": ""}
INVALID_API_KEY = {"key": "invalid_api_key"}

# ---------------------------
# Tests
# ---------------------------

def test_search_valid_query(headers):
    """Test search with a valid query."""
    response = requests.get(f"{BASE_URL}/v1/search.json", headers=headers, params=VALID_QUERY)
    assert response.status_code == 200
    assert isinstance(response.json(), list)
    assert all("id" in obj and "name" in obj for obj in response.json())

def test_search_invalid_query(headers):
    """Test search with an invalid query."""
    response = requests.get(f"{BASE_URL}/v1/search.json", headers=headers, params=INVALID_QUERY)
    assert response.status_code == 400
    assert response.json()["code"] == 1003
    assert response.json()["message"] == "Parameter 'q' not provided."

def test_missing_auth():
    """Test API response when no API key is provided."""
    response = requests.get(f"{BASE_URL}/v1/search.json", params=VALID_QUERY)
    assert response.status_code == 401
    assert response.json()["code"] == 1002
    assert response.json()["message"] == "API key not provided"

def test_invalid_auth():
    """Test API response when an invalid API key is provided."""
    headers = {"key": INVALID_API_KEY["key"]}
    response = requests.get(f"{BASE_URL}/v1/search.json", headers=headers, params=VALID_QUERY)
    assert response.status_code == 401
    assert response.json()["code"] == 2006
    assert response.json()["message"] == "API key provided is invalid"

def test_rate_limit_exceeded(headers):
    """Mock/Test API key rate limit exceeded scenario."""
    # Assuming this response is simulated/mock.
    response = {
        "code": 2007,
        "message": "API key has exceeded calls per month quota."
    }
    assert response["code"] == 2007
    assert "exceeded calls per month quota" in response["message"]

@pytest.mark.parametrize("invalid_key", ["", "random_key", None])
def test_authentication_required_invalid_key(invalid_key):
    """Parameterized test: API authorization for multiple invalid keys."""
    headers = {"key": invalid_key}
    response = requests.get(f"{BASE_URL}/v1/search.json", headers=headers, params=VALID_QUERY)
    assert response.status_code == 401
    assert "API key" in response.json()["message"]

