# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /timezone.json_get for http method type GET 
# RoostTestHash=df6b1e5ce9
# 
# 

# ********RoostGPT********
# test_time_zone_api.py
import pytest
import requests

# Configuration for base URLs, API keys, and test data
BASE_URL = "https://api.weatherapi.com/v1"
API_KEY = "your_api_key_here"

@pytest.fixture
def headers():
    """Fixture to provide request headers with API key authentication."""
    return {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {API_KEY}"
    }

@pytest.fixture
def base_url():
    """Fixture to provide the base URL."""
    return BASE_URL

@pytest.mark.parametrize("query", [
    "New York",                  # Valid city
    "90210",                     # Valid US Zipcode
    "SW1A1AA",                   # Valid UK Postcode
    "8.8.8.8",                   # Valid IP address
    "40.71,-74.01",              # Valid Latitude/Longitude
])
def test_timezone_api_success(base_url, headers, query):
    """
    Test the /timezone endpoint with valid queries.
    """
    response = requests.get(
        f"{base_url}/timezone.json",
        headers=headers,
        params={"q": query}
    )
    assert response.status_code == 200, f"Unexpected status code {response.status_code}"
    data = response.json()
    assert "name" in data, "Response does not contain 'name'"
    assert "region" in data, "Response does not contain 'region'"
    assert "country" in data, "Response does not contain 'country'"
    assert isinstance(data.get("lat"), float), "Latitude is not a valid float"
    assert isinstance(data.get("lon"), float), "Longitude is not a valid float"
    assert "tz_id" in data, "Response does not contain 'tz_id'"
    assert "localtime" in data, "Response does not contain 'localtime'"


@pytest.mark.parametrize("query", [
    "",              # Missing query
    "NonExisting",   # Invalid city
    "99999",         # Invalid postal code
])
def test_timezone_api_client_errors(base_url, headers, query):
    """
    Test the /timezone endpoint for 400-level errors.
    """
    response = requests.get(
        f"{base_url}/timezone.json",
        headers=headers,
        params={"q": query}
    )
    assert response.status_code == 400, f"Unexpected status code {response.status_code}"
    data = response.json()
    assert "code" in data and "message" in data, "Response does not contain error 'code' or 'message'"
    assert data['code'] in [1003, 1005, 1006, 9000, 9001, 9999], "Unexpected error code"
    assert isinstance(data['message'], str), "Error message is not a string"


@pytest.mark.parametrize("api_key", [
    None,                         # Missing API key
    "invalid_api_key",            # Invalid API key
])
def test_timezone_api_auth_errors(base_url, api_key):
    """
    Test the /timezone endpoint for authentication errors (401).
    """
    headers = {
        "Content-Type": "application/json",
    }
    if api_key is not None:
        headers["Authorization"] = f"Bearer {api_key}"

    response = requests.get(
        f"{base_url}/timezone.json",
        headers=headers,
        params={"q": "New York"}
    )
    assert response.status_code == 401, f"Unexpected status code {response.status_code}"
    data = response.json()
    assert "code" in data and "message" in data, "Response does not contain error 'code' or 'message'"
    assert data['code'] in [1002, 2006], "Unexpected error code"
    assert isinstance(data['message'], str), "Error message is not a string"


def test_timezone_api_rate_limit_errors(base_url, headers):
    """
    Test the /timezone endpoint for rate limit and quota errors (403).
    """
    # Simulate rate limit by making excessive calls if possible
    response = requests.get(
        f"{base_url}/timezone.json",
        headers=headers,
        params={"q": "New York"}
    )
    assert response.status_code in [403, 200], f"Unexpected status code {response.status_code}"

    if response.status_code == 403:
        data = response.json()
        assert "code" in data and "message" in data, "Response does not contain error 'code' or 'message'"
        assert data['code'] in [2007, 2008, 2009], "Unexpected error code"
        assert isinstance(data['message'], str), "Error message is not a string"
