# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/findByStatus_get for http method type GET 
# RoostTestHash=467fc95f1c
# 
# 

# ********RoostGPT********
import pytest
import requests
from urllib.parse import urlencode

# Load configurations from config.yaml
import yaml


# Load configuration
def load_config():
    with open("config.yaml", "r") as file:
        return yaml.safe_load(file)


CONFIG = load_config()

API_HOST = CONFIG["api"]["host"]
AUTH_API_KEY = CONFIG["authentication"]["api_key"]


# Pytest fixtures
@pytest.fixture
def api_key_header():
    """Fixture for API Key Authentication header"""
    return {"api_key": AUTH_API_KEY}


@pytest.fixture
def endpoint_url():
    """Fixture for building base endpoint URL"""
    return f"{API_HOST}/pet/findByStatus"


@pytest.fixture
def valid_status():
    """Fixture for valid status"""
    return ["available", "pending", "sold"]


@pytest.fixture
def invalid_status():
    """Fixture for invalid status"""
    return ["nonexistent_status"]


# Test Functions
@pytest.mark.parametrize(
    "status_values",
    [
        (["available"]),
        (["pending"]),
        (["sold"]),
        (["available", "pending"]),
        (["pending", "sold"]),
        (["available", "pending", "sold"]),
    ],
)
def test_find_by_status_success(api_key_header, endpoint_url, status_values):
    """
    Test the 'Find Pets by Status' endpoint with valid statuses.
    """
    headers = api_key_header
    params = {"status": status_values}
    response = requests.get(
        endpoint_url, headers=headers, params=params
    )
    assert response.status_code == 200, f"Unexpected status code {response.status_code}"
    assert isinstance(response.json(), list), "Response should be a list"
    for pet in response.json():
        assert "id" in pet, "Each pet should have an ID"
        assert "name" in pet, "Each pet should have a name"
        assert "photoUrls" in pet, "Each pet should have photo URLs"


def test_find_by_status_invalid_status(api_key_header, endpoint_url, invalid_status):
    """
    Test the 'Find Pets by Status' endpoint with invalid status.
    """
    headers = api_key_header
    params = {"status": invalid_status}
    response = requests.get(
        endpoint_url, headers=headers, params=params
    )
    assert response.status_code == 400, f"Unexpected status code {response.status_code}"


def test_find_by_status_no_auth(endpoint_url, valid_status):
    """
    Test the 'Find Pets by Status' endpoint without authentication.
    """
    params = {"status": valid_status}
    response = requests.get(endpoint_url, params=params)
    assert response.status_code == 403, f"Unexpected status code {response.status_code}"


@pytest.mark.parametrize(
    "status_values",
    [
        ([]),  # Empty status values
        (None),  # Missing status values
    ],
)
def test_find_by_status_invalid_parameters(api_key_header, endpoint_url, status_values):
    """
    Test the 'Find Pets by Status' endpoint with invalid parameters.
    """
    headers = api_key_header
    params = {"status": status_values} if status_values is not None else {}
    response = requests.get(
        endpoint_url, headers=headers, params=params
    )
    assert response.status_code == 400, f"Unexpected status code {response.status_code}"


# Instructions for running tests
# 1. Ensure pytest and PyYAML are installed (`pip install pytest pyyaml`).
# 2. Place the config.yaml file in the same directory as the test script.
# 3. Run tests with the command: `pytest -v <test_script_name>.py`
