# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=01adc2ed1e
# 
# 

# ********RoostGPT********
# test_pet_by_tags.py

import pytest
import requests
from urllib.parse import urlencode

# Load configuration from config.yml
import yaml

with open("config.yml", "r") as file:
    config = yaml.safe_load(file)

BASE_URL = config["api"]["host"]
API_KEY = config["authentication"]["api_key"]
HEADERS = {"Authorization": f"Bearer {API_KEY}"}

# Fixtures
@pytest.fixture
def api_base_url():
    """Fixture to get base API URL."""
    return BASE_URL

@pytest.fixture
def valid_tags():
    """Fixture with valid tags."""
    return ["pet"]

@pytest.fixture
def invalid_tags():
    """Fixture with invalid tags."""
    return ["@@@invalid$$$"]

# Test Functions
@pytest.mark.parametrize(
    "tags, expected_status_code",
    [
        (["pet"], 200),           # Valid tags
        ([], 400),                # Missing required parameter
        (None, 400),              # No tags (should fail with 400)
        (["nonexistent"], 200),   # Valid but no matching data
    ],
)
def test_find_by_tags(api_base_url, tags, expected_status_code):
    """
    Test the /v2/pet/findByTags endpoint with various tag combinations.
    """
    url = f"{api_base_url}/pet/findByTags"
    params = {"tags": tags}

    if tags is None:
        response = requests.get(url, headers=HEADERS)
    else:
        response = requests.get(url, headers=HEADERS, params=params)

    assert response.status_code == expected_status_code

    if expected_status_code == 200:
        # Validate response is an array
        response_data = response.json()
        assert isinstance(response_data, list)

        # Validate each entry in array
        for pet in response_data:
            assert "name" in pet
            assert "photoUrls" in pet
            assert isinstance(pet["photoUrls"], list)
            assert isinstance(pet["name"], str)


def test_security_missing_token(api_base_url, valid_tags):
    """
    Test the endpoint without providing the authentication token.
    """
    url = f"{api_base_url}/pet/findByTags"
    params = {"tags": valid_tags}
    response = requests.get(url, params=params)

    # Expect unauthorized error due to missing token
    assert response.status_code == 401


def test_security_invalid_token(api_base_url, valid_tags):
    """
    Test the endpoint with an invalid authentication token.
    """
    url = f"{api_base_url}/pet/findByTags"
    headers = {"Authorization": "Bearer invalid-token"}
    params = {"tags": valid_tags}
    response = requests.get(url, headers=headers, params=params)

    # Expect unauthorized error due to invalid token
    assert response.status_code == 401


def test_invalid_tag_value(api_base_url, invalid_tags):
    """
    Test the endpoint with invalid tag values.
    """
    url = f"{api_base_url}/pet/findByTags"
    params = {"tags": invalid_tags}
    response = requests.get(url, headers=HEADERS, params=params)

    # Expect HTTP 400 for invalid tag values
    assert response.status_code == 400


def test_valid_empty_results(api_base_url):
    """
    Test with valid tag but expect no results.
    """
    url = f"{api_base_url}/pet/findByTags"
    params = {"tags": ["nonexistent"]}
    response = requests.get(url, headers=HEADERS, params=params)

    assert response.status_code == 200
    assert response.json() == []


# Test Execution Instructions:
# 1. Save this test file as `test_pet_by_tags.py`.
# 2. Ensure `config.yml` is in the same directory as this test file.
# 3. Install dependencies: `pip install pytest requests pyyaml`.
# 4. Run the tests using the command: `pytest test_pet_by_tags.py`.
