# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/{petId}_get for http method type GET 
# RoostTestHash=018c365850
# 
# 

# ********RoostGPT********
import pytest
import requests
import yaml

# Load configuration data
@pytest.fixture(scope="session")
def config():
    with open("config.yml", "r") as file:
        return yaml.safe_load(file)

# Base URL fixture
@pytest.fixture(scope="session")
def base_url(config):
    return config["api"]["host"]

# Authentication key fixture
@pytest.fixture(scope="session")
def api_key(config):
    return config["authentication"]["api_key"]

# Fixture to manage test data and endpoints
@pytest.fixture(scope="session")
def endpoints(base_url):
    return {
        "get_pet_by_id": f"{base_url}/pet/{{petId}}"
    }

# Test for the GET /v2/pet/{petId} endpoint
@pytest.mark.parametrize("pet_id, expected_status, expected_fields", [
    (1, 200, ["id", "name", "photoUrls"]),
    (-1, 400, None),
    (999999, 404, None)
])
def test_get_pet_by_id(config, endpoints, api_key, pet_id, expected_status, expected_fields):
    """
    Test GET /v2/pet/{petId} endpoint.
    Covers success, client errors, and not found scenarios.
    """
    url = endpoints["get_pet_by_id"].format(petId=pet_id)
    headers = {"api_key": api_key}

    response = requests.get(url, headers=headers)

    assert response.status_code == expected_status, f"Unexpected status code: {response.status_code}"

    if expected_status == 200:
        response_json = response.json()
        # Assert required fields in the response
        for field in expected_fields:
            assert field in response_json, f"Missing field: {field}"

        # Verify schema integrity of specific fields
        assert isinstance(response_json["id"], int), "Expected 'id' to be an integer."
        assert isinstance(response_json["name"], str), "Expected 'name' to be a string."
        assert isinstance(response_json["photoUrls"], list), "Expected 'photoUrls' to be a list."

    elif expected_status in [400, 404]:
        assert "error" in response.text.lower(), "Expected an error message."

def test_get_pet_by_id_authentication_failure(endpoints):
    """
    Test GET /v2/pet/{petId} endpoint with invalid authentication.
    """
    url = endpoints["get_pet_by_id"].format(petId=1)
    headers = {"api_key": "invalid-key"}

    response = requests.get(url, headers=headers)

    assert response.status_code == 403, f"Expected status code 403 for authentication failure; got {response.status_code}"
    assert "unauthorized" in response.text.lower(), "Expected unauthorized error."

# Cleanup or teardown fixture (optional)
@pytest.fixture(scope="function", autouse=True)
def cleanup():
    yield
    # Add cleanup code here if needed for the test environment

# Instructions for running the tests
"""
To execute these tests:
1. Install pytest and requests libraries:
   pip install pytest requests pyyaml
2. Ensure 'config.yml' file exists in the same directory as the test files.
3. Run the tests using:
   pytest -v test_api.py
"""

# Example config.yml file:
"""
api:
  host: https://petstore.swagger.io/v2

authentication:
  api_key: special-key
  petstore_auth: special-key
"""
