# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /store/order/{orderId}_get for http method type GET 
# RoostTestHash=cd8cc54cf7
# 
# 

# ********RoostGPT********
# test_store_order.py

import pytest
import requests
import yaml
from jsonschema import validate

# Load configuration from YAML
@pytest.fixture(scope="module")
def config():
    with open("config.yml", "r") as file:
        return yaml.safe_load(file)

# Base URL Fixture
@pytest.fixture(scope="module")
def base_url(config):
    return config["api"]["host"]

# Authentication API Key Fixture
@pytest.fixture(scope="module")
def headers(config):
    return {"api_key": config["authentication"]["api_key"]}

# Expected Response Schema for 200
order_response_schema = {
    "type": "object",
    "properties": {
        "id": {"type": "integer", "format": "int64"},
        "petId": {"type": "integer", "format": "int64"},
        "quantity": {"type": "integer", "format": "int32"},
        "shipDate": {"type": "string", "format": "date-time"},
        "status": {"type": "string"},
        "complete": {"type": "boolean"},
    },
    "required": ["id", "petId", "quantity", "status", "complete"],
}

# Parameterized tests for /store/order/{orderId}
@pytest.mark.parametrize(
    "order_id, expected_status_code",
    [
        (1, 200),  # Valid order ID within range
        (10, 200), # Valid order ID within range
        (0, 400),  # Invalid ID (less than minimum)
        (11, 400), # Invalid ID (greater than maximum)
        ("abc", 400),  # Non-integer ID
        (9999, 404),  # Non-existent order ID
    ],
)
def test_get_order_by_id(base_url, headers, order_id, expected_status_code):
    """
    Test /store/order/{orderId} endpoint with various cases:
    - Valid IDs
    - Invalid IDs (out of range, non-integer, etc.)
    - Non-existent IDs
    """
    url = f"{base_url}/store/order/{order_id}"
    response = requests.get(url, headers=headers)
    
    # Assert the response status code
    assert response.status_code == expected_status_code

    if response.status_code == 200:
        # Validate JSON response schema
        response_json = response.json()
        validate(instance=response_json, schema=order_response_schema)
    elif response.status_code == 400:
        assert "Invalid ID" in response.json().get("message", "")
    elif response.status_code == 404:
        assert "Order not found" in response.json().get("message", "")

# Test for missing authentication
def test_get_order_by_id_missing_auth(base_url):
    """
    Test /store/order/{orderId} endpoint with missing authentication.
    """
    url = f"{base_url}/store/order/1"
    response = requests.get(url)  # No headers provided
    assert response.status_code == 401  # Unauthorized or similar error

# Test for invalid authentication
def test_get_order_by_id_invalid_auth(base_url):
    """
    Test /store/order/{orderId} endpoint with invalid authentication key.
    """
    url = f"{base_url}/store/order/1"
    headers = {"api_key": "invalid-key"}  # Invalid API key
    response = requests.get(url, headers=headers)
    assert response.status_code == 403  # Forbidden or similar error

# Instructions for running the tests
"""
How to Run:
1. Ensure `pytest` and necessary dependencies (`requests`, `PyYAML`, `jsonschema`) are installed.
2. Save the above code in a file named `test_store_order.py`.
3. Save the provided YAML content in a `config.yml` file in the same directory as the test file.
4. Run tests with the command: `pytest test_store_order.py`
"""
