# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /user/logout_get for http method type GET 
# RoostTestHash=696422fb14
# 
# 

# ********RoostGPT********
# test_user_logout.py

import pytest
import requests
import yaml
from pathlib import Path

# Load configuration from YAML file
CONFIG_PATH = Path(__file__).parent / "config.yml"
with open(CONFIG_PATH, "r") as file:
    config = yaml.safe_load(file)

BASE_URL = config["api"]["host"]
HEADERS = {"Authorization": config["authentication"]["api_key"]}
ENDPOINT = "/user/logout"

@pytest.fixture
def base_url():
    """Fixture to provide base URL for the API."""
    return BASE_URL

@pytest.fixture
def headers():
    """Fixture to provide headers with authentication."""
    return HEADERS

@pytest.fixture
def endpoint():
    """Fixture to provide the logout endpoint."""
    return ENDPOINT

@pytest.mark.smoke
def test_user_logout_success(base_url, headers, endpoint):
    """
    Test case: Successful Logout
    Verifies the logout operation is successful.
    """
    url = f"{base_url}{endpoint}"
    response = requests.get(url, headers=headers)

    assert response.status_code == 200, f"Expected status code 200, got {response.status_code}"
    assert response.text in ["", "{}", "[]"], "Response body should be empty or minimal"

@pytest.mark.security
def test_user_logout_missing_auth(base_url, endpoint):
    """
    Test case: Missing Authentication
    Verifies the API returns appropriate error for missing authentication.
    """
    url = f"{base_url}{endpoint}"
    response = requests.get(url)

    assert response.status_code in [401, 403], f"Expected status code 401 or 403, got {response.status_code}"
    assert "error" in response.text.lower(), "Expected error message in response body"

@pytest.mark.security
def test_user_logout_invalid_auth(base_url, endpoint):
    """
    Test case: Invalid Authentication
    Verifies the API returns appropriate error for invalid authentication.
    """
    url = f"{base_url}{endpoint}"
    headers = {"Authorization": "invalid-key"}
    response = requests.get(url, headers=headers)

    assert response.status_code in [401, 403], f"Expected status code 401 or 403, got {response.status_code}"
    assert "error" in response.text.lower(), "Expected error message in response body"

@pytest.mark.parameterized
@pytest.mark.parametrize("method", ["POST", "PUT", "DELETE", "PATCH", "OPTIONS"])
def test_user_logout_invalid_methods(base_url, endpoint, headers, method):
    """
    Test case: Invalid HTTP Methods
    Verifies that unsupported HTTP methods are rejected by the API.
    """
    url = f"{base_url}{endpoint}"
    response = requests.request(method, url, headers=headers)

    assert response.status_code in [405], f"Expected status code 405, got {response.status_code}"
    assert "error" in response.text.lower(), "Expected error message in response body"
