# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/{petId}_get for http method type GET 
# RoostTestHash=19a7d06811
# 
# 

# ********RoostGPT********
# test_pet_api.py

import pytest
from jsonschema import validate

# Sample request and response payloads for positive and negative cases
valid_pet_id = 10
invalid_pet_id = "abc"
nonexistent_pet_id = 999999

# Expected JSON schema of the successful response
successful_response_schema = {
    "type": "object",
    "properties": {
        "id": {"type": "integer", "format": "int64"},
        "name": {"type": "string"},
        "category": {
            "type": "object",
            "properties": {
                "id": {"type": "integer", "format": "int64"},
                "name": {"type": "string"},
            },
        },
        "photoUrls": {"type": "array", "items": {"type": "string"}},
        "tags": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {"type": "integer", "format": "int64"},
                    "name": {"type": "string"},
                },
            },
        },
        "status": {"type": "string"},
    },
    "required": ["name", "photoUrls"],
}

# Test cases for the /pet/{petId} endpoint
class TestPetApi:

    @pytest.mark.parametrize("auth_type", ["api_key", "oauth2", None])
    def test_get_pet_by_id_success(
        self, api_client, valid_api_key, oauth2_token, auth_type
    ):
        """
        Test /pet/{petId} endpoint for a successful operation (200).
        Auth is parameterized for api_key, OAuth2, and no auth for verification.
        """
        headers = {}
        # Add headers based on the authentication type
        if auth_type == "api_key":
            headers = {"api_key": valid_api_key}
        elif auth_type == "oauth2":
            headers = {"Authorization": f"Bearer {oauth2_token}"}

        response = api_client.get(f"/pet/{valid_pet_id}", headers=headers)

        assert response.status_code == 200, "Expected HTTP 200 status code"
        validate(instance=response.json(), schema=successful_response_schema)

    def test_get_pet_by_id_invalid_auth(self, api_client, invalid_api_key):
        """
        Test /pet/{petId} endpoint when authentication is invalid.
        """
        headers = {"api_key": invalid_api_key}
        response = api_client.get(f"/pet/{valid_pet_id}", headers=headers)

        assert response.status_code in [401, 403], "Expected HTTP 401 or 403 status code"

    def test_get_pet_by_id_invalid_pet_id(self, api_client, valid_api_key):
        """
        Test /pet/{petId} endpoint with an invalid pet ID format (400).
        """
        headers = {"api_key": valid_api_key}
        response = api_client.get(f"/pet/{invalid_pet_id}", headers=headers)

        assert response.status_code == 400, "Expected HTTP 400 status code"
        assert "Invalid ID supplied" in response.text

    def test_get_pet_by_id_nonexistent_pet(self, api_client, valid_api_key):
        """
        Test /pet/{petId} endpoint with a non-existent pet ID (404).
        """
        headers = {"api_key": valid_api_key}
        response = api_client.get(f"/pet/{nonexistent_pet_id}", headers=headers)

        assert response.status_code == 404, "Expected HTTP 404 status code"
        assert "Pet not found" in response.text

    def test_get_pet_by_id_missing_auth(self, api_client):
        """
        Test /pet/{petId} endpoint without providing any authentication.
        """
        response = api_client.get(f"/pet/{valid_pet_id}")

        assert response.status_code in [401, 403], "Expected HTTP 401 or 403 status code"

