# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=288991d4ff
# 
# 

# ********RoostGPT********
import pytest
from jsonschema import validate

# Test cases for the /pet/findByTags endpoint
@pytest.mark.parametrize(
    "tags, expected_status, valid_auth",
    [
        (["dog", "cat"], 200, True),  # Valid tags, successful operation
        (["not-a-tag"], 400, True),  # Invalid tags, invalid tag value error
        (None, 200, True),  # No tags, successful operation
        (["dog"], 401, False),  # Missing or invalid authentication
    ],
)
def test_find_pets_by_tags(api_client, valid_api_key, invalid_api_key, oauth2_token, tags, expected_status, valid_auth):
    """
    Test the /pet/findByTags endpoint with various scenarios.
    """
    # Configure headers with valid/invalid authentication
    if valid_auth:
        headers = {"Authorization": f"Bearer {oauth2_token}"}
    else:
        headers = {"Authorization": f"Bearer {invalid_api_key}"}

    # Build parameters
    params = {"tags": tags} if tags else {}

    # Make API request
    response = api_client.get(endpoint="/pet/findByTags", headers=headers, params=params)

    # Assert the response status code
    assert response.status_code == expected_status

    # Validate against the OpenAPI JSON schema for successful operation (status 200)
    if expected_status == 200:
        response_json = response.json()
        schema = {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["name", "photoUrls"],
                "properties": {
                    "id": {"type": "integer", "format": "int64"},
                    "name": {"type": "string"},
                    "category": {
                        "type": "object",
                        "properties": {
                            "id": {"type": "integer", "format": "int64"},
                            "name": {"type": "string"},
                        },
                    },
                    "photoUrls": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                    "tags": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {"type": "integer", "format": "int64"},
                                "name": {"type": "string"},
                            },
                        },
                    },
                    "status": {"type": "string"},
                },
            },
        }
        validate(instance=response_json, schema=schema)

    # Assert for the 400 Invalid Tag Value
    if expected_status == 400:
        assert "Invalid tag value" in response.text

    # Assert for the 401 Unauthorized error
    if expected_status == 401:
        assert "Unauthorized" in response.text
