# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /store/order/{orderId}_get for http method type GET 
# RoostTestHash=02b15e7ca7
# 
# 

# ********RoostGPT********
import pytest
import requests
import yaml
from jsonschema import validate

# Load configuration data
@pytest.fixture(scope="session")
def load_config():
    with open("config.yml", "r") as file:
        return yaml.safe_load(file)

# Define API base URL and authentication
@pytest.fixture(scope="session")
def api_base_url(load_config):
    return load_config["api"]["host"]

@pytest.fixture(scope="session")
def headers(load_config):
    return {
        "Authorization": f"Bearer {load_config['authentication']['petstore_auth']}",
        "api_key": load_config["authentication"]["api_key"]
    }

# Request payload factories
@pytest.fixture
def request_data():
    return {
        "valid_order_id": 3,  # Valid ID (<=5 or >10)
        "invalid_order_id": "abc",  # Non-integer value
        "non_existing_order_id": 99999,  # ID that doesn't exist
        "boundary_order_id": 5,  # Boundary case
    }

# Response schema for validation
@pytest.fixture
def response_schema():
    return {
        "type": "object",
        "properties": {
            "id": {"type": "integer", "format": "int64"},
            "petId": {"type": "integer", "format": "int64"},
            "quantity": {"type": "integer", "format": "int32"},
            "shipDate": {"type": "string", "format": "date-time"},
            "status": {"type": "string"},
            "complete": {"type": "boolean"}
        },
        "required": ["id", "petId", "quantity", "shipDate", "status", "complete"]
    }

# Test cases for "/store/order/{orderId}" endpoint
class TestStoreOrder:
    endpoint = "/store/order/{orderId}"

    def test_get_order_by_valid_id(self, api_base_url, headers, request_data, response_schema):
        """
        Test fetching an order with a valid ID.
        Expected: 200 OK, response matches schema.
        """
        url = api_base_url + self.endpoint.format(orderId=request_data["valid_order_id"])
        response = requests.get(url, headers=headers)

        assert response.status_code == 200
        response_json = response.json()
        validate(instance=response_json, schema=response_schema)

    def test_get_order_by_invalid_id(self, api_base_url, headers, request_data):
        """
        Test fetching an order with an invalid ID (non-integer).
        Expected: 400 Bad Request.
        """
        url = api_base_url + self.endpoint.format(orderId=request_data["invalid_order_id"])
        response = requests.get(url, headers=headers)

        assert response.status_code == 400
        assert "Invalid ID supplied" in response.text

    def test_get_non_existing_order_id(self, api_base_url, headers, request_data):
        """
        Test fetching an order with an ID that doesn't exist.
        Expected: 404 Not Found.
        """
        url = api_base_url + self.endpoint.format(orderId=request_data["non_existing_order_id"])
        response = requests.get(url, headers=headers)

        assert response.status_code == 404
        assert "Order not found" in response.text

    def test_get_order_by_boundary_id(self, api_base_url, headers, request_data, response_schema):
        """
        Test fetching an order on the boundary of valid ID (e.g., 5).
        Expected: 200 OK, response matches schema.
        """
        url = api_base_url + self.endpoint.format(orderId=request_data["boundary_order_id"])
        response = requests.get(url, headers=headers)

        assert response.status_code == 200
        response_json = response.json()
        validate(instance=response_json, schema=response_schema)

    def test_get_order_missing_auth(self, api_base_url, request_data):
        """
        Test fetching an order with missing authentication headers.
        Expected: 401 Unauthorized.
        """
        url = api_base_url + self.endpoint.format(orderId=request_data["valid_order_id"])
        response = requests.get(url)

        assert response.status_code == 401
        assert "Unauthorized" in response.text

# Sample YAML configuration file content
"""
api:
  host: https://petstore3.swagger.io/api/v3/

authentication:
  petstore_auth: sampletoken
  api_key: sampleapikey
"""

# Instructions for running the tests:
# 1. Place the test file and config.yml in the same directory.
# 2. Install dependencies: `pip install requests pytest pyyaml jsonschema`.
# 3. Run the tests: `pytest test_api.py`.
