# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /store/order/{orderId}_get for http method type GET 
# RoostTestHash=02b15e7ca7
# 
# 

# ********RoostGPT********
import pytest
from datetime import datetime

@pytest.mark.parametrize(
    "order_id, expected_status_code, valid_request",
    [
        (1, 200, True),  # Valid ID within range
        (6, 404, True),  # ID not in range, Order Not Found
        (0, 400, False), # Invalid ID (example: zero)
        (-1, 400, False),  # Negative ID
        ("test", 400, False), # Non-integer ID (e.g., string)
        (11, 200, True), # Valid ID within range
    ]
)
def test_get_order_by_id(api_client, order_id, expected_status_code, valid_request):
    """
    Test fetching order by ID for different scenarios.
    """
    response = api_client.get(f"store/order/{order_id}")

    assert response.status_code == expected_status_code, f"Unexpected status code: {response.status_code}"

    if response.status_code == 200 and valid_request:
        response_data = response.json()
        assert "id" in response_data
        assert "petId" in response_data
        assert "quantity" in response_data
        assert "shipDate" in response_data
        assert "status" in response_data
        assert "complete" in response_data

        # Validate example values
        assert isinstance(response_data["id"], int)
        assert isinstance(response_data["petId"], int)
        assert isinstance(response_data["quantity"], int)
        assert isinstance(response_data["shipDate"], str)  # Should be a date-time string
        assert datetime.fromisoformat(response_data["shipDate"].replace("Z", "+00:00"))  # Ensure valid date-time format
        assert isinstance(response_data["status"], str)
        assert isinstance(response_data["complete"], bool)

    elif response.status_code == 400:
        assert "Invalid" in response.text, "Expected error message for invalid ID"

    elif response.status_code == 404:
        assert "not found" in response.text, "Expected error message for non-existent order"


def test_get_order_invalid_endpoint(api_client):
    """
    Test accessing a non-existing endpoint.
    """
    response = api_client.get("store/order_non_existent/1")

    assert response.status_code == 404, f"Expected 404 for invalid endpoint, got {response.status_code}"


def test_get_order_no_auth(api_client):
    """
    Test fetching order without any authentication (if applicable).
    This assumes a security schema might be added in the future.
    """
    response = api_client.get("store/order/1", headers={})
    assert response.status_code != 401, "Unexpected Unauthorized error response."


def test_get_order_with_invalid_method(api_client):
    """
    Test unsupported HTTP methods (e.g., POST) on the endpoint.
    """
    response = api_client.get("store/order/1", headers={}, params=None)  # Should fail as it's a GET-only endpoint

    assert response.status_code in [400, 404]
