# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/{petId}/uploadImage_post for http method type POST 
# RoostTestHash=b2ab25b329
# 
# 

# ********RoostGPT********
import pytest


@pytest.mark.parametrize("petId, file_path, additionalMetadata, api_key, status_code, is_valid_schema", [
    (1, "tests/fixtures/sample_image.jpg", None, "VALID_API_KEY", 200, True),
    (1, "tests/fixtures/sample_image.jpg", "metadata", "VALID_API_KEY", 200, True),
    (1, None, None, "VALID_API_KEY", 400, False),
    (9999, "tests/fixtures/sample_image.jpg", None, "VALID_API_KEY", 404, False),
    (1, "tests/fixtures/sample_image.jpg", None, "INVALID_API_KEY", 401, False),
])
def test_upload_image(api_client, schema_validator, config, valid_api_key, petId, file_path, additionalMetadata, api_key, status_code, is_valid_schema):
    """
    Test uploading the image to `/pet/{petId}/uploadImage` endpoint with different scenarios.
    """
    endpoint = f"/pet/{petId}/uploadImage"
    headers = {
        "Authorization": f"Bearer {api_key}",
    }

    params = {}
    if additionalMetadata:
        params["additionalMetadata"] = additionalMetadata

    files = None
    if file_path:
        try:
            file = open(file_path, "rb")
            files = {"file": file}
        except FileNotFoundError:
            pytest.fail(f"File not found: {file_path}")

    response = api_client.helper.make_request(
        endpoint=endpoint, 
        params=params, 
        headers=headers, 
        method="POST"
    )
    
    if files:
        file.close()

    # Validate status code
    assert response.status_code == status_code, f"Expected {status_code}, got {response.status_code}"

    # Validate schema for successful response
    if status_code == 200 and is_valid_schema:
        assert schema_validator.validate_api_response_schema(response.json()), "Schema validation failed"

    # Additional check for specific error messages or conditions
    if status_code == 400:
        assert "No file uploaded" in response.text, "Expected 'No file uploaded' message"
    elif status_code == 404:
        assert "Pet not found" in response.text, "Expected 'Pet not found' message"


def test_missing_auth(api_client, schema_validator, config, petId=1):
    """
    Test uploading the image without providing authentication token.
    """
    endpoint = f"/pet/{petId}/uploadImage"
    headers = {}  # Missing OAuth token
    file_path = "tests/fixtures/sample_image.jpg"

    try:
        file = open(file_path, "rb")
        files = {"file": file}
    except FileNotFoundError:
        pytest.fail(f"File not found: {file_path}")

    response = api_client.helper.make_request(
        endpoint=endpoint, 
        headers=headers, 
        params={}, 
        method="POST"
    )
    file.close()

    assert response.status_code == 401, f"Expected 401 Unauthorized, got {response.status_code}"
    assert "Invalid API key" in response.text, "Expected error message for invalid API key"
