# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/findByStatus_get for http method type GET 
# RoostTestHash=d31df25c68
# 
# 

# ********RoostGPT********
import pytest

@pytest.mark.parametrize("status, expected_status_code, valid_auth", [
    ("available", 200, True),    # Valid status, valid authorization
    ("sold", 200, True),         # Valid status, valid authorization
    ("pending", 200, True),      # Valid status, valid authorization
    ("invalid", 400, True),      # Invalid status
    (None, 400, True),           # Missing status
    ("available", 401, False),   # Valid status, invalid authorization
])
def test_find_pets_by_status(api_client, valid_api_key, invalid_api_key, oauth2_token, status, expected_status_code, valid_auth, schema_validator):
    """
    Test the /pet/findByStatus endpoint
    with different statuses, authentication, and response codes.
    """
    # Set authentication based on `valid_auth`
    headers = {
        "Authorization": f"Bearer {oauth2_token}" if valid_auth else "Bearer invalid_token",
        "api_key": valid_api_key if valid_auth else invalid_api_key,
    }
    
    # Setup query parameters
    params = {"status": status} if status is not None else {}

    # Perform API request
    response = api_client.get("/pet/findByStatus", headers=headers, params=params)

    # Check response status code
    assert response.status_code == expected_status_code, f"Expected {expected_status_code}, got {response.status_code}"

    # Additional validations for 200 OK response
    if response.status_code == 200:
        response_json = response.json()

        # Check that the response is a list
        assert isinstance(response_json, list), "Response must be a list."

        # Validate individual pet schema
        for pet in response_json:
            assert schema_validator.validate_pet_schema(pet), f"Pet schema validation failed: {pet}"

    # Validate error scenarios
    elif response.status_code == 400:
        assert "Invalid status value" in response.text, "Expected 'Invalid status value' in response message"

    elif 500 <= response.status_code < 600:  # Unexpected server error
        assert "Unexpected error" in response.text, "Expected 'Unexpected error' in response message"
