# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/findByStatus_get for http method type GET 
# RoostTestHash=d31df25c68
# 
# 

# ********RoostGPT********
import pytest

@pytest.mark.parametrize("status, expected_status, expected_schema", [
    ("available", 200, "Pet"),
    ("pending", 200, "Pet"),
    ("sold", 200, "Pet"),
    ("invalid_status", 400, None),
])
def test_find_pets_by_status(api_client, valid_api_key, schema_validators, status, expected_status, expected_schema):
    """
    Test the /pet/findByStatus endpoint with different statuses.

    Args:
        api_client (APIClient): API client instance.
        valid_api_key (str): Valid API key.
        schema_validators (dict): Dictionary of schema validation functions.
        status (str): Status value to filter pets.
        expected_status (int): Expected HTTP status code.
        expected_schema (str | None): Expected response schema (None if not applicable).
    """

    # Define headers and parameters
    headers = {"api_key": valid_api_key}
    params = {"status": status}

    # Make request
    response = api_client.get("/pet/findByStatus", headers=headers, params=params)

    # Verify response status code
    assert response.status_code == expected_status, f"Expected {expected_status}, got {response.status_code}"

    # Verify response data schema (if applicable)
    if expected_schema and expected_status == 200:
        response_data = response.json()
        for pet in response_data:
            assert schema_validators[expected_schema](pet), f"Response schema validation failed for {pet}"

@pytest.mark.parametrize("api_key", [None, "INVALID_API_KEY"])
def test_find_pets_by_status_invalid_auth(api_client, api_key):
    """
    Test /pet/findByStatus endpoint with invalid or missing API key.

    Args:
        api_client (APIClient): API client instance.
        api_key (str | None): Invalid or missing API key.
    """

    # Define headers and parameters
    headers = {"api_key": api_key} if api_key else {}
    params = {"status": "available"}

    # Make request
    response = api_client.get("/pet/findByStatus", headers=headers, params=params)

    # Verify response status code
    assert response.status_code in [401, 403], f"Expected 401 or 403, got {response.status_code}"
