# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/findByStatus_get for http method type GET 
# RoostTestHash=d31df25c68
# 
# 

# ********RoostGPT********
import pytest


@pytest.mark.parametrize(
    "status_value, expected_status_code",
    [
        ("available", 200),
        ("pending", 200),
        ("sold", 200),
        ("invalid_status", 400),
    ],
)
def test_find_pets_by_status(
    api_client, valid_api_key, schema_validator, status_value, expected_status_code
):
    """
    Test the `findPetsByStatus` endpoint with various status values.

    This test covers the following:
    - Valid status values ('available', 'pending', 'sold').
    - An invalid status value ('invalid_status').
    - Schema validation against the expected pet object schema.
    """
    headers = {"api_key": valid_api_key}
    params = {"status": status_value}

    # Send GET request to the endpoint
    response = api_client.get("/pet/findByStatus", headers=headers, params=params)

    assert response.status_code == expected_status_code

    # Validate response schema for successful operations
    if expected_status_code == 200:
        response_data = response.json()
        assert isinstance(response_data, list), "Response should be a list of pet objects."

        # Validate each pet object in the response
        for pet in response_data:
            assert schema_validator.validate_pet_schema(pet)


def test_find_pets_by_status_missing_auth(api_client):
    """
    Test the `findPetsByStatus` endpoint without authentication.

    Expected behavior:
    - The server should return a 401 Unauthorized status.
    """
    response = api_client.get("/pet/findByStatus")

    assert response.status_code == 401
    assert response.json().get("message") == "Unauthorized"


@pytest.mark.parametrize(
    "status_value",
    ["available", "pending", "sold"],
)
def test_find_pets_by_status_invalid_api_key(api_client, invalid_api_key, status_value):
    """
    Test the `findPetsByStatus` endpoint with an invalid API key.

    Expected behavior:
    - The server should return a 403 Forbidden status.
    """
    headers = {"api_key": invalid_api_key}
    params = {"status": status_value}

    response = api_client.get("/pet/findByStatus", headers=headers, params=params)

    assert response.status_code == 403
    assert response.json().get("message") == "Forbidden"
