# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /user/{username}_get for http method type GET 
# RoostTestHash=c0fb7cdf2c
# 
# 

# ********RoostGPT********
# tests/test_user_api.py
import pytest
import requests
import yaml

# Load config data from yaml file
with open("config.yaml", "r") as config_file:
    config = yaml.safe_load(config_file)

BASE_URL = config["api"]["host"]
HEADERS_WITH_AUTH = {"Authorization": f"Bearer {config['authentication']['petstore_auth']}"}
HEADERS_WITH_API_KEY = {"api-key": config["authentication"]["api_key"]}

@pytest.fixture
def base_url():
    return f"{BASE_URL}/user"

@pytest.fixture
def valid_username():
    return "user1"

@pytest.fixture
def invalid_username():
    return "non_existing_user"

@pytest.mark.parametrize(
    "headers, username, expected_status, expected_keys",
    [
        (
            HEADERS_WITH_AUTH,
            "user1",
            200,
            ["id", "username", "firstName", "lastName", "email", "password", "phone", "userStatus"],
        ),
        (HEADERS_WITH_AUTH, "non_existing_user", 404, None),
    ],
)
def test_get_user_by_name_valid_auth(
    base_url, username, headers, expected_status, expected_keys
):
    """
    Test retrieving a user with valid authentication.
    Covers valid username and 404 case for non-existing username.
    """
    response = requests.get(f"{base_url}/{username}", headers=headers)
    assert response.status_code == expected_status
    if expected_status == 200:
        data = response.json()
        assert all(key in data for key in expected_keys)


@pytest.mark.parametrize(
    "headers, username, expected_status",
    [
        ({}, "user1", 401),
        ({"api-key": "invalid_key"}, "user1", 401),
        ({"Authorization": "Bearer invalid_token"}, "user1", 401),
    ],
)
def test_get_user_by_name_invalid_auth(base_url, username, headers, expected_status):
    """
    Test retrieving a user with invalid or missing authentication.
    """
    response = requests.get(f"{base_url}/{username}", headers=headers)
    assert response.status_code == expected_status


@pytest.mark.parametrize(
    "username, expected_status", [("", 400), (None, 400)]
)
def test_get_user_by_name_invalid_username(base_url, username, expected_status):
    """
    Test retrieving a user with an invalid username (empty or None).
    """
    url = f"{base_url}/" if username == "" else f"{base_url}/{username}"
    response = requests.get(url, headers=HEADERS_WITH_AUTH)
    assert response.status_code == expected_status


@pytest.mark.parametrize(
    "username, expected_status",
    [("user1", 200), ("user_not_found", 404), ("", 400)],
)
def test_edge_cases_username(base_url, username, expected_status):
    """
    Test edge cases for username.
    """
    url = f"{base_url}/{username}" if username else f"{base_url}/"
    response = requests.get(url, headers=HEADERS_WITH_AUTH)
    assert response.status_code == expected_status


@pytest.mark.parametrize(
    "headers",
    [HEADERS_WITH_AUTH, HEADERS_WITH_API_KEY]
)
def test_valid_auth_modes(base_url, valid_username, headers):
    """
    Test valid authentication modes (API key and Bearer token).
    """
    response = requests.get(f"{base_url}/{valid_username}", headers=headers)
    assert response.status_code == 200
    data = response.json()
    assert "username" in data


# Setup and Execution Instructions
# ---------------------------------
# To run the tests, you need to have Python and pytest installed on your system.
# 1. Install pytest: `pip install pytest`
# 2. Place this file in your test directory.
# 3. Ensure "config.yaml" with API details is in the same directory as the test file.
# 4. Run the tests using `pytest tests/test_user_api.py`.

