# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /user/login_get for http method type GET 
# RoostTestHash=fbb4064353
# 
# 

# ********RoostGPT********
# config.yml
api:
  host: "https://petstore3.swagger.io/api/v3/"
authentication:
  petstore_auth: "auth-token"
  api_key: "apikey"
