# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /user/logout_get for http method type GET 
# RoostTestHash=1092b8f68f
# 
# 

# ********RoostGPT********
# tests/test_user_logout.py

import pytest

ENDPOINT = "/user/logout"

@pytest.mark.parametrize(
    "headers, expected_status_code, description",
    [
        # Test with valid API key
        (
            {"Authorization": "Bearer valid_api_key"},
            200,
            "Valid API key - Successful logout",
        ),
        # Test with missing API key
        (
            None,
            403,
            "Missing API key - Access forbidden",
        ),
        # Test with invalid API key
        (
            {"Authorization": "Bearer invalid_api_key"},
            403,
            "Invalid API key - Access forbidden",
        ),
    ],
)
def test_user_logout(api_client, headers, expected_status_code, description):
    """
    Test the /user/logout endpoint for different authentication scenarios.
    """
    response = api_client.get(ENDPOINT, headers=headers)
    assert response.status_code == expected_status_code, f"Failed: {description}"

    if response.status_code == 200:
        assert response.text == "successful operation"
    elif response.status_code in (403, 401):
        assert "error" in response.text.lower()


@pytest.mark.parametrize(
    "headers, expected_status_code, description",
    [
        # Valid OAuth2 token test
        (
            {"Authorization": "Bearer valid_oauth_token"},
            200,
            "Valid OAuth2 token - Successful logout",
        ),
        # Expired OAuth2 token test
        (
            {"Authorization": "Bearer expired_oauth_token"},
            401,
            "Expired OAuth2 token - Unauthorized",
        ),
    ],
)
def test_user_logout_with_oauth2(api_client, headers, expected_status_code, description):
    """
    Test the /user/logout endpoint with OAuth2 tokens.
    """
    response = api_client.get(ENDPOINT, headers=headers)
    assert response.status_code == expected_status_code, f"Failed: {description}"

    if response.status_code == 200:
        assert response.text == "successful operation"
    elif response.status_code == 401:
        assert "unauthorized" in response.text.lower()
