# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/{petId}/uploadImage_post for http method type POST 
# RoostTestHash=b2ab25b329
# 
# 

# ********RoostGPT********
import pytest
import json
import os


# Load test data from JSON file
def load_test_data(file_path):
    with open(file_path, "r") as file:
        return json.load(file)


@pytest.fixture(scope="module")
def test_data():
    test_data_file = os.path.join(os.path.dirname(__file__), "SWAGGER_PETSTORE_OPENAPI_30_pet_petId_uploadImage.json")
    return load_test_data(test_data_file)


@pytest.mark.parametrize("test_case", load_test_data(os.path.join(os.path.dirname(__file__), "SWAGGER_PETSTORE_OPENAPI_30_pet_petId_uploadImage.json")))
def test_pet_upload_image(api_client, config, schema_validator, valid_api_key, test_case):
    """
    Tests the /pet/{petId}/uploadImage endpoint.

    Args:
        api_client: Fixture for API client
        config: Application configuration
        schema_validator: Fixture for schema validation
        valid_api_key: Valid API key
        test_case: Single test case from the test data JSON file
    """
    endpoint = f"/pet/{test_case['petId']}/uploadImage"
    query_params = {"additionalMetadata": test_case["additionalMetadata"]}
    headers = {"Authorization": f"Bearer {valid_api_key}"}
    response = None

    try:
        response = api_client.helper.make_request(
            endpoint=endpoint,
            params=query_params,
            headers=headers,
            method='POST'
        )
    except RuntimeError as e:
        assert str(e), f"Request failed for scenario: {test_case['scenario']}"

    # Assertions
    assert response.status_code == test_case["statusCode"], f"Status code mismatch on scenario: {test_case['scenario']}"

    if response.status_code == 200:
        assert schema_validator.validate_schema_apiresponse(response.json()), f"Schema validation failed on scenario: {test_case['scenario']}"
    elif response.status_code == 400:
        assert response.json()["message"] == "No file uploaded", f"Error message mismatch on scenario: {test_case['scenario']}"
    elif response.status_code == 404:
        assert response.json()["message"] == "Pet not found", f"Error message mismatch on scenario: {test_case['scenario']}"
    elif test_case["statusCode"] == "default":
        assert "Unexpected error" in response.json()["message"], f"Default error handling failed on scenario: {test_case['scenario']}"
