# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/{petId}/uploadImage_post for http method type POST 
# RoostTestHash=b2ab25b329
# 
# 

# ********RoostGPT********
import os
import pytest
import json

@pytest.fixture(scope="module")
def test_data():
    """Load input JSON test cases."""
    current_dir = os.path.dirname(__file__)
    file_path = os.path.join(current_dir, "pet_petId_uploadImage.json")
    with open(file_path, "r") as f:
        return json.load(f)

@pytest.fixture()
def headers(valid_api_key):
    """Return default headers with valid API key."""
    return {"Authorization": f"Bearer {valid_api_key}"}

@pytest.fixture()
def invalid_headers(invalid_api_key):
    """Return headers with an invalid API key."""
    return {"Authorization": f"Bearer {invalid_api_key}"}

@pytest.mark.parametrize("test_case", ["200", "400", "404", "500"])
def test_upload_image(
    api_client,
    schema_validator,
    headers,
    invalid_headers,
    oauth2_token,
    config,
    test_data,
    test_case,
):
    """
    Testing /pet/{petId}/uploadImage endpoint with various scenarios.
    """
    for data in test_data:
        # Extract details from test data
        pet_id = data["petId"]
        additional_metadata = data["additionalMetadata"]
        expected_status_code = data["statusCode"]
        scenario = data["scenario"]

        # File payload (mimic file upload via binary format)
        files = {"file": ("test_image.jpg", b"FakeImageData", "image/jpeg")}

        # Base endpoint with petId
        endpoint = f"pet/{pet_id}/uploadImage"

        # Set headers dynamically for scenario-based testing
        chosen_headers = headers
        if scenario == "Unauthorized":
            chosen_headers = invalid_headers

        # Handle query parameters dynamically
        query_params = {"additionalMetadata": additional_metadata}

        # Make the API call
        response = api_client.get(
            method="POST",
            endpoint=endpoint,
            headers=chosen_headers,
            params=query_params,
            files=files,
        )

        # Assert response status code
        assert response.status_code == expected_status_code, f"Failed for scenario {scenario}. Expected {expected_status_code}, got {response.status_code}"

        if response.status_code == 200:
            # Validate response schema for successful operation
            assert schema_validator.validate_schema_api_response(response.json()), "Schema validation failed for 200 response."

        elif response.status_code == 400:
            # Assert descriptive error info for 400
            assert "No file uploaded" in response.text

        elif response.status_code == 404:
            # Assert descriptive error info for 404
            assert "Pet not found" in response.text

        elif response.status_code == 500:
            # Assert descriptive error info for 500
            assert "Internal Server Error" in response.text

