# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /astronomy.json_get for http method type GET 
# RoostTestHash=656c29a7ca
# 
# 

# ********RoostGPT********
import pytest
import os
import json
from validator import SwaggerSchemaValidator

# Path to the OpenAPI specification file
API_SPEC_PATH = os.path.join(os.path.dirname(__file__), "api.json")
VALIDATOR = SwaggerSchemaValidator(API_SPEC_PATH)

# Path to the astronomy test data JSON file
TEST_DATA_PATH = os.path.join(os.path.dirname(__file__), "astronomy_json.json")

@pytest.mark.parametrize("test_input", json.load(open(TEST_DATA_PATH, 'r')))
def test_astronomy_endpoint(api_client, valid_api_key, test_input):
    """
    Test the /v1/astronomy.json endpoint

    Args:
    - api_client: API client fixture
    - valid_api_key: Valid API key fixture
    - test_input: Test case data loaded from JSON file

    Steps:
    1. Validate request schema before sending.
    2. Execute API call.
    3. Validate response schema and data.
    """
    endpoint = "/v1/astronomy.json"
    params = {
        "q": test_input["q"],
        "dt": test_input["dt"]
    }
    headers = {"Authorization": f"Bearer {valid_api_key}"}

    # Validate the request before sending
    VALIDATOR.validate_with_schema(params, {
        "type": "object",
        "properties": {
            "q": {"type": "string"},
            "dt": {"type": "string", "format": "date"}
        },
        "required": ["q", "dt"]
    })

    # Send GET request
    response = api_client.get(endpoint, headers=headers, params=params)

    # Assert response status code
    assert response.status_code == test_input["statusCode"], f"Expected {test_input['statusCode']}, but got {response.status_code}"

    # Validate response
    if response.status_code == 200:
        VALIDATOR.validate_json(response.json(), "200_Response")
        assert "location" in response.json()
        assert "astronomy" in response.json()
    elif response.status_code == 400:
        VALIDATOR.validate_json(response.json(), "400_Response")
    elif response.status_code == 401:
        VALIDATOR.validate_json(response.json(), "401_Response")
    elif response.status_code == 403:
        VALIDATOR.validate_json(response.json(), "403_Response")

@pytest.mark.parametrize("invalid_key", ["INVALID_API_KEY_123", ""])
def test_authentication_errors(api_client, invalid_key, valid_location):
    """
    Test /v1/astronomy.json endpoint with invalid API key

    Args:
    - api_client: API client fixture
    - invalid_key: Invalid API key
    - valid_location: Valid location data

    Steps:
    1. Execute API call with invalid API key.
    2. Assert response status code and message.
    """
    endpoint = "/v1/astronomy.json"
    params = {"q": valid_location["latitude"], "dt": "2023-10-01"}
    headers = {"Authorization": f"Bearer {invalid_key}"}

    # Send GET request
    response = api_client.get(endpoint, headers=headers, params=params)

    # Assert 401 Unauthorized response
    assert response.status_code == 401, f"Expected 401 Unauthorized, but got {response.status_code}"
    VALIDATOR.validate_json(response.json(), "401_Response")

@pytest.mark.parametrize("test_input", json.load(open(TEST_DATA_PATH, 'r')))
def test_edge_case_scenarios(api_client, valid_api_key, test_input):
    """
    Test edge cases for /v1/astronomy.json endpoint.

    Args:
    - api_client: API client fixture
    - valid_api_key: Valid API key fixture
    - test_input: Test case data loaded from JSON file

    Steps:
    1. Execute API call with edge case data.
    2. Validate response schema and data.
    """
    endpoint = "/v1/astronomy.json"
    params = {
        "q": test_input["q"],
        "dt": test_input["dt"]
    }
    headers = {"Authorization": f"Bearer {valid_api_key}"}

    # Validate the request before sending (Boundary/Edge cases should throw ValidationError if invalid)
    try:
        VALIDATOR.validate_with_schema(params, {
            "type": "object",
            "properties": {
                "q": {"type": "string"},
                "dt": {"type": "string", "format": "date"}
            },
            "required": ["q", "dt"]
        })
    except ValidationError as error:
        pytest.skip("Invalid payload provided as part of test data")

    response = api_client.get(endpoint, headers=headers, params=params)

    # Assert response status code
    assert response.status_code == test_input["statusCode"], f"Expected {test_input['statusCode']}, but got {response.status_code}"

    # Validate response schema based on status code
    if response.status_code == 200:
        VALIDATOR.validate_json(response.json(), "200_Response")
    elif response.status_code == 400:
        VALIDATOR.validate_json(response.json(), "400_Response")
    
def test_missing_authentication(api_client, valid_location):
    """
    Test /v1/astronomy.json endpoint without authentication

    Args:
    - api_client: API client fixture
    - valid_location: Valid location data

    Steps:
    1. Execute API call without authentication header.
    2. Assert response status code and validation errors.
    """
    endpoint = "/v1/astronomy.json"
    params = {"q": valid_location["latitude"], "dt": "2023-10-01"}

    # Send GET request without authentication header
    response = api_client.get(endpoint, headers=None, params=params)

    # Assert 401 Unauthorized response
    assert response.status_code == 401, f"Expected 401 Unauthorized, but got {response.status_code}"
    VALIDATOR.validate_json(response.json(), "401_Response")

# Instructions for Test Execution
"""
To execute the test suite, run the following command in the terminal:
$ pytest -v

Ensure the following environment variables are set:
- WEATHER_API_API_HOST: Base URL for the API
- key: Valid API key for authentication
"""
