# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /astronomy.json_get for http method type GET 
# RoostTestHash=656c29a7ca
# 
# 

# ********RoostGPT********
import pytest
import os
import json
from validator import SwaggerSchemaValidator

# Load Swagger Schema and Validator
swagger_spec_path = os.path.join(os.path.dirname(__file__), "api.json")
schema_validator = SwaggerSchemaValidator(swagger_spec_path)

# Load Astronomy JSON Test Data
test_data_path = os.path.join(os.path.dirname(__file__), "astronomy.json.json")
with open(test_data_path, 'r') as f:
    test_data = json.load(f)

@pytest.mark.parametrize("test_case", test_data)
def test_astronomy_endpoint(api_client, valid_api_key, test_case):
    """
    Test the /v1/astronomy.json endpoint with valid and invalid payloads.

    Args:
        api_client: Fixture that provides APIClient instance.
        valid_api_key: Fixture providing a valid API key.
        test_case: Parameterized test case from astronomy.json.json
    """
    endpoint = "/v1/astronomy.json"
    headers = {"key": valid_api_key}
    params = {"q": test_case["q"], "dt": test_case["dt"]}

    # Validate request payload using schema (if necessary)
    request_schema_name = "AstronomyRequest"  # Replace with actual schema name if defined in Swagger spec
    try:
        schema_validator.validate_with_schema(json_data=params, schema=schema_validator.get_schema(request_schema_name))
    except Exception as e:
        pytest.fail(f"Request validation failed: {str(e)}")

    # Make API call
    response = api_client.get(endpoint, headers=headers, params=params)
    assert response.status_code == test_case["statusCode"], f"Expected {test_case['statusCode']} but got {response.status_code}"

    # Validate response based on status code
    response_schema_name = "AstronomyResponse" if response.status_code == 200 else "ErrorResponse"
    try:
        schema_validator.validate_with_schema(json_data=response.json(), schema=schema_validator.get_schema(response_schema_name))
    except Exception as e:
        pytest.fail(f"Response validation failed: {str(e)}")

@pytest.mark.parametrize("test_case", test_data)
def test_astronomy_endpoint_with_invalid_key(api_client, invalid_api_key, test_case):
    """
    Test the /v1/astronomy.json endpoint with an invalid API key.

    Args:
        api_client: Fixture that provides APIClient instance.
        invalid_api_key: Fixture providing an invalid API key.
        test_case: Parameterized test case from astronomy.json.json
    """
    endpoint = "/v1/astronomy.json"
    headers = {"key": invalid_api_key}
    params = {"q": test_case["q"], "dt": test_case["dt"]}

    # Make API call
    response = api_client.get(endpoint, headers=headers, params=params)
    assert response.status_code == 401  # Expect Unauthorized status code

    # Validate error response schema
    try:
        schema_validator.validate_with_schema(json_data=response.json(), schema=schema_validator.get_schema("ErrorResponse"))
    except Exception as e:
        pytest.fail(f"Response validation failed for invalid key: {str(e)}")

def test_missing_auth(api_client):
    """
    Test the /v1/astronomy.json endpoint with missing API key.

    Args:
        api_client: Fixture that provides APIClient instance.
    """
    endpoint = "/v1/astronomy.json"
    params = {"q": "New York", "dt": "2023-10-10"}

    # Make API call without authentication headers
    response = api_client.get(endpoint, headers=None, params=params)
    assert response.status_code == 401  # Expect Unauthorized status code

    # Validate error response schema
    try:
        schema_validator.validate_with_schema(json_data=response.json(), schema=schema_validator.get_schema("ErrorResponse"))
    except Exception as e:
        pytest.fail(f"Response validation failed for missing auth: {str(e)}")

@pytest.mark.parametrize("test_case", test_data)
def test_invalid_request_payload(api_client, valid_api_key, test_case):
    """
    Test the /v1/astronomy.json endpoint with invalid request payloads.

    Args:
        api_client: Fixture that provides APIClient instance.
        valid_api_key: Fixture providing a valid API key.
        test_case: Parameterized test case from astronomy.json.json
    """
    endpoint = "/v1/astronomy.json"
    headers = {"key": valid_api_key}
    params = {"q": test_case["q"], "dt": test_case["dt"]}

    # Skip valid test cases
    if test_case["statusCode"] == 200:
        pytest.skip("This test targets invalid request payloads!")

    # Make API call
    response = api_client.get(endpoint, headers=headers, params=params)
    assert response.status_code == test_case["statusCode"], f"Expected {test_case['statusCode']} but got {response.status_code}"

    # Validate error response schema
    try:
        schema_validator.validate_with_schema(json_data=response.json(), schema=schema_validator.get_schema("ErrorResponse"))
    except Exception as e:
        pytest.fail(f"Response validation failed for invalid payload: {str(e)}")
