# ********RoostGPT********

# Test generated by RoostGPT for test roost_test using AI Type Azure Open AI and AI Model gpt-4o
# 
# Test file generated for /astronomy.json_get for http method type GET 
# RoostTestHash=656c29a7ca
# 
# 

# ********RoostGPT********
import pytest
import json
from pathlib import Path
from validator import SwaggerSchemaValidator

# Load API Specification
api_spec_path = Path(__file__).parent / "api.json"
swagger_validator = SwaggerSchemaValidator(api_spec_path)

# Load test data from JSON file
test_data_path = Path(__file__).parent / "astronomy.json"
with open(test_data_path, "r") as file:
    test_data = json.load(file)

@pytest.fixture(scope="module")
def validate_200_response_schema():
    return swagger_validator.get_schema("200")

@pytest.fixture(scope="module")
def validate_400_response_schema():
    return swagger_validator.get_schema("400")

@pytest.fixture(scope="module")
def validate_401_response_schema():
    return swagger_validator.get_schema("401")

@pytest.fixture(scope="module")
def validate_403_response_schema():
    return swagger_validator.get_schema("403")

@pytest.fixture(scope="module")
def endpoint():
    return "/v1/astronomy.json"

@pytest.mark.parametrize("data", test_data)
def test_astronomy_api(api_client, valid_api_key, endpoint, validate_200_response_schema, validate_400_response_schema, validate_401_response_schema, validate_403_response_schema, data):
    """
    Test Astronomy API for valid and invalid scenarios.

    Args:
        api_client: API client fixture.
        valid_api_key: Authentication key from config.yml.
        endpoint: API endpoint path.
        validate_200_response_schema: Validator for 200 response schema.
        validate_400_response_schema: Validator for 400 response schema.
        validate_401_response_schema: Validator for 401 response schema.
        validate_403_response_schema: Validator for 403 response schema.
        data: Test data from astronomy.json.
    """
    headers = {
        "Authorization": f"ApiKey {valid_api_key}"
    }
    params = {
        "q": data.get("q"),
        "dt": data.get("dt")
    }
    expected_status = data.get("statusCode")
    scenario = data.get("scenario")

    response = api_client.get(endpoint=endpoint, headers=headers, params=params)

    assert response.status_code == expected_status, f"Scenario: {scenario}"
    
    if response.status_code == 200:
        assert swagger_validator.validate_with_schema(response.json(), validate_200_response_schema) is True
    elif response.status_code == 400:
        assert swagger_validator.validate_with_schema(response.json(), validate_400_response_schema) is True
    elif response.status_code == 401:
        assert swagger_validator.validate_with_schema(response.json(), validate_401_response_schema) is True
    elif response.status_code == 403:
        assert swagger_validator.validate_with_schema(response.json(), validate_403_response_schema) is True
    else:
        pytest.fail(f"Unhandled response status code: {response.status_code}")

def test_invalid_api_key(api_client, invalid_api_key, endpoint):
    """
    Test Astronomy API with an invalid API key.
    
    Args:
        api_client: API client fixture.
        invalid_api_key: Placeholder invalid API key.
        endpoint: API endpoint path.
    """
    headers = {
        "Authorization": f"ApiKey {invalid_api_key}"
    }
    params = {
        "q": "London",
        "dt": "2023-09-01"
    }

    response = api_client.get(endpoint=endpoint, headers=headers, params=params)
    assert response.status_code == 401, "Expected 401 Unauthorized"
    assert swagger_validator.validate_with_schema(response.json(), swagger_validator.get_schema("401")) is True

def test_missing_auth(api_client, endpoint):
    """
    Test Astronomy API without any authentication key.
    
    Args:
        api_client: API client fixture.
        endpoint: API endpoint path.
    """
    params = {
        "q": "London",
        "dt": "2023-09-01"
    }

    response = api_client.get(endpoint=endpoint, headers=None, params=params)
    assert response.status_code == 401, "Expected 401 Unauthorized"
    assert swagger_validator.validate_with_schema(response.json(), swagger_validator.get_schema("401")) is True

def test_rate_limit_exceeded(api_client, valid_api_key, endpoint):
    """
    Test Astronomy API for rate limit exceeded scenario.
    
    Args:
        api_client: API client fixture.
        valid_api_key: Authentication key from config.yml.
        endpoint: API endpoint path.
    """
    headers = {
        "Authorization": f"ApiKey {valid_api_key}"
    }
    params = {
        "q": "London",
        "dt": "2023-09-01"
    }

    response = api_client.get(endpoint=endpoint, headers=headers, params=params)
    assert response.status_code == 403, "Expected 403 Forbidden"
    assert swagger_validator.validate_with_schema(response.json(), swagger_validator.get_schema("403")) is True
